# EXTRACCION DATOS API LAST.FM

lista de artistas ya seleccionados:

In [28]:
import requests
import time
import pandas as pd
import json

In [29]:
artistas = [
    'Taylor Swift', 'Drake', 'Morgan Wallen', 'Kendrick Lamar',
    'The Weeknd', 'SZA', 'Zach Bryan', 'Tyler The Creator',
    'Billie Eilish', 'Ariana Grande', 'Bad Bunny', 'Karol G',
    'Myke Towers', 'Quevedo', 'Aitana', 'Rosalía', 'Morad',
    'Melendi', 'Enrique Iglesias', 'Juanes', 'Duki',
    'María Becerra', 'Tini Stoessel', 'Nicki Nicole', 'Cazzu',
    'Lali', 'Paulo Londra', 'Shakira', 'Bizarrap', 'Emilia'
]

In [30]:
api_key = "197275203e5eeefad448fda24601b401"
api_url = "http://ws.audioscrobbler.com/2.0/"

In [31]:
url = "http://ws.audioscrobbler.com/2.0/"

params = {
    "method": "artist.getInfo",
    "artist": "Taylor Swift",       ## pruebo primero con 1 para q no se pille.
    "api_key": "197275203e5eeefad448fda24601b401",
    "format": "json"
}

respuesta = requests.get(url, params=params)
datos = respuesta.json()

print(datos)

{'artist': {'name': 'Taylor Swift', 'mbid': '20244d07-534f-4eff-b4d4-930878889970', 'url': 'https://www.last.fm/music/Taylor+Swift', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}], 'streamable': '0', 'ontour': '0', 'stats': {'listeners': '5941473', 'playcount': '3677983140'}, 'similar': {'artist': [{'name': 'Sabrina Carpenter', 'url': 'https://www.last.fm/music/Sabrina+Carpenter', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Olivia Rodrigo', 'url': 'https://www.last.fm/music/Olivia+Rodrigo', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Gracie Abrams', 'url': 'https://www.last.fm/music/Gracie+Abrams', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Harry Styles', 'url': 'https://www.last.fm/music/Harry+Styles', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Chappell Roan', 'url': 'https://www.last.fm/music/Chappell+Roan', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}]}, 'tags': {'tag': [{'name': 'country', 'url': 'https://www.last.fm/tag/country'}, {'name': 'pop', 'url': 'https://www.last.fm/tag/pop'}, {'name': 'female vocalists', 'url': 'https://www.last.fm/tag/female+vocalists'}, {'name': 'singer-songwriter', 'url': 'https://www.last.fm/tag/singer-songwriter'}, {'name': 'acoustic', 'url': 'https://www.last.fm/tag/acoustic'}]}, 'bio': {'links': {'link': {'#text': '', 'rel': 'original', 'href': 'https://last.fm/music/Taylor+Swift/+wiki'}}, 'published': '16 Aug 2006, 21:31', 'summary': 'Taylor Alison Swift is an American singer-songwriter. Her discography spans multiple genres, and her narrative songwriting, which is often inspired by her personal life, has received widespread media coverage and critical praise.\n\nSwift rose to mainstream prominence with her sophomore studio album, Fearless (2008), a country pop record with crossover appeal. Aided by the top-five singles “Love Story” and “You Belong with Me”, Fearless was certified Diamond by the Recording Industry Recording Industry Association of America (RIAA). <a href="https://www.last.fm/music/Taylor+Swift">Read more on Last.fm</a>', 'content': 'Taylor Alison Swift is an American singer-songwriter. Her discography spans multiple genres, and her narrative songwriting, which is often inspired by her personal life, has received widespread media coverage and critical praise.\n\nSwift rose to mainstream prominence with her sophomore studio album, Fearless (2008), a country pop record with crossover appeal. Aided by the top-five singles “Love Story” and “You Belong with Me”, Fearless was certified Diamond by the Recording Industry Recording Industry Association of America (RIAA). Swift\'s third studio album, Speak Now (2010), blended country pop with elements of rock and featured the top-ten singles “Mine” and “Back to December”.\n\nDrawing inspiration from various pop, rock, and electronic genres, Swift\'s fourth studio album Red (2012) saw her transcending her country roots. She completely moved to pop with her synth-pop fifth studio album, 1989 (2014), and expanded the electropop sound on her next two studio albums, reputation (2017) and Lover (2019), which respectively embraced urban and retro styles. The four albums spawned a string of international top-five singles, including “We Are Never Ever Getting Back Together”, “I Knew You Were Trouble”, “Shake It Off”, “Blank Space”, “Bad Blood”, “Look What You Made Me Do”, “ME! (feat. Brendon Urie of Panic! at the Disco)”, “You Need to Calm Down”, and “Lover”.\n\nIn the midst of the COVID-19 pandemic, Swift experimented with folk and alternative rock on her eighth and ninth studio albums, folklore and evermore (both 2020), whose lead singles “cardigan” and “willow” topped charts around the world. She also released the critically acclaimed documentaries Miss Americana and Folklore: The Long Pond Studio Sessions that year. Swift\'s tenth studio album, Midnights (2022), marked her triumphant return to pop after two folk albums. The album set the record for biggest first day and first week ever on Spotify, spawned the hits Anti-Hero and Lavender Haze, and sold over 1.5 million copies in its first week becoming not only the biggest debut of the decade but also Swift\'s biggest debut ever. She would make history by becoming the first artist to occupy the entire top ten of the Billboard Hot 100 with tracks from Midnights.\n\nAdditionally, Swift began re-recording her back catalog in November 2020 as a result of a publicized dispute with talent manager Scooter Braun and her former label Big Machine, regarding the acquisition of the masters of her back catalog. In April 2021, Swift released a re-recorded issue of her 2008 album Fearless, titled Fearless (Taylor\'s Version). It debuted at number one in the US. Swift continued releasing re-recorded versions of her back catalog in November, 2021 with the release of Red (Taylor\'s Version), a 30 track re-issue of her 2012 critical smash. The album debuted at #1 in the US, spawned the #1 hit All Too Well (10 Minute Version) (Taylor\'s Version) (From the Vault), and broke the record at the time for biggest first day for a female album on Spotify. Red (Taylor\'s Version) was a critical and commercial hit, and proved that Swift\'s ambitious, yet ongoing plan to re-record her first 6 albums was well worth it.\n\nAlong with the release of Red (Taylor\'s Version) came All Too Well: The Short Film (2021), Swift\'s filmmaking debut. The 15 minute romantic drama was based on the lyrical content from Swift\'s 2012 fan favorite “All Too Well” starring Sadie Sink and Dylan O\'Brien. It had a limited theatrical release in major cities, and Swift held special screenings of the film throughout 2022 at various film festivals. In December, 2022 Taylor announced that she would be making her feature directorial debut with Oscar-winning studio Searchlight Pictures.\n\nFollowing the release of Midnights, Swift would embark on her first tour in five years, The Eras Tour—a retrospective tour covering the entirety of her discography. During her ongoing tour, Swift would release her next two re-recorded albums, Speak Now (Taylor\'s Version) in July and 1989 (Taylor\'s Version) in October of 2023. The former of which would land Swift as the woman with the most number-one albums (12) in Billboard 200 history, surpassing Barbra Streisand. The latter was her sixth album to sell one million copies in a single week in the US, her largest album sales in a week span. “Is It Over Now? (Taylor\'s Version)”, the lead single for 1989 (Taylor\'s Version), would peak at number one on the Billboard Hot 100.\n\nAt the 66th annual GRAMMY Awards, Taylor Swift surprised viewers by announcing her eleventh studio album, THE TORTURED POETS DEPARTMENT. On April 19, 2024, the album was released globally, breaking records: it became the first ever to amass 1 billion Spotify streams in a week and sold 2.6 million units in its first week in the US. Swift dominated the charts, monopolizing the top 14 spots on the Billboard Hot 100 and securing the top 10 positions on Australia’s ARIA Singles Chart. The lead single, Fortnight, featuring Post Malone, quickly soared to the number-one position on the Hot 100. Additionally, just two hours after the album’s release, Swift surprised fans with a reissue titled THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY, which included 15 extra songs.\n\nSwift has released several songs for film soundtracks. She co-wrote two songs for the Hannah Montana: The Movie soundtrack— “You\'ll Always Find Your Way Back Home” and “Crazier”, and contributed two songs to the Valentine\'s Day soundtrack, including the single “Today Was a Fairytale”, which was her first number one on the Canadian Hot 100, and peaked at number two on the Billboard Hot 100. She also contributed two original songs to The Hunger Games soundtrack album: “Safe & Sound - from The Hunger Games Soundtrack”, co-written and recorded with The Civil Wars and T-Bone Burnett, and “Eyes Open”. “Safe & Sound” won the Grammy Award for Best Song Written for Visual Media and was nominated for the Golden Globe Award for Best Original Song. In 2013, Swift recorded “Sweeter than Fiction”, a song she wrote and produced with Jack Antonoff for the One Chance film soundtrack, which received a Best Original Song nomination at the 71st Golden Globe Awards. Swift and English singer Zayn Malik, mononymously known as Zayn, released a single together, “I Don\'t Wanna Live Forever”, for the soundtrack of the film Fifty Shades Darker (2017). She also recorded an original song called “Beautiful Ghosts”, which she wrote with Andrew Lloyd Webber for the Cats\'s soundtrack (2019). In 2020, Swift\'s documentary Miss Americana featured the song “Only the Young” which was written after the 2018 United States elections. In 2022, she released an original song titled “Carolina” for Where The Crawdads Sing (2022) inspired by the novel written by Delia Owens.\n\nWith sales of over 200 million records worldwide, Swift is a best-selling music artist. Her accolades include 14 Grammy Awards, including four Album of the Year wins, which makes Swift the artist with the most awards for that category in history, two Brit Awards (including a Global Icon award), an Emmy Award, 28 Guinness World Records, 32 American Music Awards (the most wins by an artist), and 23 Billboard Music Awards (the most wins by a woman). She ranked eighth on Billboard\'s Greatest of All Time Artists Chart (2019) and was listed on Rolling Stone\'s 100 Greatest Songwriters of All Time (2015). Swift has been included in various power rankings, such as Time\'s annual list of the 100 most influential people in the world (2010, 2015 and 2019) and Forbes Celebrity 100 (placing first in 2016 and 2019). She was named Woman of the Decade (2010s) by Billboard, Artist of the Decade (2010s) by the American Music Awards, and Person of the Year (2023) by Time Magazine. <a href="https://www.last.fm/music/Taylor+Swift">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

In [32]:
datos

{'artist': {'name': 'Taylor Swift',
  'mbid': '20244d07-534f-4eff-b4d4-930878889970',
  'url': 'https://www.last.fm/music/Taylor+Swift',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}],
  'streamable': '0',
  'ontour': '0',
  'stats': {'listeners': '5941473', 'playcount': '3677983140'},
  'similar': {'artist': [{'name': 'Sabrina Carpenter',
     'url': 'https://www.last.fm/music/Sabrina+Carpenter',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Olivia Rodrigo',
     'url': 'https://www.last.fm/music/Olivia+Rodrigo',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Gracie Abrams',
     'url': 'https://www.last.fm/music/Gracie+Abrams',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Harry Styles',
     'url': 'https://www.last.fm/music/Harry+Styles',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Chappell Roan',
     'url': 'https://www.last.fm/music/Chappell+Roan',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]}]},
  'tags': {'tag': [{'name': 'country',
     'url': 'https://www.last.fm/tag/country'},
    {'name': 'pop', 'url': 'https://www.last.fm/tag/pop'},
    {'name': 'female vocalists',
     'url': 'https://www.last.fm/tag/female+vocalists'},
    {'name': 'singer-songwriter',
     'url': 'https://www.last.fm/tag/singer-songwriter'},
    {'name': 'acoustic', 'url': 'https://www.last.fm/tag/acoustic'}]},
  'bio': {'links': {'link': {'#text': '',
     'rel': 'original',
     'href': 'https://last.fm/music/Taylor+Swift/+wiki'}},
   'published': '16 Aug 2006, 21:31',
   'summary': 'Taylor Alison Swift is an American singer-songwriter. Her discography spans multiple genres, and her narrative songwriting, which is often inspired by her personal life, has received widespread media coverage and critical praise.\n\nSwift rose to mainstream prominence with her sophomore studio album, Fearless (2008), a country pop record with crossover appeal. Aided by the top-five singles “Love Story” and “You Belong with Me”, Fearless was certified Diamond by the Recording Industry Recording Industry Association of America (RIAA). <a href="https://www.last.fm/music/Taylor+Swift">Read more on Last.fm</a>',
   'content': 'Taylor Alison Swift is an American singer-songwriter. Her discography spans multiple genres, and her narrative songwriting, which is often inspired by her personal life, has received widespread media coverage and critical praise.\n\nSwift rose to mainstream prominence with her sophomore studio album, Fearless (2008), a country pop record with crossover appeal. Aided by the top-five singles “Love Story” and “You Belong with Me”, Fearless was certified Diamond by the Recording Industry Recording Industry Association of America (RIAA). Swift\'s third studio album, Speak Now (2010), blended country pop with elements of rock and featured the top-ten singles “Mine” and “Back to December”.\n\nDrawing inspiration from various pop, rock, and electronic genres, Swift\'s fourth studio album Red (2012) saw her transcending her country roots. She completely moved to pop with her synth-pop fifth studio album, 1989 (2014), and expanded the electropop sound on her next two studio albums, reputation (2017) and Lover (2019), which respectively embraced urban and retro styles. The four albums spawned a string of international top-five singles, including “We Are Never Ever Getting Back Together”, “I Knew You Were Trouble”, “Shake It Off”, “Blank Space”, “Bad Blood”, “Look What You Made Me Do”, “ME! (feat. Brendon Urie of Panic! at the Disco)”, “You Need to Calm Down”, and “Lover”.\n\nIn the midst of the COVID-19 pandemic, Swift experimented with folk and alternative rock on her eighth and ninth studio albums, folklore and evermore (both 2020), whose lead singles “cardigan” and “willow” topped charts around the world. She also released the critically acclaimed documentaries Miss Americana and Folklore: The Long Pond Studio Sessions that year. Swift\'s tenth studio album, Midnights (2022), marked her triumphant return to pop after two folk albums. The album set the record for biggest first day and first week ever on Spotify, spawned the hits Anti-Hero and Lavender Haze, and sold over 1.5 million copies in its first week becoming not only the biggest debut of the decade but also Swift\'s biggest debut ever. She would make history by becoming the first artist to occupy the entire top ten of the Billboard Hot 100 with tracks from Midnights.\n\nAdditionally, Swift began re-recording her back catalog in November 2020 as a result of a publicized dispute with talent manager Scooter Braun and her former label Big Machine, regarding the acquisition of the masters of her back catalog. In April 2021, Swift released a re-recorded issue of her 2008 album Fearless, titled Fearless (Taylor\'s Version). It debuted at number one in the US. Swift continued releasing re-recorded versions of her back catalog in November, 2021 with the release of Red (Taylor\'s Version), a 30 track re-issue of her 2012 critical smash. The album debuted at #1 in the US, spawned the #1 hit All Too Well (10 Minute Version) (Taylor\'s Version) (From the Vault), and broke the record at the time for biggest first day for a female album on Spotify. Red (Taylor\'s Version) was a critical and commercial hit, and proved that Swift\'s ambitious, yet ongoing plan to re-record her first 6 albums was well worth it.\n\nAlong with the release of Red (Taylor\'s Version) came All Too Well: The Short Film (2021), Swift\'s filmmaking debut. The 15 minute romantic drama was based on the lyrical content from Swift\'s 2012 fan favorite “All Too Well” starring Sadie Sink and Dylan O\'Brien. It had a limited theatrical release in major cities, and Swift held special screenings of the film throughout 2022 at various film festivals. In December, 2022 Taylor announced that she would be making her feature directorial debut with Oscar-winning studio Searchlight Pictures.\n\nFollowing the release of Midnights, Swift would embark on her first tour in five years, The Eras Tour—a retrospective tour covering the entirety of her discography. During her ongoing tour, Swift would release her next two re-recorded albums, Speak Now (Taylor\'s Version) in July and 1989 (Taylor\'s Version) in October of 2023. The former of which would land Swift as the woman with the most number-one albums (12) in Billboard 200 history, surpassing Barbra Streisand. The latter was her sixth album to sell one million copies in a single week in the US, her largest album sales in a week span. “Is It Over Now? (Taylor\'s Version)”, the lead single for 1989 (Taylor\'s Version), would peak at number one on the Billboard Hot 100.\n\nAt the 66th annual GRAMMY Awards, Taylor Swift surprised viewers by announcing her eleventh studio album, THE TORTURED POETS DEPARTMENT. On April 19, 2024, the album was released globally, breaking records: it became the first ever to amass 1 billion Spotify streams in a week and sold 2.6 million units in its first week in the US. Swift dominated the charts, monopolizing the top 14 spots on the Billboard Hot 100 and securing the top 10 positions on Australia’s ARIA Singles Chart. The lead single, Fortnight, featuring Post Malone, quickly soared to the number-one position on the Hot 100. Additionally, just two hours after the album’s release, Swift surprised fans with a reissue titled THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY, which included 15 extra songs.\n\nSwift has released several songs for film soundtracks. She co-wrote two songs for the Hannah Montana: The Movie soundtrack— “You\'ll Always Find Your Way Back Home” and “Crazier”, and contributed two songs to the Valentine\'s Day soundtrack, including the single “Today Was a Fairytale”, which was her first number one on the Canadian Hot 100, and peaked at number two on the Billboard Hot 100. She also contributed two original songs to The Hunger Games soundtrack album: “Safe & Sound - from The Hunger Games Soundtrack”, co-written and recorded with The Civil Wars and T-Bone Burnett, and “Eyes Open”. “Safe & Sound” won the Grammy Award for Best Song Written for Visual Media and was nominated for the Golden Globe Award for Best Original Song. In 2013, Swift recorded “Sweeter than Fiction”, a song she wrote and produced with Jack Antonoff for the One Chance film soundtrack, which received a Best Original Song nomination at the 71st Golden Globe Awards. Swift and English singer Zayn Malik, mononymously known as Zayn, released a single together, “I Don\'t Wanna Live Forever”, for the soundtrack of the film Fifty Shades Darker (2017). She also recorded an original song called “Beautiful Ghosts”, which she wrote with Andrew Lloyd Webber for the Cats\'s soundtrack (2019). In 2020, Swift\'s documentary Miss Americana featured the song “Only the Young” which was written after the 2018 United States elections. In 2022, she released an original song titled “Carolina” for Where The Crawdads Sing (2022) inspired by the novel written by Delia Owens.\n\nWith sales of over 200 million records worldwide, Swift is a best-selling music artist. Her accolades include 14 Grammy Awards, including four Album of the Year wins, which makes Swift the artist with the most awards for that category in history, two Brit Awards (including a Global Icon award), an Emmy Award, 28 Guinness World Records, 32 American Music Awards (the most wins by an artist), and 23 Billboard Music Awards (the most wins by a woman). She ranked eighth on Billboard\'s Greatest of All Time Artists Chart (2019) and was listed on Rolling Stone\'s 100 Greatest Songwriters of All Time (2015). Swift has been included in various power rankings, such as Time\'s annual list of the 100 most influential people in the world (2010, 2015 and 2019) and Forbes Celebrity 100 (placing first in 2016 and 2019). She was named Woman of the Decade (2010s) by Billboard, Artist of the Decade (2010s) by the American Music Awards, and Person of the Year (2023) by Time Magazine. <a href="https://www.last.fm/music/Taylor+Swift">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

-Para la popularidad: listeners y playcount 

(listeners usarios unicosq han escuchaado el artista // playcounts numero total de reproducciones)

-para la biografia: bio ["summary"]

-para artistas similares: similar["artist"]

revisar la info que queremos realmente utilizar

ANALOGIA: 

Muchos listeners + mucho playcount = artista muy popular

Muchos listeners + poco playcount = mucha gente lo prueba pero no repite

Pocos listeners + mucho playcount = fans muy fieles


ratio = playcount / listeners ( RTA- cuantas veces escucha de media cada usuario)

In [33]:
print(datos.keys())    #confirmo laas claves que voy a necesitar para filtrar la info que quiero de
                        #cada artista. En este caso, me quedo con artist

dict_keys(['artist'])

In [34]:
print(datos["artist"].keys())      #reviso las claves dentro de artist y me quedo con las q necesito.name, stats, similar, tag bio.

dict_keys(['name', 'mbid', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [35]:
print(datos["artist"]["stats"].keys())   #reviso las claves dentro de stats, que es donde están los datos que quiero extraer.

dict_keys(['listeners', 'playcount'])

In [36]:
print(datos["artist"]["bio"].keys())        #reviso las claves dentro de bio, que es donde están los datos a extraer de la bio- me quedo con summary, que es el resumen.

dict_keys(['links', 'published', 'summary', 'content'])

In [37]:
print(datos["artist"]["tags"].keys())

dict_keys(['tag'])

In [38]:
artista = datos["artist"]       #

nombre = artista["name"]                        # extraigo el nombre del artista
listeners = artista["stats"]["listeners"]       # extraigo el número de oyentes del artista
playcount = artista["stats"]["playcount"]       # extraigo el número de reproducciones del artista
biografia = artista["bio"]["summary"]           # extraigo el resumen de la biografía del artista

similares = []          

for similar in artista["similar"]["artist"]:
    similares.append(similar["name"])

print(nombre)
print(listeners)
print(playcount)
print(biografia)
print(similares)

Taylor Swift
5941473
3677983140
Taylor Alison Swift is an American singer-songwriter. Her discography spans multiple genres, and her narrative songwriting, which is often inspired by her personal life, has received widespread media coverage and critical praise.

Swift rose to mainstream prominence with her sophomore studio album, Fearless (2008), a country pop record with crossover appeal. Aided by the top-five singles “Love Story” and “You Belong with Me”, Fearless was certified Diamond by the Recording Industry Recording Industry Association of America (RIAA). <a href="https://www.last.fm/music/Taylor+Swift">Read more on Last.fm</a>
['Sabrina Carpenter', 'Olivia Rodrigo', 'Gracie Abrams', 'Harry Styles', 'Chappell Roan']

pruebo código con masartistas

In [39]:
info_artistas = []

for nombre_artista in artistas:

    params = {
        "method": "artist.getInfo",
        "artist": nombre_artista,
        "api_key": api_key,
        "format": "json",
        "lang": "es",
        "autocorrect": 1                # para corregir nombrede artista q esté mal escrito y lo traiga bien aunque no lo tengo en la lista de artistas, pero por si acaso.
    }

    respuesta = requests.get(url, params=params)
    datos = respuesta.json()

    if "artist" not in datos:
        print(f"Artista no encontrado: {nombre_artista}")
        continue

    artista = datos["artist"]

    # similares
    similares = []
    for similar in artista["similar"]["artist"]:
        similares.append(similar["name"])

    # tags (añadimos esto ahora) -para ver estilo(pop), genero mujer, etc. - es una lista de etiquetas que los usuarios han asignado al artista en Last.fm.
    tags = []
    for tag in artista["tags"]["tag"]:
        tags.append(tag["name"])

    # biografía limpia
    bio_limpia = artista["bio"]["summary"].split("<a href=")[0].strip() # lo limpia para quedarnos solo con el resumen sin el enlace a la bio completa

    # guardo todo en un diccionario y lo añado a la lista
    info_artistas.append({
        "artista_buscado": nombre_artista,
        "nombre": artista["name"],
        "listeners": artista["stats"]["listeners"],
        "playcount": artista["stats"]["playcount"],
        "biografia": bio_limpia,
        "similares": similares,
        "tags": tags
    })

    time.sleep(0.3)

In [40]:
print(info_artistas)

[{'artista_buscado': 'Taylor Swift', 'nombre': 'Taylor Swift', 'listeners': '5941473', 'playcount': '3677983140', 'biografia': 'Taylor Alison Swift (Reading, Pennsylvania, 13 de diciembre de 1989) es una cantante y compositora de música country y pop estadounidense. Trabajaba con la compañía discográfica independiente Big Machine Records desde 2006 hasta 2018, año en el que se unio a Republic Records donde se encuentra hasta la actualidad. Taylor Swift hizo su aparición en las listas de country con su sencillo Tim McGraw.\n\nSu primer álbum Taylor Swift fue lanzado al mercado a finales de 2006, y ha sido catalogado desde entonces como 7X Multi-Platinum por el RIAA.', 'similares': ['Sabrina Carpenter', 'Olivia Rodrigo', 'Gracie Abrams', 'Harry Styles', 'Chappell Roan'], 'tags': ['country', 'pop', 'female vocalists', 'singer-songwriter', 'acoustic']}, {'artista_buscado': 'Drake', 'nombre': 'Drake', 'listeners': '6722037', 'playcount': '1166074902', 'biografia': 'Aubrey Drake Graham (24 de octubre de 1986), conocido como Drake, es un rapero, cantante y actor canadiense. Figura influyente de la música popular, se le atribuye la popularización de la sensibilidad R&B entre los artistas de hip hop. Reconocido por su papel de Jimmy Brooks en la serie dramática de la CTV Degrassi: The Next Generation (2001-2008), Drake comenzó su carrera discográfica en 2006 con el lanzamiento de su primera mixtape, Room for Improvement (2006).', 'similares': ['PARTYNEXTDOOR', 'DJ Khaled', 'Drake & Future', 'Tory Lanez', 'Lil Baby'], 'tags': ['Hip-Hop', 'rap', 'rnb', 'hip hop', 'Canadian']}, {'artista_buscado': 'Morgan Wallen', 'nombre': 'Morgan Wallen', 'listeners': '986913', 'playcount': '91544677', 'biografia': 'Morgan Wallen (nacido el 13 de mayo de 1993 en Sneedville, Tennessee ) es un artista de música country estadounidense. Él firmó con Big Loud Records y lanzó una obra extendida y un sencillo, "The Way I Talk". Su padre era predicador, y cuando era niño, Wallen tomó clases de piano y violín. Jugó al béisbol en la universidad, pero optó por buscar música en su lugar después de una lesión. En 2014, compitió en la temporada 6 de The Voice , pero fue eliminado.', 'similares': ['Bailey Zimmerman', 'Luke Combs', 'Tucker Wetmore', 'Riley Green', 'HARDY'], 'tags': ['country', 'country pop', 'contemporary country', 'the voice', 'bro-country']}, {'artista_buscado': 'Kendrick Lamar', 'nombre': 'Kendrick Lamar', 'listeners': '5099421', 'playcount': '1031948825', 'biografia': 'Kendrick Lamar Duckworth (17 Junio, 1987), es un rapero y cantautor americano nacido en Compton, California perteneciente a la firma Aftermath Entertainment. Consiguió llamar la atención después del lanzamiento en 2010 de su mixtape Overly Dedicated. En 2011, su album Section.80, lanzado exclusivamente a través de iTunes, se clasificó al instante como uno de los top lanzamientos digitales del año. Lamar ha acumulado un gran número de seguidores en internet y actualmente es miembro del grupo de Hip Hop Black Hippy', 'similares': ['Baby Keem', 'JID', 'Jay Rock', 'Black Hippy', 'Tyler, The Creator'], 'tags': ['Hip-Hop', 'rap', 'west coast', 'hip hop', 'compton']}, {'artista_buscado': 'The Weeknd', 'nombre': 'The Weeknd', 'listeners': '5320117', 'playcount': '1123613252', 'biografia': 'Abel Makkonen Tesfaye, mejor conocido por su nombre artístico The Weeknd (Toronto, Canadá, 16 de febrero de 1990), es un cantante, compositor y productor canadiense.\n\nA finales de 2010, Tesfaye subió anónimamente varias canciones a YouTube bajo el nombre "The Weeknd". Lanzó tres mixtapes de nueve pistas a lo largo de 2011: House of Balloons, Thursday and Echoes of Silence, que eran muy aclamadas. Al año siguiente, lanzo su álbum recopilatorio', 'similares': ['Tory Lanez', 'Drake', 'Black Atlass', 'PARTYNEXTDOOR', 'Don Toliver'], 'tags': ['rnb', 'electronic', 'dubstep', 'Canadian', 'prog-rnb']}, {'artista_buscado': 'SZA', 'nombre': 'SZA', 'listeners': '3497700', 'playcount': '588174194', 'biografia': 'Solana Rowe (nacida el 8 de Noviembre de 1989) es mejor conocida como SZA. El proyecto de esta cantante y compositora estadounidense es significativamente distinto y tras lanzar su EP debut de manera independiente (See.SZA.Run) se notaron las influencias de Rowe (neo soul, alternative R&B y el PBR&B) que la llevaron a trabajar con artistas como Chance the Rapper y Kendrick Lamar.\n\nEn su corta carrera, SZA (influenciada por Björk, Red Hot Chilli Peppers y Billie Holiday) ha cultivado una carrera de éxito crítico por sus sonidos y voz y que', 'similares': ['Summer Walker', 'Doja Cat', 'Kali Uchis', 'Doechii', 'Jhené Aiko'], 'tags': ['rnb', 'soul', 'alternative rnb', 'electronic', 'Neo-Soul']}, {'artista_buscado': 'Zach Bryan', 'nombre': 'Zach Bryan', 'listeners': '1205931', 'playcount': '136678363', 'biografia': 'Zachary Lane Bryan es un cantautor estadounidense. Su álbum debut, American Heartbreak, alcanzó la posición número cinco en el Billboard 200', 'similares': ['Sam Barber', 'Dylan Gossett', 'Charles Wesley Godwin', 'Wyatt Flores', 'Turnpike Troubadours'], 'tags': ['country', 'singer-songwriter', 'americana', 'Alt-country', 'country rock']}, {'artista_buscado': 'Tyler The Creator', 'nombre': 'Tyler, The Creator', 'listeners': '4333565', 'playcount': '1053111426', 'biografia': 'Tyler Okonma (6 de marzo de 1991), más conocido por su nombre artístico de Tyler, The Creator, es un rapero y productor musical de Los Angeles, California. Tyler fue el creador y líder del colectivo de hip hop alternativo OFWGKTA. Ha rapeado y producido canciones para casi todos los lanzamientos de OFWGKTA. Cuenta con 6 trabajos de larga duración. Considerado como uno de los mejores raperos de la actualidad.', 'similares': ['OFWGKTA', 'Kendrick Lamar', 'Domo Genesis', 'Childish Gambino', 'MellowHype'], 'tags': ['Hip-Hop', 'rap', 'ofwgkta', 'underground hip-hop', 'swag']}, {'artista_buscado': 'Billie Eilish', 'nombre': 'Billie Eilish', 'listeners': '4232010', 'playcount': '836742492', 'biografia': "Billie Eilish Pirate Baird O'Connell\u200b (Los Ángeles, California; 18 de diciembre de 2001\u200b) conocida solo como Billie Eilish, es una cantante y compositora estadounidense. Su primer sencillo, «Ocean Eyes», producido por su hermano, y ella ha acumulado más de 1 millón de streams en YouTube desde febrero de 2018. Su primer EP, «Don't Smile at Me» fue lanzado en agosto de 2017. Tras el éxito del EP, un mes después, en octubre de 2017, Apple nombró a Eilish como su más reciente artista UPNEXT de Apple Music.", 'similares': ['FINNEAS', 'Olivia Rodrigo', 'Melanie Martinez', 'Lana Del Rey', 'Ariana Grande'], 'tags': ['pop', 'indie pop', 'electropop', 'art pop', 'alternative']}, {'artista_buscado': 'Ariana Grande', 'nombre': 'Ariana Grande', 'listeners': '4484810', 'playcount': '1112472000', 'biografia': 'Ariana Grande Butera (Boca Ratón, 26 de junio de 1993) es una actriz, cantante y compositora estadounidense. Debutó como actriz en 2008 con el papel de Charlotte en el musical 13 de Broadway.\nDesde 2010 al presente, Grande interpreta a Cat Valentine en las series de Nickelodeon, Victorious y Sam & Cat, el primero lo co-protagonizó y el segundo es una serie derivada que lo protagoniza junto a Jennette McCurdy. En marzo de 2013, Grande alcanzó éxito', 'similares': ['Jessie J, Ariana Grande & Nicki Minaj', 'Madison Beer', 'Cynthia Erivo', 'Sabrina Carpenter', 'Doja Cat'], 'tags': ['pop', 'rnb', 'female vocalists', 'Ariana Grande', 'american']}, {'artista_buscado': 'Bad Bunny', 'nombre': 'Bad Bunny', 'listeners': '2583506', 'playcount': '407351101', 'biografia': 'Benito Antonio Martínez Ocasio, mejor conocido como Bad Bunny, es un rapero y compositor puertorriqueño de trap, rap y hip-hop en español. Nació el 10 de marzo de 1994 en San Juan, Puerto Rico. Se ha ganado un nombre por su estilo inigualable a la hora de escribir rimas que de inmediato llaman la atención y por explorar distintos géneros musicales sin limitarse. Ambas cualidades no han afectado su popularidad mundial. Es tanto su popularidad', 'similares': ['JHAYCO', 'Rauw Alejandro', 'Tainy', 'Mora', 'Trio Vegabajeño'], 'tags': ['Reggaeton', 'trap', 'latin', 'puerto rico', 'trap latino']}, {'artista_buscado': 'Karol G', 'nombre': 'KAROL G', 'listeners': '1446042', 'playcount': '75934691', 'biografia': 'Carolina Giraldo Navarro (Medellín, Colombia, 14 de febrero de 1991), mejor conocida como Karol G es una cantante colombiana de reggaeton, pop y R&B.\n\nDurante su infancia participó en el reality Factor Xs, pero fue hasta el año 2010 cuando empezó a ser corista de Reykon, donde empezó a experimentar en el ámbito musical. En el año 2012 Karol G debutó con su éxito "301" junto a Reykon, el cual llegó a ser número uno en muchos canales de televisión y estaciones de radio.', 'similares': ['Natti Natasha', 'J Balvin', 'Maluma', 'Becky G', 'Maria Becerra'], 'tags': ['Reggaeton', 'pop', 'latin pop', 'latin', 'Colombia']}, {'artista_buscado': 'Myke Towers', 'nombre': 'Myke Towers', 'listeners': '659832', 'playcount': '28489794', 'biografia': 'Michael Torres (Río Piedras, Puerto Rico, 15 de enero de 1994), conocido por su nombre artístico Myke Towers, es un rapero, cantante y compositor puertorriqueño.\n\nMyke Towers nació el 15 de enero de 1994 en Puerto Rico y desde muy pequeño demostró tener interés por la música, es así como en el año 2012 empieza a publicar sus primeros sencillos en la plataforma digital SoundCloud, donde logró tener aceptación por el público oyente de la música urbana', 'similares': ['JHAYCO', 'Dei V', 'Bryant Myers', 'Mora', 'Anuel AA'], 'tags': ['Reggaeton', 'puerto rico', 'latin', 'trap', 'rap']}, {'artista_buscado': 'Quevedo', 'nombre': 'Quevedo', 'listeners': '386264', 'playcount': '23722085', 'biografia': 'Pedro Domínguez Quevedo, más conocido por su nombre artístico: “Quevedo”, nació en Madrid el 7 de diciembre del 2001. Con tan solo un año se va a vivir a Brasil hasta los 5 años. Después, se asienta en Gran Canaria. Por ello, su trabajo se ve influenciado por la cultura musical de la isla, el Hip-Hop y los ritmos latinos principalmente.\n\nAprovechando que este año es uno de los artistas más aclamados de la industria, ya que entra en el top 3 de los artistas más oídos de España', 'similares': ['Myke Towers', 'JHAYCO', 'Gonzy', 'Omar Courtz', 'Feid'], 'tags': ['Reggaeton', 'rap', 'spanish', 'Hip-Hop', 'spain']}, {'artista_buscado': 'Aitana', 'nombre': 'Aitana', 'listeners': '243729', 'playcount': '14829901', 'biografia': 'Aitana Ocaña Morales, conocida simplemente como Aitana, es una cantante española. Se dio a conocer en el año 2017, cuando formó parte de la novena temporada de Operación Triunfo.', 'similares': ['Belén Aguilera', 'Ana Mena', 'Lola Indigo', 'Amaia', 'Vicco'], 'tags': ['spanish', 'pop', 'spain', 'female vocalists', 'pop rock']}, {'artista_buscado': 'Rosalía', 'nombre': 'ROSALÍA', 'listeners': '1868077', 'playcount': '203852560', 'biografia': 'Rosalía Vila Tobella, conocida mundialmente como ROSALÍA, es una cantante y compositora española.\n\n Comienza sus estudios musicales a los 10 años, hasta finalizar el grado superior en la ESMUC (Escola Superior de Música de Catalunya), en la especialización de flamenco. Al terminar, comienza a trabajar en distintas áreas de la música, participando en prestigiosos eventos dentro y fuera de España. En febrero de 2017 finalmente publicaría su primer álbum', 'similares': ['Judeline', 'Lorde', 'Robyn', 'Bad Gyal', 'NATHY PELUSO'], 'tags': ['pop', 'Flamenco', 'spanish', 'art pop', 'Flamenco Nuevo']}, {'artista_buscado': 'Morad', 'nombre': 'Morad', 'listeners': '207124', 'playcount': '9314374', 'biografia': 'Morad es el nombre artístico de un rapero catalán de ascendencia marroquí que nació el 5 de marzo de 1999 en L’Hospitalet de Llobregat y que hace música del estilo drill con temática urbana y joven. El artista ha visibilizado a la calle, a aquellos que no salen en los noticieros pero que protagonizan historias duras y relatos de supervivencia para conseguir llevar comida a casa en unas circunstancias difíciles.', 'similares': ['Baby Gang', 'Rvfv', 'Capo Plaza', 'Sfera Ebbasta', 'Artie 5ive'], 'tags': ['rap', 'Hip-Hop', 'hip hop', 'french', 'All']}, {'artista_buscado': 'Melendi', 'nombre': 'Melendi', 'listeners': '316017', 'playcount': '8232484', 'biografia': 'Ramón Melendi nace en Oviedo en 1979. Aunque va para futbolista –incluso llega a jugar en las categorías infantiles del equipo de su ciudad-, durante su adolescencia descubre los dudosos placeres de la vida nocturna y despreocupada. En todo caso, hace cada vez más patente su interés por la música y a principios de 2001 forma la banda "El Bosque de Sherwood", proyecto que obtiene nula repercusión mediática y comercial por lo que Ramón decide probar suerte como solista.', 'similares': ['Estopa', 'El Canto del Loco', 'Maldita Nerea', 'Pereza', 'El Arrebato'], 'tags': ['spanish', 'pop', 'Flamenco', 'new flamenco', 'Espanol']}, {'artista_buscado': 'Enrique Iglesias', 'nombre': 'Enrique Iglesias', 'listeners': '2712737', 'playcount': '54246937', 'biografia': 'Enrique Miguel Iglesias Preysler (n. 8 de mayo de 1975) es un cantante español. Nacido en Madrid, es hijo del destacado cantante español Julio Iglesias y la también destacada modelo filipina Isabel Preysler, sus hermanos son Chabeli Iglesias y Julio Iglesias Jr.. Tiene además otros siete hermanos fruto de otros matrimonios de sus padres.\n\nDespués del secuestro de su abuelo en España, Iglesias se mudó a Miami en 1985 a los 10 años de edad.', 'similares': ['Ricky Martin', 'Chayanne', 'Luis Fonsi', 'Alejandro Sanz', 'Franco De Vita'], 'tags': ['pop', 'latin', 'spanish', 'dance', 'latin pop']}, {'artista_buscado': 'Juanes', 'nombre': 'Juanes', 'listeners': '1209521', 'playcount': '21965331', 'biografia': 'Juan Esteban Aristizábal nació el 9 de agosto de 1972 en Medellín, Antioquia, Colombia; vivió su niñez en un pueblo de Antioquia llamado Carolina del Príncipe (donde se levantó una estatua el 12 de octubre de 2007 en su honor), en el seno de una familia influenciada por la música. A su corta edad su padre y sus cinco hermanos le enseñan a tocar la guitarra, instrumento que lo ha acompañado toda su vida musical.\n\nComenzó su carrera artística', 'similares': ['Bacilos', 'Carlos Vives', 'Maná', 'Chayanne', 'Cabas'], 'tags': ['latin', 'pop', 'spanish', 'rock', 'latino']}, {'artista_buscado': 'Duki', 'nombre': 'Duki', 'listeners': '298201', 'playcount': '43048568', 'biografia': 'Mauro Ezequiel Lombardo (Almagro, Argentina; 24 de junio de 1996), conocido artísticamente como Duki, es un cantante, trapero y freestyler argentino.', 'similares': ['Ysy A', 'Khea', 'LIT killah', 'Neo Pistea', 'Bhavi'], 'tags': ['trap', 'latin', 'argentina', 'Latin Trap', 'Hip Hop Latino']}, {'artista_buscado': 'María Becerra', 'nombre': 'María Becerra', 'listeners': '509', 'playcount': '7097', 'biografia': '', 'similares': ['Maria Becerra', 'Natti Natasha', 'Sofía Reyes', 'Myke Towers', 'Cazzu'], 'tags': ['Reggaeton', 'trap', 'argentina']}, {'artista_buscado': 'Tini Stoessel', 'nombre': 'Tini Stoessel', 'listeners': '49', 'playcount': '486', 'biografia': '', 'similares': ['Rusherking, Maria Becerra', 'Laid Back Avenue', 'La Konga', 'Emilia & Duki', 'Axwell Ʌ Ingrosso'], 'tags': []}, {'artista_buscado': 'Nicki Nicole', 'nombre': 'Nicki Nicole', 'listeners': '257172', 'playcount': '10846174', 'biografia': 'Nicki Nicole es una cantante y compositora nacida el 25 de agosto de 2000 en Rosario, Argentina. Su nombre completo es Nicole Denise Cucco, y es considerada una de las máximas exponentes del trap y el rap en Latinoamérica. Creció en el barrio Echesortu y, desde pequeña, mostró inclinación por la música, participando en eventos escolares y familiares.\n\nDebutó en 2019 con su sencillo "Wapo Traketero", que rápidamente se volvió viral en YouTube.', 'similares': ['Maria Becerra', 'Cazzu', 'Emilia', 'Wos', 'Paulo Londra'], 'tags': ['pop', 'argentina', 'rnb', 'indie pop', 'latinoamerica']}, {'artista_buscado': 'Cazzu', 'nombre': 'Cazzu', 'listeners': '207599', 'playcount': '5879351', 'biografia': 'Julieta Emilia Cazzucheli, conocida por su nombre artístico Cazzu, es una cantante y compositora argentina de trap.\u200b\u200b Es considerada una de las grandes exponentes del Trap latino, con una carrera en pleno ascenso. Los medios nacionales y otros artistas del género y colegas se refieren a ella como "La Jefa".', 'similares': ['Maria Becerra', 'Nicki Nicole', 'Lali', 'La Joaqui', 'Emilia'], 'tags': ['pop', 'Hip-Hop', 'rnb', 'trap', 'trap latino']}, {'artista_buscado': 'Lali', 'nombre': 'Lali', 'listeners': '133027', 'playcount': '9000043', 'biografia': 'Lali es una cantautora y actriz argentina. Desde pequeña ha incursionado el mundo artístico a través de distintas producciones exitosas en televisión, cine y teatro.\nSus canciones la han ubicado como una de las voces pop en español más escuchadas a nivel mundial.\nEn 2013 lanzó su álbum debut "A Bailar" de manera independiente, con el que se transformó en una precursora del pop femenino en Sur América.\nEn 2016 lanza "SOY" su segundo álbum', 'similares': ['Angela Torres', 'Maria Becerra', 'Miranda!', 'Cazzu', 'Floricienta'], 'tags': ['argentina', 'pop', 'dance', 'latin', 'argentine']}, {'artista_buscado': 'Paulo Londra', 'nombre': 'Paulo Londra', 'listeners': '387196', 'playcount': '16770023', 'biografia': 'Paulo Ezequiel Londra Farías, más conocido como Paulo Londra (Córdoba, Argentina; 12 de abril de 1998) es un cantante argentino de trap.\nInició su carrera musical en enero de 2017 cuando lanzó su primer sencillo, Relax, que luego de unos meses estaba posicionado como un hit argentino del año. Desde entonces empezó a componer y continuó lanzando canciones. A pesar de que sus inicios son similares a otros exponentes urbanos, Londra, a diferencia de otros artistas, evita tocar temas como violencia, insultos o drogas en sus canciones.', 'similares': ['LIT killah', 'Duki', 'Trueno', 'Khea', 'Wos'], 'tags': ['argentina', 'trap', 'trap latino', 'white rapper', 'trap argentino']}, {'artista_buscado': 'Shakira', 'nombre': 'Shakira', 'listeners': '4881220', 'playcount': '180195664', 'biografia': 'Shakira Isabel Mebarak Ripoll, es una cantante y compositora de pop-rock en español e inglés, nació el 2 de Febrero de 1977 en Barranquilla, Colombia. En árabe, Shakira (شاكرة) significa "llena de gracia". Ha sido ganadora en dos ocasiones del Premio Grammy y ocho veces ganadora del Grammy Latino.La artista ha vendido más de 135 millones de records según informa NBC.\n\nSe trata de una de las cantantes del ámbito musical latino con más éxito internacional.', 'similares': ['Paulina Rubio', 'Belinda', 'Thalía', 'KAROL G', 'Julieta Venegas'], 'tags': ['pop', 'latin', 'female vocalists', 'spanish', 'rock']}, {'artista_buscado': 'Bizarrap', 'nombre': 'Bizarrap', 'listeners': '926528', 'playcount': '46018935', 'biografia': 'Gonzalo Julián Conde mejor conocido artísticamente como Bizarrap es un productor discográfico argentino, nacido el 29 de agosto de 1998 en Ramos Mejía, Argentina. Se especializa en géneros como trap, latin trap y rap.', 'similares': ['Duki', 'Milo j', 'LIT killah', 'Khea', 'Bhavi'], 'tags': ['argentina', 'rap', 'trap', 'latin', 'pinga']}, {'artista_buscado': 'Emilia', 'nombre': 'Emilia', 'listeners': '501626', 'playcount': '18933502', 'biografia': 'Emilia Mernes (29 de Octubre de 1996, Nogoyá, Entre Ríos, Argentina) es una cantante de pop urbano argentina. Perteneció al dúo cumbia/pop Rombai entre 2016 y 2018. Actualmente solista bajo el nombre de “Emilia”.', 'similares': ['Maria Becerra', 'Tini', 'Nicki Nicole', 'Lali', 'Cazzu'], 'tags': ['pop', 'female vocalists', 'swedish', '90s', 'argentina']}]

In [41]:
info_artistas

[{'artista_buscado': 'Taylor Swift',
  'nombre': 'Taylor Swift',
  'listeners': '5941473',
  'playcount': '3677983140',
  'biografia': 'Taylor Alison Swift (Reading, Pennsylvania, 13 de diciembre de 1989) es una cantante y compositora de música country y pop estadounidense. Trabajaba con la compañía discográfica independiente Big Machine Records desde 2006 hasta 2018, año en el que se unio a Republic Records donde se encuentra hasta la actualidad. Taylor Swift hizo su aparición en las listas de country con su sencillo Tim McGraw.\n\nSu primer álbum Taylor Swift fue lanzado al mercado a finales de 2006, y ha sido catalogado desde entonces como 7X Multi-Platinum por el RIAA.',
  'similares': ['Sabrina Carpenter',
   'Olivia Rodrigo',
   'Gracie Abrams',
   'Harry Styles',
   'Chappell Roan'],
  'tags': ['country',
   'pop',
   'female vocalists',
   'singer-songwriter',
   'acoustic']},
 {'artista_buscado': 'Drake',
  'nombre': 'Drake',
  'listeners': '6722037',
  'playcount': '1166074902',
  'biografia': 'Aubrey Drake Graham (24 de octubre de 1986), conocido como Drake, es un rapero, cantante y actor canadiense. Figura influyente de la música popular, se le atribuye la popularización de la sensibilidad R&B entre los artistas de hip hop. Reconocido por su papel de Jimmy Brooks en la serie dramática de la CTV Degrassi: The Next Generation (2001-2008), Drake comenzó su carrera discográfica en 2006 con el lanzamiento de su primera mixtape, Room for Improvement (2006).',
  'similares': ['PARTYNEXTDOOR',
   'DJ Khaled',
   'Drake & Future',
   'Tory Lanez',
   'Lil Baby'],
  'tags': ['Hip-Hop', 'rap', 'rnb', 'hip hop', 'Canadian']},
 {'artista_buscado': 'Morgan Wallen',
  'nombre': 'Morgan Wallen',
  'listeners': '986913',
  'playcount': '91544677',
  'biografia': 'Morgan Wallen (nacido el 13 de mayo de 1993 en Sneedville, Tennessee ) es un artista de música country estadounidense. Él firmó con Big Loud Records y lanzó una obra extendida y un sencillo, "The Way I Talk". Su padre era predicador, y cuando era niño, Wallen tomó clases de piano y violín. Jugó al béisbol en la universidad, pero optó por buscar música en su lugar después de una lesión. En 2014, compitió en la temporada 6 de The Voice , pero fue eliminado.',
  'similares': ['Bailey Zimmerman',
   'Luke Combs',
   'Tucker Wetmore',
   'Riley Green',
   'HARDY'],
  'tags': ['country',
   'country pop',
   'contemporary country',
   'the voice',
   'bro-country']},
 {'artista_buscado': 'Kendrick Lamar',
  'nombre': 'Kendrick Lamar',
  'listeners': '5099421',
  'playcount': '1031948825',
  'biografia': 'Kendrick Lamar Duckworth (17 Junio, 1987), es un rapero y cantautor americano nacido en Compton, California perteneciente a la firma Aftermath Entertainment. Consiguió llamar la atención después del lanzamiento en 2010 de su mixtape Overly Dedicated. En 2011, su album Section.80, lanzado exclusivamente a través de iTunes, se clasificó al instante como uno de los top lanzamientos digitales del año. Lamar ha acumulado un gran número de seguidores en internet y actualmente es miembro del grupo de Hip Hop Black Hippy',
  'similares': ['Baby Keem',
   'JID',
   'Jay Rock',
   'Black Hippy',
   'Tyler, The Creator'],
  'tags': ['Hip-Hop', 'rap', 'west coast', 'hip hop', 'compton']},
 {'artista_buscado': 'The Weeknd',
  'nombre': 'The Weeknd',
  'listeners': '5320117',
  'playcount': '1123613252',
  'biografia': 'Abel Makkonen Tesfaye, mejor conocido por su nombre artístico The Weeknd (Toronto, Canadá, 16 de febrero de 1990), es un cantante, compositor y productor canadiense.\n\nA finales de 2010, Tesfaye subió anónimamente varias canciones a YouTube bajo el nombre "The Weeknd". Lanzó tres mixtapes de nueve pistas a lo largo de 2011: House of Balloons, Thursday and Echoes of Silence, que eran muy aclamadas. Al año siguiente, lanzo su álbum recopilatorio',
  'similares': ['Tory Lanez',
   'Drake',
   'Black Atlass',
   'PARTYNEXTDOOR',
   'Don Toliver'],
  'tags': ['rnb', 'electronic', 'dubstep', 'Canadian', 'prog-rnb']},
 {'artista_buscado': 'SZA',
  'nombre': 'SZA',
  'listeners': '3497700',
  'playcount': '588174194',
  'biografia': 'Solana Rowe (nacida el 8 de Noviembre de 1989) es mejor conocida como SZA. El proyecto de esta cantante y compositora estadounidense es significativamente distinto y tras lanzar su EP debut de manera independiente (See.SZA.Run) se notaron las influencias de Rowe (neo soul, alternative R&B y el PBR&B) que la llevaron a trabajar con artistas como Chance the Rapper y Kendrick Lamar.\n\nEn su corta carrera, SZA (influenciada por Björk, Red Hot Chilli Peppers y Billie Holiday) ha cultivado una carrera de éxito crítico por sus sonidos y voz y que',
  'similares': ['Summer Walker',
   'Doja Cat',
   'Kali Uchis',
   'Doechii',
   'Jhené Aiko'],
  'tags': ['rnb', 'soul', 'alternative rnb', 'electronic', 'Neo-Soul']},
 {'artista_buscado': 'Zach Bryan',
  'nombre': 'Zach Bryan',
  'listeners': '1205931',
  'playcount': '136678363',
  'biografia': 'Zachary Lane Bryan es un cantautor estadounidense. Su álbum debut, American Heartbreak, alcanzó la posición número cinco en el Billboard 200',
  'similares': ['Sam Barber',
   'Dylan Gossett',
   'Charles Wesley Godwin',
   'Wyatt Flores',
   'Turnpike Troubadours'],
  'tags': ['country',
   'singer-songwriter',
   'americana',
   'Alt-country',
   'country rock']},
 {'artista_buscado': 'Tyler The Creator',
  'nombre': 'Tyler, The Creator',
  'listeners': '4333565',
  'playcount': '1053111426',
  'biografia': 'Tyler Okonma (6 de marzo de 1991), más conocido por su nombre artístico de Tyler, The Creator, es un rapero y productor musical de Los Angeles, California. Tyler fue el creador y líder del colectivo de hip hop alternativo OFWGKTA. Ha rapeado y producido canciones para casi todos los lanzamientos de OFWGKTA. Cuenta con 6 trabajos de larga duración. Considerado como uno de los mejores raperos de la actualidad.',
  'similares': ['OFWGKTA',
   'Kendrick Lamar',
   'Domo Genesis',
   'Childish Gambino',
   'MellowHype'],
  'tags': ['Hip-Hop', 'rap', 'ofwgkta', 'underground hip-hop', 'swag']},
 {'artista_buscado': 'Billie Eilish',
  'nombre': 'Billie Eilish',
  'listeners': '4232010',
  'playcount': '836742492',
  'biografia': "Billie Eilish Pirate Baird O'Connell\u200b (Los Ángeles, California; 18 de diciembre de 2001\u200b) conocida solo como Billie Eilish, es una cantante y compositora estadounidense. Su primer sencillo, «Ocean Eyes», producido por su hermano, y ella ha acumulado más de 1 millón de streams en YouTube desde febrero de 2018. Su primer EP, «Don't Smile at Me» fue lanzado en agosto de 2017. Tras el éxito del EP, un mes después, en octubre de 2017, Apple nombró a Eilish como su más reciente artista UPNEXT de Apple Music.",
  'similares': ['FINNEAS',
   'Olivia Rodrigo',
   'Melanie Martinez',
   'Lana Del Rey',
   'Ariana Grande'],
  'tags': ['pop', 'indie pop', 'electropop', 'art pop', 'alternative']},
 {'artista_buscado': 'Ariana Grande',
  'nombre': 'Ariana Grande',
  'listeners': '4484810',
  'playcount': '1112472000',
  'biografia': 'Ariana Grande Butera (Boca Ratón, 26 de junio de 1993) es una actriz, cantante y compositora estadounidense. Debutó como actriz en 2008 con el papel de Charlotte en el musical 13 de Broadway.\nDesde 2010 al presente, Grande interpreta a Cat Valentine en las series de Nickelodeon, Victorious y Sam & Cat, el primero lo co-protagonizó y el segundo es una serie derivada que lo protagoniza junto a Jennette McCurdy. En marzo de 2013, Grande alcanzó éxito',
  'similares': ['Jessie J, Ariana Grande & Nicki Minaj',
   'Madison Beer',
   'Cynthia Erivo',
   'Sabrina Carpenter',
   'Doja Cat'],
  'tags': ['pop', 'rnb', 'female vocalists', 'Ariana Grande', 'american']},
 {'artista_buscado': 'Bad Bunny',
  'nombre': 'Bad Bunny',
  'listeners': '2583506',
  'playcount': '407351101',
  'biografia': 'Benito Antonio Martínez Ocasio, mejor conocido como Bad Bunny, es un rapero y compositor puertorriqueño de trap, rap y hip-hop en español. Nació el 10 de marzo de 1994 en San Juan, Puerto Rico. Se ha ganado un nombre por su estilo inigualable a la hora de escribir rimas que de inmediato llaman la atención y por explorar distintos géneros musicales sin limitarse. Ambas cualidades no han afectado su popularidad mundial. Es tanto su popularidad',
  'similares': ['JHAYCO',
   'Rauw Alejandro',
   'Tainy',
   'Mora',
   'Trio Vegabajeño'],
  'tags': ['Reggaeton', 'trap', 'latin', 'puerto rico', 'trap latino']},
 {'artista_buscado': 'Karol G',
  'nombre': 'KAROL G',
  'listeners': '1446042',
  'playcount': '75934691',
  'biografia': 'Carolina Giraldo Navarro (Medellín, Colombia, 14 de febrero de 1991), mejor conocida como Karol G es una cantante colombiana de reggaeton, pop y R&B.\n\nDurante su infancia participó en el reality Factor Xs, pero fue hasta el año 2010 cuando empezó a ser corista de Reykon, donde empezó a experimentar en el ámbito musical. En el año 2012 Karol G debutó con su éxito "301" junto a Reykon, el cual llegó a ser número uno en muchos canales de televisión y estaciones de radio.',
  'similares': ['Natti Natasha',
   'J Balvin',
   'Maluma',
   'Becky G',
   'Maria Becerra'],
  'tags': ['Reggaeton', 'pop', 'latin pop', 'latin', 'Colombia']},
 {'artista_buscado': 'Myke Towers',
  'nombre': 'Myke Towers',
  'listeners': '659832',
  'playcount': '28489794',
  'biografia': 'Michael Torres (Río Piedras, Puerto Rico, 15 de enero de 1994), conocido por su nombre artístico Myke Towers, es un rapero, cantante y compositor puertorriqueño.\n\nMyke Towers nació el 15 de enero de 1994 en Puerto Rico y desde muy pequeño demostró tener interés por la música, es así como en el año 2012 empieza a publicar sus primeros sencillos en la plataforma digital SoundCloud, donde logró tener aceptación por el público oyente de la música urbana',
  'similares': ['JHAYCO', 'Dei V', 'Bryant Myers', 'Mora', 'Anuel AA'],
  'tags': ['Reggaeton', 'puerto rico', 'latin', 'trap', 'rap']},
 {'artista_buscado': 'Quevedo',
  'nombre': 'Quevedo',
  'listeners': '386264',
  'playcount': '23722085',
  'biografia': 'Pedro Domínguez Quevedo, más conocido por su nombre artístico: “Quevedo”, nació en Madrid el 7 de diciembre del 2001. Con tan solo un año se va a vivir a Brasil hasta los 5 años. Después, se asienta en Gran Canaria. Por ello, su trabajo se ve influenciado por la cultura musical de la isla, el Hip-Hop y los ritmos latinos principalmente.\n\nAprovechando que este año es uno de los artistas más aclamados de la industria, ya que entra en el top 3 de los artistas más oídos de España',
  'similares': ['Myke Towers', 'JHAYCO', 'Gonzy', 'Omar Courtz', 'Feid'],
  'tags': ['Reggaeton', 'rap', 'spanish', 'Hip-Hop', 'spain']},
 {'artista_buscado': 'Aitana',
  'nombre': 'Aitana',
  'listeners': '243729',
  'playcount': '14829901',
  'biografia': 'Aitana Ocaña Morales, conocida simplemente como Aitana, es una cantante española. Se dio a conocer en el año 2017, cuando formó parte de la novena temporada de Operación Triunfo.',
  'similares': ['Belén Aguilera', 'Ana Mena', 'Lola Indigo', 'Amaia', 'Vicco'],
  'tags': ['spanish', 'pop', 'spain', 'female vocalists', 'pop rock']},
 {'artista_buscado': 'Rosalía',
  'nombre': 'ROSALÍA',
  'listeners': '1868077',
  'playcount': '203852560',
  'biografia': 'Rosalía Vila Tobella, conocida mundialmente como ROSALÍA, es una cantante y compositora española.\n\n Comienza sus estudios musicales a los 10 años, hasta finalizar el grado superior en la ESMUC (Escola Superior de Música de Catalunya), en la especialización de flamenco. Al terminar, comienza a trabajar en distintas áreas de la música, participando en prestigiosos eventos dentro y fuera de España. En febrero de 2017 finalmente publicaría su primer álbum',
  'similares': ['Judeline', 'Lorde', 'Robyn', 'Bad Gyal', 'NATHY PELUSO'],
  'tags': ['pop', 'Flamenco', 'spanish', 'art pop', 'Flamenco Nuevo']},
 {'artista_buscado': 'Morad',
  'nombre': 'Morad',
  'listeners': '207124',
  'playcount': '9314374',
  'biografia': 'Morad es el nombre artístico de un rapero catalán de ascendencia marroquí que nació el 5 de marzo de 1999 en L’Hospitalet de Llobregat y que hace música del estilo drill con temática urbana y joven. El artista ha visibilizado a la calle, a aquellos que no salen en los noticieros pero que protagonizan historias duras y relatos de supervivencia para conseguir llevar comida a casa en unas circunstancias difíciles.',
  'similares': ['Baby Gang',
   'Rvfv',
   'Capo Plaza',
   'Sfera Ebbasta',
   'Artie 5ive'],
  'tags': ['rap', 'Hip-Hop', 'hip hop', 'french', 'All']},
 {'artista_buscado': 'Melendi',
  'nombre': 'Melendi',
  'listeners': '316017',
  'playcount': '8232484',
  'biografia': 'Ramón Melendi nace en Oviedo en 1979. Aunque va para futbolista –incluso llega a jugar en las categorías infantiles del equipo de su ciudad-, durante su adolescencia descubre los dudosos placeres de la vida nocturna y despreocupada. En todo caso, hace cada vez más patente su interés por la música y a principios de 2001 forma la banda "El Bosque de Sherwood", proyecto que obtiene nula repercusión mediática y comercial por lo que Ramón decide probar suerte como solista.',
  'similares': ['Estopa',
   'El Canto del Loco',
   'Maldita Nerea',
   'Pereza',
   'El Arrebato'],
  'tags': ['spanish', 'pop', 'Flamenco', 'new flamenco', 'Espanol']},
 {'artista_buscado': 'Enrique Iglesias',
  'nombre': 'Enrique Iglesias',
  'listeners': '2712737',
  'playcount': '54246937',
  'biografia': 'Enrique Miguel Iglesias Preysler (n. 8 de mayo de 1975) es un cantante español. Nacido en Madrid, es hijo del destacado cantante español Julio Iglesias y la también destacada modelo filipina Isabel Preysler, sus hermanos son Chabeli Iglesias y Julio Iglesias Jr.. Tiene además otros siete hermanos fruto de otros matrimonios de sus padres.\n\nDespués del secuestro de su abuelo en España, Iglesias se mudó a Miami en 1985 a los 10 años de edad.',
  'similares': ['Ricky Martin',
   'Chayanne',
   'Luis Fonsi',
   'Alejandro Sanz',
   'Franco De Vita'],
  'tags': ['pop', 'latin', 'spanish', 'dance', 'latin pop']},
 {'artista_buscado': 'Juanes',
  'nombre': 'Juanes',
  'listeners': '1209521',
  'playcount': '21965331',
  'biografia': 'Juan Esteban Aristizábal nació el 9 de agosto de 1972 en Medellín, Antioquia, Colombia; vivió su niñez en un pueblo de Antioquia llamado Carolina del Príncipe (donde se levantó una estatua el 12 de octubre de 2007 en su honor), en el seno de una familia influenciada por la música. A su corta edad su padre y sus cinco hermanos le enseñan a tocar la guitarra, instrumento que lo ha acompañado toda su vida musical.\n\nComenzó su carrera artística',
  'similares': ['Bacilos', 'Carlos Vives', 'Maná', 'Chayanne', 'Cabas'],
  'tags': ['latin', 'pop', 'spanish', 'rock', 'latino']},
 {'artista_buscado': 'Duki',
  'nombre': 'Duki',
  'listeners': '298201',
  'playcount': '43048568',
  'biografia': 'Mauro Ezequiel Lombardo (Almagro, Argentina; 24 de junio de 1996), conocido artísticamente como Duki, es un cantante, trapero y freestyler argentino.',
  'similares': ['Ysy A', 'Khea', 'LIT killah', 'Neo Pistea', 'Bhavi'],
  'tags': ['trap', 'latin', 'argentina', 'Latin Trap', 'Hip Hop Latino']},
 {'artista_buscado': 'María Becerra',
  'nombre': 'María Becerra',
  'listeners': '509',
  'playcount': '7097',
  'biografia': '',
  'similares': ['Maria Becerra',
   'Natti Natasha',
   'Sofía Reyes',
   'Myke Towers',
   'Cazzu'],
  'tags': ['Reggaeton', 'trap', 'argentina']},
 {'artista_buscado': 'Tini Stoessel',
  'nombre': 'Tini Stoessel',
  'listeners': '49',
  'playcount': '486',
  'biografia': '',
  'similares': ['Rusherking, Maria Becerra',
   'Laid Back Avenue',
   'La Konga',
   'Emilia & Duki',
   'Axwell Ʌ Ingrosso'],
  'tags': []},
 {'artista_buscado': 'Nicki Nicole',
  'nombre': 'Nicki Nicole',
  'listeners': '257172',
  'playcount': '10846174',
  'biografia': 'Nicki Nicole es una cantante y compositora nacida el 25 de agosto de 2000 en Rosario, Argentina. Su nombre completo es Nicole Denise Cucco, y es considerada una de las máximas exponentes del trap y el rap en Latinoamérica. Creció en el barrio Echesortu y, desde pequeña, mostró inclinación por la música, participando en eventos escolares y familiares.\n\nDebutó en 2019 con su sencillo "Wapo Traketero", que rápidamente se volvió viral en YouTube.',
  'similares': ['Maria Becerra', 'Cazzu', 'Emilia', 'Wos', 'Paulo Londra'],
  'tags': ['pop', 'argentina', 'rnb', 'indie pop', 'latinoamerica']},
 {'artista_buscado': 'Cazzu',
  'nombre': 'Cazzu',
  'listeners': '207599',
  'playcount': '5879351',
  'biografia': 'Julieta Emilia Cazzucheli, conocida por su nombre artístico Cazzu, es una cantante y compositora argentina de trap.\u200b\u200b Es considerada una de las grandes exponentes del Trap latino, con una carrera en pleno ascenso. Los medios nacionales y otros artistas del género y colegas se refieren a ella como "La Jefa".',
  'similares': ['Maria Becerra',
   'Nicki Nicole',
   'Lali',
   'La Joaqui',
   'Emilia'],
  'tags': ['pop', 'Hip-Hop', 'rnb', 'trap', 'trap latino']},
 {'artista_buscado': 'Lali',
  'nombre': 'Lali',
  'listeners': '133027',
  'playcount': '9000043',
  'biografia': 'Lali es una cantautora y actriz argentina. Desde pequeña ha incursionado el mundo artístico a través de distintas producciones exitosas en televisión, cine y teatro.\nSus canciones la han ubicado como una de las voces pop en español más escuchadas a nivel mundial.\nEn 2013 lanzó su álbum debut "A Bailar" de manera independiente, con el que se transformó en una precursora del pop femenino en Sur América.\nEn 2016 lanza "SOY" su segundo álbum',
  'similares': ['Angela Torres',
   'Maria Becerra',
   'Miranda!',
   'Cazzu',
   'Floricienta'],
  'tags': ['argentina', 'pop', 'dance', 'latin', 'argentine']},
 {'artista_buscado': 'Paulo Londra',
  'nombre': 'Paulo Londra',
  'listeners': '387196',
  'playcount': '16770023',
  'biografia': 'Paulo Ezequiel Londra Farías, más conocido como Paulo Londra (Córdoba, Argentina; 12 de abril de 1998) es un cantante argentino de trap.\nInició su carrera musical en enero de 2017 cuando lanzó su primer sencillo, Relax, que luego de unos meses estaba posicionado como un hit argentino del año. Desde entonces empezó a componer y continuó lanzando canciones. A pesar de que sus inicios son similares a otros exponentes urbanos, Londra, a diferencia de otros artistas, evita tocar temas como violencia, insultos o drogas en sus canciones.',
  'similares': ['LIT killah', 'Duki', 'Trueno', 'Khea', 'Wos'],
  'tags': ['argentina',
   'trap',
   'trap latino',
   'white rapper',
   'trap argentino']},
 {'artista_buscado': 'Shakira',
  'nombre': 'Shakira',
  'listeners': '4881220',
  'playcount': '180195664',
  'biografia': 'Shakira Isabel Mebarak Ripoll, es una cantante y compositora de pop-rock en español e inglés, nació el 2 de Febrero de 1977 en Barranquilla, Colombia. En árabe, Shakira (شاكرة) significa "llena de gracia". Ha sido ganadora en dos ocasiones del Premio Grammy y ocho veces ganadora del Grammy Latino.La artista ha vendido más de 135 millones de records según informa NBC.\n\nSe trata de una de las cantantes del ámbito musical latino con más éxito internacional.',
  'similares': ['Paulina Rubio',
   'Belinda',
   'Thalía',
   'KAROL G',
   'Julieta Venegas'],
  'tags': ['pop', 'latin', 'female vocalists', 'spanish', 'rock']},
 {'artista_buscado': 'Bizarrap',
  'nombre': 'Bizarrap',
  'listeners': '926528',
  'playcount': '46018935',
  'biografia': 'Gonzalo Julián Conde mejor conocido artísticamente como Bizarrap es un productor discográfico argentino, nacido el 29 de agosto de 1998 en Ramos Mejía, Argentina. Se especializa en géneros como trap, latin trap y rap.',
  'similares': ['Duki', 'Milo j', 'LIT killah', 'Khea', 'Bhavi'],
  'tags': ['argentina', 'rap', 'trap', 'latin', 'pinga']},
 {'artista_buscado': 'Emilia',
  'nombre': 'Emilia',
  'listeners': '501626',

In [42]:
df_lastfm = pd.DataFrame(info_artistas)
df_lastfm

,artista_buscado,nombre,listeners,playcount,biografia,similares,tags
0,Taylor Swift,Taylor Swift,5941473,3677983140,"Taylor Alison Swift (Reading, Pennsylvania, 13...","[Sabrina Carpenter, Olivia Rodrigo, Gracie Abr...","[country, pop, female vocalists, singer-songwr..."
1,Drake,Drake,6722037,1166074902,"Aubrey Drake Graham (24 de octubre de 1986), c...","[PARTYNEXTDOOR, DJ Khaled, Drake & Future, Tor...","[Hip-Hop, rap, rnb, hip hop, Canadian]"
2,Morgan Wallen,Morgan Wallen,986913,91544677,Morgan Wallen (nacido el 13 de mayo de 1993 en...,"[Bailey Zimmerman, Luke Combs, Tucker Wetmore,...","[country, country pop, contemporary country, t..."
3,Kendrick Lamar,Kendrick Lamar,5099421,1031948825,"Kendrick Lamar Duckworth (17 Junio, 1987), es ...","[Baby Keem, JID, Jay Rock, Black Hippy, Tyler,...","[Hip-Hop, rap, west coast, hip hop, compton]"
4,The Weeknd,The Weeknd,5320117,1123613252,"Abel Makkonen Tesfaye, mejor conocido por su n...","[Tory Lanez, Drake, Black Atlass, PARTYNEXTDOO...","[rnb, electronic, dubstep, Canadian, prog-rnb]"
5,SZA,SZA,3497700,588174194,Solana Rowe (nacida el 8 de Noviembre de 1989)...,"[Summer Walker, Doja Cat, Kali Uchis, Doechii,...","[rnb, soul, alternative rnb, electronic, Neo-S..."
6,Zach Bryan,Zach Bryan,1205931,136678363,Zachary Lane Bryan es un cantautor estadounide...,"[Sam Barber, Dylan Gossett, Charles Wesley God...","[country, singer-songwriter, americana, Alt-co..."
7,Tyler The Creator,"Tyler, The Creator",4333565,1053111426,"Tyler Okonma (6 de marzo de 1991), más conocid...","[OFWGKTA, Kendrick Lamar, Domo Genesis, Childi...","[Hip-Hop, rap, ofwgkta, underground hip-hop, s..."
8,Billie Eilish,Billie Eilish,4232010,836742492,Billie Eilish Pirate Baird O'Connell​ (Los Áng...,"[FINNEAS, Olivia Rodrigo, Melanie Martinez, La...","[pop, indie pop, electropop, art pop, alternat..."
9,Ariana Grande,Ariana Grande,4484810,1112472000,"Ariana Grande Butera (Boca Ratón, 26 de junio ...","[Jessie J, Ariana Grande & Nicki Minaj, Madiso...","[pop, rnb, female vocalists, Ariana Grande, am..."
10,Bad Bunny,Bad Bunny,2583506,407351101,"Benito Antonio Martínez Ocasio, mejor conocido...","[JHAYCO, Rauw Alejandro, Tainy, Mora, Trio Veg...","[Reggaeton, trap, latin, puerto rico, trap lat..."
11,Karol G,KAROL G,1446042,75934691,"Carolina Giraldo Navarro (Medellín, Colombia, ...","[Natti Natasha, J Balvin, Maluma, Becky G, Mar...","[Reggaeton, pop, latin pop, latin, Colombia]"
12,Myke Towers,Myke Towers,659832,28489794,"Michael Torres (Río Piedras, Puerto Rico, 15 d...","[JHAYCO, Dei V, Bryant Myers, Mora, Anuel AA]","[Reggaeton, puerto rico, latin, trap, rap]"
13,Quevedo,Quevedo,386264,23722085,"Pedro Domínguez Quevedo, más conocido por su n...","[Myke Towers, JHAYCO, Gonzy, Omar Courtz, Feid]","[Reggaeton, rap, spanish, Hip-Hop, spain]"
14,Aitana,Aitana,243729,14829901,"Aitana Ocaña Morales, conocida simplemente com...","[Belén Aguilera, Ana Mena, Lola Indigo, Amaia,...","[spanish, pop, spain, female vocalists, pop rock]"
15,Rosalía,ROSALÍA,1868077,203852560,"Rosalía Vila Tobella, conocida mundialmente co...","[Judeline, Lorde, Robyn, Bad Gyal, NATHY PELUSO]","[pop, Flamenco, spanish, art pop, Flamenco Nuevo]"
16,Morad,Morad,207124,9314374,Morad es el nombre artístico de un rapero cata...,"[Baby Gang, Rvfv, Capo Plaza, Sfera Ebbasta, A...","[rap, Hip-Hop, hip hop, french, All]"
17,Melendi,Melendi,316017,8232484,Ramón Melendi nace en Oviedo en 1979. Aunque v...,"[Estopa, El Canto del Loco, Maldita Nerea, Per...","[spanish, pop, Flamenco, new flamenco, Espanol]"
18,Enrique Iglesias,Enrique Iglesias,2712737,54246937,Enrique Miguel Iglesias Preysler (n. 8 de mayo...,"[Ricky Martin, Chayanne, Luis Fonsi, Alejandro...","[pop, latin, spanish, dance, latin pop]"
19,Juanes,Juanes,1209521,21965331,Juan Esteban Aristizábal nació el 9 de agosto ...,"[Bacilos, Carlos Vives, Maná, Chayanne, Cabas]","[latin, pop, spanish, rock, latino]"
20,Duki,Duki,298201,43048568,"Mauro Ezequiel Lombardo (Almagro, Argentina; 2...","[Ysy A, Khea, LIT killah, Neo Pistea, Bhavi]","[trap, latin, argentina, Latin Trap, Hip Hop L..."
21,María Becerra,María Becerra,509,7097,,"[Maria Becerra, Natti Natasha, Sofía Reyes, My...","[Reggaeton, trap, argentina]"
22,Tini Stoessel,Tini Stoessel,49,486,,"[Rusherking, Maria Becerra, Laid Back Avenue, ...",[]
23,Nicki Nicole,Nicki Nicole,257172,10846174,Nicki Nicole es una cantante y compositora nac...,"[Maria Becerra, Cazzu, Emilia, Wos, Paulo Londra]","[pop, argentina, rnb, indie pop, latinoamerica]"
24,Cazzu,Cazzu,207599,5879351,"Julieta Emilia Cazzucheli, conocida por su nom...","[Maria Becerra, Nicki Nicole, Lali, La Joaqui,...","[pop, Hip-Hop, rnb, trap, trap latino]"
25,Lali,Lali,133027,9000043,Lali es una cantautora y actriz argentina. Des...,"[Angela Torres, Maria Becerra, Miranda!, Cazzu...","[argentina, pop, dance, latin, argentine]"
26,Paulo Londra,Paulo Londra,387196,16770023,"Paulo Ezequiel Londra Farías, más conocido com...","[LIT killah, Duki, Trueno, Khea, Wos]","[argentina, trap, trap latino, white rapper, t..."
27,Shakira,Shakira,4881220,180195664,"Shakira Isabel Mebarak Ripoll, es una cantante...","[Paulina Rubio, Belinda, Thalía, KAROL G, Juli...","[pop, latin, female vocalists, spanish, rock]"
28,Bizarrap,Bizarrap,926528,46018935,Gonzalo Julián Conde mejor conocido artísticam...,"[Duki, Milo j, LIT killah, Khea, Bhavi]","[argentina, rap, trap, latin, pinga]"
29,Emilia,Emilia,501626,18933502,"Emilia Mernes (29 de Octubre de 1996, Nogoyá, ...","[Maria Becerra, Tini, Nicki Nicole, Lali, Cazzu]","[pop, female vocalists, swedish, 90s, argentina]"

In [43]:
df_lastfm["listeners"] = df_lastfm["listeners"].astype(int)
df_lastfm["playcount"] = df_lastfm["playcount"].astype(int)

In [44]:
df_lastfm["ratio_popularidad"] = df_lastfm["playcount"] / df_lastfm["listeners"]

In [45]:
df_lastfm.info()
df_lastfm.head()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   artista_buscado    30 non-null     str
 1   nombre             30 non-null     str
 2   listeners          30 non-null     int64
 3   playcount          30 non-null     int64
 4   biografia          30 non-null     str
 5   similares          30 non-null     object
 6   tags               30 non-null     object
 7   ratio_popularidad  30 non-null     float64
dtypes: float64(1), int64(2), object(2), str(3)
memory usage: 2.0+ KB

,artista_buscado,nombre,listeners,playcount,biografia,similares,tags,ratio_popularidad
0,Taylor Swift,Taylor Swift,5941473,3677983140,"Taylor Alison Swift (Reading, Pennsylvania, 13...","[Sabrina Carpenter, Olivia Rodrigo, Gracie Abr...","[country, pop, female vocalists, singer-songwr...",619.035572
1,Drake,Drake,6722037,1166074902,"Aubrey Drake Graham (24 de octubre de 1986), c...","[PARTYNEXTDOOR, DJ Khaled, Drake & Future, Tor...","[Hip-Hop, rap, rnb, hip hop, Canadian]",173.470468
2,Morgan Wallen,Morgan Wallen,986913,91544677,Morgan Wallen (nacido el 13 de mayo de 1993 en...,"[Bailey Zimmerman, Luke Combs, Tucker Wetmore,...","[country, country pop, contemporary country, t...",92.758609
3,Kendrick Lamar,Kendrick Lamar,5099421,1031948825,"Kendrick Lamar Duckworth (17 Junio, 1987), es ...","[Baby Keem, JID, Jay Rock, Black Hippy, Tyler,...","[Hip-Hop, rap, west coast, hip hop, compton]",202.365881
4,The Weeknd,The Weeknd,5320117,1123613252,"Abel Makkonen Tesfaye, mejor conocido por su n...","[Tory Lanez, Drake, Black Atlass, PARTYNEXTDOO...","[rnb, electronic, dubstep, Canadian, prog-rnb]",211.200854

In [46]:
df_lastfm.to_csv("lastfm_artistas.csv", index=False, encoding="utf-8-sig")

In [47]:
df_lastfm.head(30)

,artista_buscado,nombre,listeners,playcount,biografia,similares,tags,ratio_popularidad
0,Taylor Swift,Taylor Swift,5941473,3677983140,"Taylor Alison Swift (Reading, Pennsylvania, 13...","[Sabrina Carpenter, Olivia Rodrigo, Gracie Abr...","[country, pop, female vocalists, singer-songwr...",619.035572
1,Drake,Drake,6722037,1166074902,"Aubrey Drake Graham (24 de octubre de 1986), c...","[PARTYNEXTDOOR, DJ Khaled, Drake & Future, Tor...","[Hip-Hop, rap, rnb, hip hop, Canadian]",173.470468
2,Morgan Wallen,Morgan Wallen,986913,91544677,Morgan Wallen (nacido el 13 de mayo de 1993 en...,"[Bailey Zimmerman, Luke Combs, Tucker Wetmore,...","[country, country pop, contemporary country, t...",92.758609
3,Kendrick Lamar,Kendrick Lamar,5099421,1031948825,"Kendrick Lamar Duckworth (17 Junio, 1987), es ...","[Baby Keem, JID, Jay Rock, Black Hippy, Tyler,...","[Hip-Hop, rap, west coast, hip hop, compton]",202.365881
4,The Weeknd,The Weeknd,5320117,1123613252,"Abel Makkonen Tesfaye, mejor conocido por su n...","[Tory Lanez, Drake, Black Atlass, PARTYNEXTDOO...","[rnb, electronic, dubstep, Canadian, prog-rnb]",211.200854
5,SZA,SZA,3497700,588174194,Solana Rowe (nacida el 8 de Noviembre de 1989)...,"[Summer Walker, Doja Cat, Kali Uchis, Doechii,...","[rnb, soul, alternative rnb, electronic, Neo-S...",168.160275
6,Zach Bryan,Zach Bryan,1205931,136678363,Zachary Lane Bryan es un cantautor estadounide...,"[Sam Barber, Dylan Gossett, Charles Wesley God...","[country, singer-songwriter, americana, Alt-co...",113.338460
7,Tyler The Creator,"Tyler, The Creator",4333565,1053111426,"Tyler Okonma (6 de marzo de 1991), más conocid...","[OFWGKTA, Kendrick Lamar, Domo Genesis, Childi...","[Hip-Hop, rap, ofwgkta, underground hip-hop, s...",243.012722
8,Billie Eilish,Billie Eilish,4232010,836742492,Billie Eilish Pirate Baird O'Connell​ (Los Áng...,"[FINNEAS, Olivia Rodrigo, Melanie Martinez, La...","[pop, indie pop, electropop, art pop, alternat...",197.717513
9,Ariana Grande,Ariana Grande,4484810,1112472000,"Ariana Grande Butera (Boca Ratón, 26 de junio ...","[Jessie J, Ariana Grande & Nicki Minaj, Madiso...","[pop, rnb, female vocalists, Ariana Grande, am...",248.053318
10,Bad Bunny,Bad Bunny,2583506,407351101,"Benito Antonio Martínez Ocasio, mejor conocido...","[JHAYCO, Rauw Alejandro, Tainy, Mora, Trio Veg...","[Reggaeton, trap, latin, puerto rico, trap lat...",157.673758
11,Karol G,KAROL G,1446042,75934691,"Carolina Giraldo Navarro (Medellín, Colombia, ...","[Natti Natasha, J Balvin, Maluma, Becky G, Mar...","[Reggaeton, pop, latin pop, latin, Colombia]",52.512092
12,Myke Towers,Myke Towers,659832,28489794,"Michael Torres (Río Piedras, Puerto Rico, 15 d...","[JHAYCO, Dei V, Bryant Myers, Mora, Anuel AA]","[Reggaeton, puerto rico, latin, trap, rap]",43.177345
13,Quevedo,Quevedo,386264,23722085,"Pedro Domínguez Quevedo, más conocido por su n...","[Myke Towers, JHAYCO, Gonzy, Omar Courtz, Feid]","[Reggaeton, rap, spanish, Hip-Hop, spain]",61.414175
14,Aitana,Aitana,243729,14829901,"Aitana Ocaña Morales, conocida simplemente com...","[Belén Aguilera, Ana Mena, Lola Indigo, Amaia,...","[spanish, pop, spain, female vocalists, pop rock]",60.845862
15,Rosalía,ROSALÍA,1868077,203852560,"Rosalía Vila Tobella, conocida mundialmente co...","[Judeline, Lorde, Robyn, Bad Gyal, NATHY PELUSO]","[pop, Flamenco, spanish, art pop, Flamenco Nuevo]",109.124281
16,Morad,Morad,207124,9314374,Morad es el nombre artístico de un rapero cata...,"[Baby Gang, Rvfv, Capo Plaza, Sfera Ebbasta, A...","[rap, Hip-Hop, hip hop, french, All]",44.970037
17,Melendi,Melendi,316017,8232484,Ramón Melendi nace en Oviedo en 1979. Aunque v...,"[Estopa, El Canto del Loco, Maldita Nerea, Per...","[spanish, pop, Flamenco, new flamenco, Espanol]",26.050763
18,Enrique Iglesias,Enrique Iglesias,2712737,54246937,Enrique Miguel Iglesias Preysler (n. 8 de mayo...,"[Ricky Martin, Chayanne, Luis Fonsi, Alejandro...","[pop, latin, spanish, dance, latin pop]",19.997124
19,Juanes,Juanes,1209521,21965331,Juan Esteban Aristizábal nació el 9 de agosto ...,"[Bacilos, Carlos Vives, Maná, Chayanne, Cabas]","[latin, pop, spanish, rock, latino]",18.160355
20,Duki,Duki,298201,43048568,"Mauro Ezequiel Lombardo (Almagro, Argentina; 2...","[Ysy A, Khea, LIT killah, Neo Pistea, Bhavi]","[trap, latin, argentina, Latin Trap, Hip Hop L...",144.360911
21,María Becerra,María Becerra,509,7097,,"[Maria Becerra, Natti Natasha, Sofía Reyes, My...","[Reggaeton, trap, argentina]",13.943026
22,Tini Stoessel,Tini Stoessel,49,486,,"[Rusherking, Maria Becerra, Laid Back Avenue, ...",[],9.918367
23,Nicki Nicole,Nicki Nicole,257172,10846174,Nicki Nicole es una cantante y compositora nac...,"[Maria Becerra, Cazzu, Emilia, Wos, Paulo Londra]","[pop, argentina, rnb, indie pop, latinoamerica]",42.174786
24,Cazzu,Cazzu,207599,5879351,"Julieta Emilia Cazzucheli, conocida por su nom...","[Maria Becerra, Nicki Nicole, Lali, La Joaqui,...","[pop, Hip-Hop, rnb, trap, trap latino]",28.320710
25,Lali,Lali,133027,9000043,Lali es una cantautora y actriz argentina. Des...,"[Angela Torres, Maria Becerra, Miranda!, Cazzu...","[argentina, pop, dance, latin, argentine]",67.655762
26,Paulo Londra,Paulo Londra,387196,16770023,"Paulo Ezequiel Londra Farías, más conocido com...","[LIT killah, Duki, Trueno, Khea, Wos]","[argentina, trap, trap latino, white rapper, t...",43.311457
27,Shakira,Shakira,4881220,180195664,"Shakira Isabel Mebarak Ripoll, es una cantante...","[Paulina Rubio, Belinda, Thalía, KAROL G, Juli...","[pop, latin, female vocalists, spanish, rock]",36.916112
28,Bizarrap,Bizarrap,926528,46018935,Gonzalo Julián Conde mejor conocido artísticam...,"[Duki, Milo j, LIT killah, Khea, Bhavi]","[argentina, rap, trap, latin, pinga]",49.668154
29,Emilia,Emilia,501626,18933502,"Emilia Mernes (29 de Octubre de 1996, Nogoyá, ...","[Maria Becerra, Tini, Nicki Nicole, Lali, Cazzu]","[pop, female vocalists, swedish, 90s, argentina]",37.744260