## PROYECTO - MODULO 2

**Extracción de Datos API Deezer**

In [1]:
import requests
import time
import pandas as pd
import json

#### Lista de 30 artistas populares (Argentina, España y EEUU)

In [2]:
lista_artistas = [
 
    # 🇺🇸 EEUU (10)
    "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
 
    # 🇪🇸 España (10)
    "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
    "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
 
    # 🇦🇷 Argentina (10)
    "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
    "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
]
 
print(f"Total: {len(lista_artistas)} artistas")

Total: 30 artistas

#### Consulta de artistas en Deezer API

In [3]:
lista_artistas = [
 
    # 🇺🇸 EEUU (10)
    "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
 
    # 🇪🇸 España (10)
    "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
    "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
 
    # 🇦🇷 Argentina (10)
    "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
    "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
]

artista_search = []

for artista in lista_artistas:
    consulta=requests.get(f"https://api.deezer.com/search/artist?q={artista}&index=0&limit=1")
    consulta.status_code

    if consulta.status_code != 200:
        print(f"No se pudo realizar la consulta del artista: {artista}.\n Error : {consulta.status_code}") 

    datos=consulta.json()
    artista_search.append(datos['data'][0])

print(artista_search)

[{'id': 12246, 'name': 'Taylor Swift', 'link': 'https://www.deezer.com/artist/12246', 'picture': 'https://api.deezer.com/artist/12246/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/1000x1000-000000-80-0-0.jpg', 'nb_album': 124, 'nb_fan': 12525803, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12246/top?limit=50', 'type': 'artist'}, {'id': 246791, 'name': 'Drake', 'link': 'https://www.deezer.com/artist/246791', 'picture': 'https://api.deezer.com/artist/246791/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/1000x1000-000000-80-0-0.jpg', 'nb_album': 76, 'nb_fan': 23933582, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/246791/top?limit=50', 'type': 'artist'}, {'id': 386950521, 'name': 'Morgan Wallen', 'link': 'https://www.deezer.com/artist/386950521', 'picture': 'https://api.deezer.com/artist/386950521/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/1000x1000-000000-80-0-0.jpg', 'nb_album': 1, 'nb_fan': 9, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/386950521/top?limit=50', 'type': 'artist'}, {'id': 525046, 'name': 'Kendrick Lamar', 'link': 'https://www.deezer.com/artist/525046', 'picture': 'https://api.deezer.com/artist/525046/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg', 'nb_album': 40, 'nb_fan': 6080689, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/525046/top?limit=50', 'type': 'artist'}, {'id': 4050205, 'name': 'The Weeknd', 'link': 'https://www.deezer.com/artist/4050205', 'picture': 'https://api.deezer.com/artist/4050205/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg', 'nb_album': 86, 'nb_fan': 14426054, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4050205/top?limit=50', 'type': 'artist'}, {'id': 5531258, 'name': 'SZA', 'link': 'https://www.deezer.com/artist/5531258', 'picture': 'https://api.deezer.com/artist/5531258/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg', 'nb_album': 40, 'nb_fan': 1283716, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5531258/top?limit=50', 'type': 'artist'}, {'id': 71855892, 'name': 'Zach Bryan', 'link': 'https://www.deezer.com/artist/71855892', 'picture': 'https://api.deezer.com/artist/71855892/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/1000x1000-000000-80-0-0.jpg', 'nb_album': 38, 'nb_fan': 112752, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/71855892/top?limit=50', 'type': 'artist'}, {'id': 1194083, 'name': 'Tyler, The Creator', 'link': 'https://www.deezer.com/artist/1194083', 'picture': 'https://api.deezer.com/artist/1194083/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/1000x1000-000000-80-0-0.jpg', 'nb_album': 29, 'nb_fan': 1324163, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/1194083/top?limit=50', 'type': 'artist'}, {'id': 9635624, 'name': 'Billie Eilish', 'link': 'https://www.deezer.com/artist/9635624', 'picture': 'https://api.deezer.com/artist/9635624/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg', 'nb_album': 32, 'nb_fan': 9113151, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/9635624/top?limit=50', 'type': 'artist'}, {'id': 1562681, 'name': 'Ariana Grande', 'link': 'https://www.deezer.com/artist/1562681', 'picture': 'https://api.deezer.com/artist/1562681/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/1000x1000-000000-80-0-0.jpg', 'nb_album': 69, 'nb_fan': 13301064, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/1562681/top?limit=50', 'type': 'artist'}, {'id': 10583405, 'name': 'Bad Bunny', 'link': 'https://www.deezer.com/artist/10583405', 'picture': 'https://api.deezer.com/artist/10583405/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/1000x1000-000000-80-0-0.jpg', 'nb_album': 89, 'nb_fan': 7737974, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/10583405/top?limit=50', 'type': 'artist'}, {'id': 5297021, 'name': 'KAROL G', 'link': 'https://www.deezer.com/artist/5297021', 'picture': 'https://api.deezer.com/artist/5297021/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/1000x1000-000000-80-0-0.jpg', 'nb_album': 74, 'nb_fan': 3358065, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5297021/top?limit=50', 'type': 'artist'}, {'id': 12029862, 'name': 'Myke Towers', 'link': 'https://www.deezer.com/artist/12029862', 'picture': 'https://api.deezer.com/artist/12029862/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/1000x1000-000000-80-0-0.jpg', 'nb_album': 177, 'nb_fan': 1679143, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12029862/top?limit=50', 'type': 'artist'}, {'id': 6705223, 'name': 'Quevedo', 'link': 'https://www.deezer.com/artist/6705223', 'picture': 'https://api.deezer.com/artist/6705223/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/1000x1000-000000-80-0-0.jpg', 'nb_album': 105, 'nb_fan': 286581, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/6705223/top?limit=50', 'type': 'artist'}, {'id': 11928391, 'name': 'Aitana', 'link': 'https://www.deezer.com/artist/11928391', 'picture': 'https://api.deezer.com/artist/11928391/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg', 'nb_album': 58, 'nb_fan': 343384, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/11928391/top?limit=50', 'type': 'artist'}, {'id': 554792, 'name': 'ROSALÍA', 'link': 'https://www.deezer.com/artist/554792', 'picture': 'https://api.deezer.com/artist/554792/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/1000x1000-000000-80-0-0.jpg', 'nb_album': 37, 'nb_fan': 1022660, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/554792/top?limit=50', 'type': 'artist'}, {'id': 111130212, 'name': 'Morad', 'link': 'https://www.deezer.com/artist/111130212', 'picture': 'https://api.deezer.com/artist/111130212/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/1000x1000-000000-80-0-0.jpg', 'nb_album': 133, 'nb_fan': 322086, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/111130212/top?limit=50', 'type': 'artist'}, {'id': 2697, 'name': 'Melendi', 'link': 'https://www.deezer.com/artist/2697', 'picture': 'https://api.deezer.com/artist/2697/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/1000x1000-000000-80-0-0.jpg', 'nb_album': 72, 'nb_fan': 609172, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2697/top?limit=50', 'type': 'artist'}, {'id': 2792, 'name': 'Enrique Iglesias', 'link': 'https://www.deezer.com/artist/2792', 'picture': 'https://api.deezer.com/artist/2792/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/1000x1000-000000-80-0-0.jpg', 'nb_album': 106, 'nb_fan': 5940717, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2792/top?limit=50', 'type': 'artist'}, {'id': 70, 'name': 'Juanes', 'link': 'https://www.deezer.com/artist/70', 'picture': 'https://api.deezer.com/artist/70/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/1000x1000-000000-80-0-0.jpg', 'nb_album': 114, 'nb_fan': 1618058, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/70/top?limit=50', 'type': 'artist'}, {'id': 4902904, 'name': 'DUKI', 'link': 'https://www.deezer.com/artist/4902904', 'picture': 'https://api.deezer.com/artist/4902904/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/1000x1000-000000-80-0-0.jpg', 'nb_album': 155, 'nb_fan': 817543, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4902904/top?limit=50', 'type': 'artist'}, {'id': 14343187, 'name': 'Maria Becerra', 'link': 'https://www.deezer.com/artist/14343187', 'picture': 'https://api.deezer.com/artist/14343187/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/1000x1000-000000-80-0-0.jpg', 'nb_album': 75, 'nb_fan': 375276, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/14343187/top?limit=50', 'type': 'artist'}, {'id': 2252591, 'name': 'TINI', 'link': 'https://www.deezer.com/artist/2252591', 'picture': 'https://api.deezer.com/artist/2252591/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg', 'nb_album': 79, 'nb_fan': 905200, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2252591/top?limit=50', 'type': 'artist'}, {'id': 13299379, 'name': 'Nicki Nicole', 'link': 'https://www.deezer.com/artist/13299379', 'picture': 'https://api.deezer.com/artist/13299379/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg', 'nb_album': 64, 'nb_fan': 605597, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/13299379/top?limit=50', 'type': 'artist'}, {'id': 12268072, 'name': 'Cazzu', 'link': 'https://www.deezer.com/artist/12268072', 'picture': 'https://api.deezer.com/artist/12268072/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/1000x1000-000000-80-0-0.jpg', 'nb_album': 56, 'nb_fan': 599021, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12268072/top?limit=50', 'type': 'artist'}, {'id': 5181388, 'name': 'Lali', 'link': 'https://www.deezer.com/artist/5181388', 'picture': 'https://api.deezer.com/artist/5181388/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/1000x1000-000000-80-0-0.jpg', 'nb_album': 44, 'nb_fan': 48365, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5181388/top?limit=50', 'type': 'artist'}, {'id': 12637039, 'name': 'Paulo Londra', 'link': 'https://www.deezer.com/artist/12637039', 'picture': 'https://api.deezer.com/artist/12637039/image', 'picture_smal

In [4]:
artista_search

[{'id': 12246,
  'name': 'Taylor Swift',
  'link': 'https://www.deezer.com/artist/12246',
  'picture': 'https://api.deezer.com/artist/12246/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/1000x1000-000000-80-0-0.jpg',
  'nb_album': 124,
  'nb_fan': 12525803,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/12246/top?limit=50',
  'type': 'artist'},
 {'id': 246791,
  'name': 'Drake',
  'link': 'https://www.deezer.com/artist/246791',
  'picture': 'https://api.deezer.com/artist/246791/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/1000x1000-000000-80-0-0.jpg',
  'nb_album': 76,
  'nb_fan': 23933582,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/246791/top?limit=50',
  'type': 'artist'},
 {'id': 386950521,
  'name': 'Morgan Wallen',
  'link': 'https://www.deezer.com/artist/386950521',
  'picture': 'https://api.deezer.com/artist/386950521/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/1000x1000-000000-80-0-0.jpg',
  'nb_album': 1,
  'nb_fan': 9,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/386950521/top?limit=50',
  'type': 'artist'},
 {'id': 525046,
  'name': 'Kendrick Lamar',
  'link': 'https://www.deezer.com/artist/525046',
  'picture': 'https://api.deezer.com/artist/525046/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg',
  'nb_album': 40,
  'nb_fan': 6080689,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/525046/top?limit=50',
  'type': 'artist'},
 {'id': 4050205,
  'name': 'The Weeknd',
  'link': 'https://www.deezer.com/artist/4050205',
  'picture': 'https://api.deezer.com/artist/4050205/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg',
  'nb_album': 86,
  'nb_fan': 14426054,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/4050205/top?limit=50',
  'type': 'artist'},
 {'id': 5531258,
  'name': 'SZA',
  'link': 'https://www.deezer.com/artist/5531258',
  'picture': 'https://api.deezer.com/artist/5531258/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg',
  'nb_album': 40,
  'nb_fan': 1283716,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/5531258/top?limit=50',
  'type': 'artist'},
 {'id': 71855892,
  'name': 'Zach Bryan',
  'link': 'https://www.deezer.com/artist/71855892',
  'picture': 'https://api.deezer.com/artist/71855892/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/1000x1000-000000-80-0-0.jpg',
  'nb_album': 38,
  'nb_fan': 112752,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/71855892/top?limit=50',
  'type': 'artist'},
 {'id': 1194083,
  'name': 'Tyler, The Creator',
  'link': 'https://www.deezer.com/artist/1194083',
  'picture': 'https://api.deezer.com/artist/1194083/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/1000x1000-000000-80-0-0.jpg',
  'nb_album': 29,
  'nb_fan': 1324163,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/1194083/top?limit=50',
  'type': 'artist'},
 {'id': 9635624,
  'name': 'Billie Eilish',
  'link': 'https://www.deezer.com/artist/9635624',
  'picture': 'https://api.deezer.com/artist/9635624/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg',
  'nb_album': 32,
  'nb_fan': 9113151,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/9635624/top?limit=50',
  'type': 'artist'},
 {'id': 1562681,
  'name': 'Ariana Grande',
  'link': 'https://www.deezer.com/artist/1562681',
  'picture': 'https://api.deezer.com/artist/1562681/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/3504ffe2519090026bc359b689d22e20/1000x1000-000000-80-0-0.jpg',
  'nb_album': 69,
  'nb_fan': 13301064,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/1562681/top?limit=50',
  'type': 'artist'},
 {'id': 10583405,
  'name': 'Bad Bunny',
  'link': 'https://www.deezer.com/artist/10583405',
  'picture': 'https://api.deezer.com/artist/10583405/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/1000x1000-000000-80-0-0.jpg',
  'nb_album': 89,
  'nb_fan': 7737974,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/10583405/top?limit=50',
  'type': 'artist'},
 {'id': 5297021,
  'name': 'KAROL G',
  'link': 'https://www.deezer.com/artist/5297021',
  'picture': 'https://api.deezer.com/artist/5297021/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/1000x1000-000000-80-0-0.jpg',
  'nb_album': 74,
  'nb_fan': 3358065,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/5297021/top?limit=50',
  'type': 'artist'},
 {'id': 12029862,
  'name': 'Myke Towers',
  'link': 'https://www.deezer.com/artist/12029862',
  'picture': 'https://api.deezer.com/artist/12029862/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/1000x1000-000000-80-0-0.jpg',
  'nb_album': 177,
  'nb_fan': 1679143,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/12029862/top?limit=50',
  'type': 'artist'},
 {'id': 6705223,
  'name': 'Quevedo',
  'link': 'https://www.deezer.com/artist/6705223',
  'picture': 'https://api.deezer.com/artist/6705223/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/1000x1000-000000-80-0-0.jpg',
  'nb_album': 105,
  'nb_fan': 286581,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/6705223/top?limit=50',
  'type': 'artist'},
 {'id': 11928391,
  'name': 'Aitana',
  'link': 'https://www.deezer.com/artist/11928391',
  'picture': 'https://api.deezer.com/artist/11928391/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg',
  'nb_album': 58,
  'nb_fan': 343384,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/11928391/top?limit=50',
  'type': 'artist'},
 {'id': 554792,
  'name': 'ROSALÍA',
  'link': 'https://www.deezer.com/artist/554792',
  'picture': 'https://api.deezer.com/artist/554792/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/1000x1000-000000-80-0-0.jpg',
  'nb_album': 37,
  'nb_fan': 1022660,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/554792/top?limit=50',
  'type': 'artist'},
 {'id': 111130212,
  'name': 'Morad',
  'link': 'https://www.deezer.com/artist/111130212',
  'picture': 'https://api.deezer.com/artist/111130212/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/1000x1000-000000-80-0-0.jpg',
  'nb_album': 133,
  'nb_fan': 322086,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/111130212/top?limit=50',
  'type': 'artist'},
 {'id': 2697,
  'name': 'Melendi',
  'link': 'https://www.deezer.com/artist/2697',
  'picture': 'https://api.deezer.com/artist/2697/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/1000x1000-000000-80-0-0.jpg',
  'nb_album': 72,
  'nb_fan': 609172,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/2697/top?limit=50',
  'type': 'artist'},
 {'id': 2792,
  'name': 'Enrique Iglesias',
  'link': 'https://www.deezer.com/artist/2792',
  'picture': 'https://api.deezer.com/artist/2792/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/1000x1000-000000-80-0-0.jpg',
  'nb_album': 106,
  'nb_fan': 5940717,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/2792/top?limit=50',
  'type': 'artist'},
 {'id': 70,
  'name': 'Juanes',
  'link': 'https://www.deezer.com/artist/70',
  'picture': 'https://api.deezer.com/artist/70/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/1000x1000-000000-80-0-0.jpg',
  'nb_album': 114,
  'nb_fan': 1618058,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/70/top?limit=50',
  'type': 'artist'},
 {'id': 4902904,
  'name': 'DUKI',
  'link': 'https://www.deezer.com/artist/4902904',
  'picture': 'https://api.deezer.com/artist/4902904/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/1000x1000-000000-80-0-0.jpg',
  'nb_album': 155,
  'nb_fan': 817543,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/4902904/top?limit=50',
  'type': 'artist'},
 {'id': 14343187,
  'name': 'Maria Becerra',
  'link': 'https://www.deezer.com/artist/14343187',
  'picture': 'https://api.deezer.com/artist/14343187/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/1000x1000-000000-80-0-0.jpg',
  'nb_album': 75,
  'nb_fan': 375276,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/14343187/top?limit=50',
  'type': 'artist'},
 {'id': 2252591,
  'name': 'TINI',
  'link': 'https://www.deezer.com/artist/2252591',
  'picture': 'https://api.deezer.com/artist/2252591/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg',
  'nb_album': 79,
  'nb_fan': 905200,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/2252591/top?limit=50',
  'type': 'artist'},
 {'id': 13299379,
  'name': 'Nicki Nicole',
  'link': 'https://www.deezer.com/artist/13299379',
  'picture': 'https://api.deezer.com/artist/13299379/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg',
  'nb_album': 64,
  'nb_fan': 605597,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/13299379/top?limit=50',
  'type': 'artist'},
 {'id': 12268072,
  'name': 'Cazzu',
  'link': 'https://www.deezer.com/artist/12268072',
  'picture': 'https://api.deezer.com/artist/12268072/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/1000x1000-000000-80-0-0.jpg',
  'nb_album': 56,
  'nb_fan': 599021,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/12268072/top?limit=50',
  'type': 'artist'},
 {'id': 5181388,
  'name': 'Lali',
  'link': 'https://www.deezer.com/artist/5181388',
  'picture': 'https://api.deezer.com/artist/5181388/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/56x56-000000-80-0-0.jpg',

In [5]:
print(f"Total: {len(artista_search)} artistas")

Total: 30 artistas

LISTA INFORMACION DE ARTISTAS

In [6]:
artistas_info = []
for artista in artista_search:
    artistas_info.append({"id_artista": artista["id"], "nombre_artista":artista["name"]})
    for artista in artistas_info:     
        if artista["nombre_artista"] == "Morgan Wallen":         
            artista["id_artista"] = 7188840
        if artista["nombre_artista"] == "Shakira":         
            artista["id_artista"] = 160

artistas_info

[{'id_artista': 12246, 'nombre_artista': 'Taylor Swift'},
 {'id_artista': 246791, 'nombre_artista': 'Drake'},
 {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen'},
 {'id_artista': 525046, 'nombre_artista': 'Kendrick Lamar'},
 {'id_artista': 4050205, 'nombre_artista': 'The Weeknd'},
 {'id_artista': 5531258, 'nombre_artista': 'SZA'},
 {'id_artista': 71855892, 'nombre_artista': 'Zach Bryan'},
 {'id_artista': 1194083, 'nombre_artista': 'Tyler, The Creator'},
 {'id_artista': 9635624, 'nombre_artista': 'Billie Eilish'},
 {'id_artista': 1562681, 'nombre_artista': 'Ariana Grande'},
 {'id_artista': 10583405, 'nombre_artista': 'Bad Bunny'},
 {'id_artista': 5297021, 'nombre_artista': 'KAROL G'},
 {'id_artista': 12029862, 'nombre_artista': 'Myke Towers'},
 {'id_artista': 6705223, 'nombre_artista': 'Quevedo'},
 {'id_artista': 11928391, 'nombre_artista': 'Aitana'},
 {'id_artista': 554792, 'nombre_artista': 'ROSALÍA'},
 {'id_artista': 111130212, 'nombre_artista': 'Morad'},
 {'id_artista': 2697, 'nombre_artista': 'Melendi'},
 {'id_artista': 2792, 'nombre_artista': 'Enrique Iglesias'},
 {'id_artista': 70, 'nombre_artista': 'Juanes'},
 {'id_artista': 4902904, 'nombre_artista': 'DUKI'},
 {'id_artista': 14343187, 'nombre_artista': 'Maria Becerra'},
 {'id_artista': 2252591, 'nombre_artista': 'TINI'},
 {'id_artista': 13299379, 'nombre_artista': 'Nicki Nicole'},
 {'id_artista': 12268072, 'nombre_artista': 'Cazzu'},
 {'id_artista': 5181388, 'nombre_artista': 'Lali'},
 {'id_artista': 12637039, 'nombre_artista': 'Paulo Londra'},
 {'id_artista': 160, 'nombre_artista': 'Shakira'},
 {'id_artista': 12487862, 'nombre_artista': 'Bizarrap'},
 {'id_artista': 61094422, 'nombre_artista': 'Emilia'}]

In [7]:
len(artistas_info)

30

LISTA CANCIONES

In [8]:
import time

canciones = []
for artista in artistas_info:
    id_artista = artista["id_artista"]
    nombre_artista = artista["nombre_artista"]

    consulta_canciones = requests.get(f"https://api.deezer.com/artist/{id_artista}/top?limit=50")

    if consulta_canciones.status_code != 200:
        print(f"No se pudo consultar las canciones del artista: {nombre_artista}")
        continue
    datos_canciones = consulta_canciones.json()

    for cancion in datos_canciones["data"]:
        canciones.append({"id_artista": id_artista,
            "nombre_artista": nombre_artista,
            "titulo_cancion": cancion["title"],
            "titulo_album": cancion["album"]["title"],
            "tipo_cancion": cancion["type"]})
        
    time.sleep(1)

In [9]:
print (json.dumps(datos_canciones, indent=4, ensure_ascii=False))

{
    "data": [
        {
            "id": 3288087861,
            "readable": true,
            "title": "blackout ?",
            "title_short": "blackout ?",
            "title_version": "",
            "link": "https://www.deezer.com/track/3288087861",
            "duration": 180,
            "rank": 577836,
            "explicit_lyrics": false,
            "explicit_content_lyrics": 0,
            "explicit_content_cover": 2,
            "preview": "https://cdnt-preview.dzcdn.net/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3?hdnea=exp=1777458872~acl=/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3*~data=user_id=0,application_id=42~hmac=f2f3888cf17c6b87273f66add137f1ceddfef7b45f99b55dd2cc1cc3f41fe442",
            "contributors": [
                {
                    "id": 61094422,
                    "name": "Emilia",
                    "link": "https://www.deezer.com/artist/61094422",
                    "share": "https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/61094422/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 2252591,
                    "name": "TINI",
                    "link": "https://www.deezer.com/artist/2252591",
                    "share": "https://www.deezer.com/artist/2252591?utm_source=deezer&utm_content=artist-2252591&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/2252591/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 13299379,
                    "name": "Nicki Nicole",
                    "link": "https://www.deezer.com/artist/13299379",
                    "share": "https://www.deezer.com/artist/13299379?utm_source=deezer&utm_content=artist-13299379&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/13299379/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/13299379/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                }
            ],
            "md5_image": "fee888110d29c7d8021275c36004961f",
            "artist": {
                "id": 61094422,
                "name": "Emilia",
                "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
                "type": "artist"
            },
            "album": {
                "id": 730638231,
                "title": "blackout ?",
                "cover": "https://api.deezer.com/album/730638231/image",
                "cover_small": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/56x56-000000-80-0-0.jpg",
                "cover_medium": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/250x250-000000-80-0-0.jpg",
                "cover_big": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/500x500-000000-80-0-0.jpg",
                "cover_xl": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/1000x1000-000000-80-0-0.jpg",
                "md5_image": "fee888110d29c7d8021275c36004961f",
                "tracklist": "https://api.deezer.com/album/730638231/tracks",
                "type": "album"
            },
            "type": "track"
        },
        {
            "id": 1825853207,
            "readable": true,
            "title": "Quieres",
            "title_short": "Quieres",
            "title_version": "",
            "link": "https://www.deezer.com/track/1825853207",
            "duration": 213,
            "rank": 504369,
            "explicit_lyrics": false,
            "explicit_content_lyrics": 0,
            "explicit_content_cover": 0,
            "preview": "https://cdnt-preview.dzcdn.net/api/1/1/b/6/f/0/b6f2f5af86e9dc60e6c5746cf04024aa.mp3?hdnea=exp=1777458872~acl=/api/1/1/b/6/f/0/b6f2f5af86e9dc60e6c5746cf04024aa.mp3*~data=user_id=0,application_id=42~hmac=a31b3826d8bc224819dc001c0ebd5a0f6afa0233442bf2aa8dea5faffaea4e12",
            "contributors": [
                {
                    "id": 11928391,
                    "name": "Aitana",
                    "link": "https://www.deezer.com/artist/11928391",
                    "share": "https://www.deezer.com/artist/11928391?utm_source=deezer&utm_content=artist-11928391&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/11928391/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/11928391/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 61094422,
                    "name": "Emilia",
                    "link": "https://www.deezer.com/artist/61094422",
                    "share": "https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/61094422/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 81719632,
                    "name": "Ptazeta",
                    "link": "https://www.deezer.com/artist/81719632",
                    "share": "https://www.deezer.com/artist/81719632?utm_source=deezer&utm_content=artist-81719632&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/81719632/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/81719632/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                }
            ],
            "md5_image": "405226485b6c6bf695a2d5534be0cd89",
            "artist": {
                "id": 11928391,
                "name": "Aitana",
                "tracklist": "https://api.deezer.com/artist/11928391/top?limit=50",
                "type": "artist"
            },
            "album": {
                "id": 336049067,
                "title": "Quieres",
                "cover": "https://api.deezer.com/album/336049067/image",
                "cover_small": "https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/56x56-000000-80-0-0.jpg",
                "cover_medium": "https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/250x250-000000-80-0-0.jpg",
                "cover_big": "https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/500x500-000000-80-0-0.jpg",
                "cover_xl": "https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/1000x1000-000000-80-0-0.jpg",
                "md5_image": "405226485b6c6bf695a2d5534be0cd89",
                "tracklist": "https://api.deezer.com/album/336049067/tracks",
                "type": "album"
            },
            "type": "track"
        },
        {
            "id": 3829132661,
            "readable": true,
            "title": "JETSKI - Remix",
            "title_short": "JETSKI - Remix",
            "title_version": "",
            "link": "https://www.deezer.com/track/3829132661",
            "duration": 181,
            "rank": 669671,
            "explicit_lyrics": true,
            "explicit_content_lyrics": 1,
            "explicit_content_cover": 2,
            "preview": "https://cdnt-preview.dzcdn.net/api/1/1/d/3/3/0/d33fe67da20e36deea296de834976f2f.mp3?hdnea=exp=1777458872~acl=/api/1/1/d/3/3/0/d33fe67da20e36deea296de834976f2f.mp3*~data=user_id=0,application_id=42~hmac=5ccfea9b8a76e7ddb61cbd0aed2e01ea6cb2290c37d05998048156311ad67e6b",
            "contributors": [
                {
                    "id": 50633822,
                    "name": "PEDRO SAMPAIO",
                    "link": "https://www.deezer.com/artist/50633822",
                    "share": "https://www.deezer.com/artist/50633822?utm_source=deezer&utm_content=artist-50633822&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/50633822/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/50633822/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 61094422,
                    "name": "Emilia",
                    "link": "https://www.deezer.com/artist/61094422",
                    "share": "https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/61094422/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 118232102,
                    "name": "MC Meno K",
                    "link": "https://www.deezer.com/artist/118232102",
                    "share": "https://www.deezer.com/artist/118232102?utm_source=deezer&utm_content=artist-118232102&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/118232102/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/118232102/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 123505,
                    "name": "Melody",
                    "link": "https://www.deezer.com/artist/123505",
                    "share": "https://www.deezer.com/artist/123505?utm_source=deezer&utm_content=artist-123505&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/123505/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/123505/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                }
            ],
            "md5_image": "811342cf7292c03bf399b208523a2334",
            "artist": {
                "id": 50633822,
                "name": "PEDRO SAMPAIO",
                "tracklist": "https://api.deezer.com/artist/50633822/top?limit=50",
                "type": "artist"
            },
            "album": {
                "id": 913604051,
                "title": "JETSKI - Remix",
                "cover": "https://api.deezer.com/album/913604051/image",
                "cover_small": "https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/56x56-000000-80-0-0.jpg",
                "cover_medium": "https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/250x250-000000-80-0-0.jpg",
                "cover_big": "https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/500x500-000000-80-0-0.jpg",
                "cover_xl": "https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/1000x1000-000000-80-0-0.jpg",
                "md5_image": "811342cf7292c03bf399b208523a2334",
                "tracklist": "https://api.deezer.com/album/913604051/tracks",
                "type": "album"
            },
            "type": "track"
        },
        {
            "id": 2498029491,
            "readable": true,
            "title": "La_Original.mp3",
            "title_short": "La_Original.mp3",
            "title_version": "",
            "link": "https://www.deezer.com/track/2498029491",
            "duration": 140,
            "rank": 541606,
            "explicit_lyrics": false,
            "explicit_content_lyrics": 0,
            "explicit_content_cover": 2,
            "preview": "https://cdnt-preview.dzcdn.net/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3?hdnea=exp=1777458872~acl=/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3*~data=user_id=0,application_id=42~hmac=a2e628e90e906ccf90790c25b67d86349521ff346286c7bbb65c57ca2a9d2e81",
            "contributors": [
                {
                    "id": 61094422,
                    "name": "Emilia",
                    "link": "https://www.deezer.com/artist/61094422",
                    "share": "https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web",
                    "picture": "https://api.deezer.com/artist/61094422/image",
                    "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
                    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
                    "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
                    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
                    "radio": true,
                    "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
                    "type": "artist",
                    "role": "Main"
                },
                {
                    "id": 2252591,
                    "name": "TINI",
                    "link": "https://www.deezer.com/artist/2252591",
                    "share": "https://www.deezer.com/artist/2252591?utm_source=deezer&utm_content=artist-2252591&utm_term=0_1777457972&utm_medium=web",

In [10]:
canciones

[{'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'The Fate of Ophelia',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Opalite',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Elizabeth Taylor',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Blank Space',
  'titulo_album': '1989 (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "Out Of The Woods (Taylor's Version)",
  'titulo_album': "1989 (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Shake It Off',
  'titulo_album': '1989 (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Eldest Daughter',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'cardigan',
  'titulo_album': 'folklore',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Cruel Summer',
  'titulo_album': 'Lover',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Father Figure',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Wildest Dreams',
  'titulo_album': '1989 (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Style',
  'titulo_album': '1989 (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Actually Romantic',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Anti-Hero',
  'titulo_album': 'Midnights',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Daylight',
  'titulo_album': 'Lover',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Anti-Hero (Acoustic Version)',
  'titulo_album': 'Anti-Hero (Acoustic Version)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'exile',
  'titulo_album': 'folklore (deluxe version)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Ruin The Friendship',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'my tears ricochet',
  'titulo_album': 'folklore (deluxe version)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'CANCELLED!',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Wood',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'The Life of a Showgirl',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Wi$h Li$t',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)",
  'titulo_album': "Red (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'I Can Do It With a Broken Heart',
  'titulo_album': 'THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'We Are Never Ever Getting Back Together',
  'titulo_album': 'Red (Deluxe Edition)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Don’t Blame Me',
  'titulo_album': 'reputation',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "All Too Well (Taylor's Version)",
  'titulo_album': "Red (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "Blank Space (Taylor's Version)",
  'titulo_album': "1989 (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "Red (Taylor's Version)",
  'titulo_album': "Red (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'You Need To Calm Down',
  'titulo_album': 'Lover',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Fortnight',
  'titulo_album': 'THE TORTURED POETS DEPARTMENT',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'august',
  'titulo_album': 'folklore (deluxe version)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "I Knew You Were Trouble (Taylor's Version)",
  'titulo_album': "Red (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Love Story',
  'titulo_album': 'Fearless (International Version)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'I Don’t Wanna Live Forever (Fifty Shades Darker)',
  'titulo_album': 'reputation Stadium Tour Surprise Song Playlist',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Look What You Made Me Do',
  'titulo_album': 'reputation',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'You Belong With Me (Taylor’s Version)',
  'titulo_album': "Fearless (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'End Game',
  'titulo_album': 'reputation',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'So High School',
  'titulo_album': 'THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Miss Americana & The Heartbreak Prince',
  'titulo_album': 'Lover',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "Bad Blood (Taylor's Version)",
  'titulo_album': "1989 (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Delicate',
  'titulo_album': 'reputation',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Opalite (Ely Oaks Remix)',
  'titulo_album': 'Opalite (Ely Oaks Remix)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Honey',
  'titulo_album': 'The Life of a Showgirl',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': "Enchanted (Taylor's Version)",
  'titulo_album': "Speak Now (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Love Story (Taylor’s Version)',
  'titulo_album': "Fearless (Taylor's Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Karma',
  'titulo_album': 'Midnights (3am Edition)',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'Bejeweled',
  'titulo_album': 'Midnights',
  'tipo_cancion': 'track'},
 {'id_artista': 12246,
  'nombre_artista': 'Taylor Swift',
  'titulo_cancion': 'loml',
  'titulo_album': 'THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'One Dance',
  'titulo_album': 'Views',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Passionfruit',
  'titulo_album': 'More Life',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Hotline Bling',
  'titulo_album': 'Views',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'NOKIA',
  'titulo_album': '$ome $exy $ongs 4 U',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': "God's Plan",
  'titulo_album': 'Scorpion',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Nice For What',
  'titulo_album': 'Scorpion',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Teenage Fever',
  'titulo_album': 'More Life',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Fair Trade',
  'titulo_album': 'Certified Lover Boy',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'DIE TRYING',
  'titulo_album': '$ome $exy $ongs 4 U',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Toosie Slide',
  'titulo_album': 'Toosie Slide',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Laugh Now Cry Later',
  'titulo_album': 'Laugh Now Cry Later',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Massive',
  'titulo_album': 'Honestly, Nevermind',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'POPSTAR (feat. Drake)',
  'titulo_album': 'POPSTAR (feat. Drake)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Headlines (Explicit Version)',
  'titulo_album': 'Take Care (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Chicago Freestyle',
  'titulo_album': 'Dark Lane Demo Tapes',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'IDGAF',
  'titulo_album': 'For All The Dogs',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Yes Indeed',
  'titulo_album': 'Harder Than Ever',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Girls Want Girls',
  'titulo_album': 'Certified Lover Boy',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'She Will',
  'titulo_album': 'Tha Carter IV (Complete Edition)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Know Yourself',
  'titulo_album': "If You're Reading This It's Too Late",
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Not You Too',
  'titulo_album': 'Dark Lane Demo Tapes',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Money In The Grave',
  'titulo_album': 'The Best In The World Pack',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Yebba’s Heartbreak',
  'titulo_album': 'Certified Lover Boy',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Too Good',
  'titulo_album': 'Views',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'In My Feelings',
  'titulo_album': 'Scorpion',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Rich Baby Daddy',
  'titulo_album': 'For All The Dogs',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Jimmy Cooks',
  'titulo_album': 'Honestly, Nevermind',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'What Did I Miss?',
  'titulo_album': 'What Did I Miss?',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Trust Issues',
  'titulo_album': 'Care Package',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Crew Love',
  'titulo_album': 'Take Care (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': '9',
  'titulo_album': 'Views',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'First Person Shooter',
  'titulo_album': 'For All The Dogs',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Forever (Album Version Explicit)',
  'titulo_album': 'Relapse: Refill',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Which One',
  'titulo_album': 'Which One',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'GREECE (feat. Drake)',
  'titulo_album': 'GREECE (feat. Drake)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Shot For Me',
  'titulo_album': 'Take Care (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Don’t Matter To Me',
  'titulo_album': 'Scorpion',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Time Flies',
  'titulo_album': 'Dark Lane Demo Tapes',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'You Broke My Heart',
  'titulo_album': 'For All The Dogs Scary Hours Edition',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Marvins Room',
  'titulo_album': 'Take Care (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Take Care',
  'titulo_album': 'Take Care (Deluxe)',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Girls Need Love (Remix)',
  'titulo_album': 'Last Day Of Summer',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Jumpman',
  'titulo_album': 'What A Time To Be Alive',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Hours In Silence',
  'titulo_album': 'Her Loss',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Pipe Down',
  'titulo_album': 'Certified Lover Boy',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Feel No Ways',
  'titulo_album': 'Views',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Champagne Poetry',
  'titulo_album': 'Certified Lover Boy',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Shut It Down',
  'titulo_album': "Thank Me Later (Int'l Version)",
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': 'Way 2 Sexy',
  'titulo_album': 'Certified Lover Boy',
  'tipo_cancion': 'track'},
 {'id_artista': 246791,
  'nombre_artista': 'Drake',
  'titulo_cancion': "Flight's Booked",
  'titulo_album': 'Honestly, Nevermind',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'What I Want',
  'titulo_album': 'I’m The Problem',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Somebody’s Problem',
  'titulo_album': 'Dangerous: The Double Album (Bonus)',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'More Than My Hometown',
  'titulo_album': 'More Than My Hometown',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Graveyard Whistling',
  'titulo_album': 'Graveyard Whistling',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Wasted On You',
  'titulo_album': 'Dangerous: The Double Album',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': "Where'd That Girl Go",
  'titulo_album': 'I’m The Problem',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Falling Apart',
  'titulo_album': 'I’m The Problem',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': "I'm The Problem",
  'titulo_album': "I'm The Problem",
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Heartless',
  'titulo_album': 'Heartless',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': '7 Summers',
  'titulo_album': '7 Summers',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': '20 Cigarettes',
  'titulo_album': 'I’m The Problem',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Just In Case',
  'titulo_album': 'Just In Case',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Last Night',
  'titulo_album': 'One Thing At A Time',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': "I Ain't Comin' Back",
  'titulo_album': "I Ain't Comin' Back",
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Lies Lies Lies',
  'titulo_album': 'Lies Lies Lies',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Kick Myself',
  'titulo_album': 'I’m The Problem',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Smile',
  'titulo_album': 'Smile',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Thinkin’ Bout Me',
  'titulo_album': 'One Thing At A Time',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Whiskey Glasses',
  'titulo_album': 'If I Know Me',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Love Somebody',
  'titulo_album': 'Love Somebody',
  'tipo_cancion': 'track'},
 {'id_artista': 7188840,
  'nombre_artista': 'Morgan Wallen',
  'titulo_cancion': 'Me On Whiskey',
  'titulo_album': 'Dangerous: The Double Album',
  'tipo_cancion': 'track'},

In [11]:
print(datos_canciones)

{'data': [{'id': 3288087861, 'readable': True, 'title': 'blackout ?', 'title_short': 'blackout ?', 'title_version': '', 'link': 'https://www.deezer.com/track/3288087861', 'duration': 180, 'rank': 577836, 'explicit_lyrics': False, 'explicit_content_lyrics': 0, 'explicit_content_cover': 2, 'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3?hdnea=exp=1777458872~acl=/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3*~data=user_id=0,application_id=42~hmac=f2f3888cf17c6b87273f66add137f1ceddfef7b45f99b55dd2cc1cc3f41fe442', 'contributors': [{'id': 61094422, 'name': 'Emilia', 'link': 'https://www.deezer.com/artist/61094422', 'share': 'https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/61094422/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 2252591, 'name': 'TINI', 'link': 'https://www.deezer.com/artist/2252591', 'share': 'https://www.deezer.com/artist/2252591?utm_source=deezer&utm_content=artist-2252591&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/2252591/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2252591/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 13299379, 'name': 'Nicki Nicole', 'link': 'https://www.deezer.com/artist/13299379', 'share': 'https://www.deezer.com/artist/13299379?utm_source=deezer&utm_content=artist-13299379&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/13299379/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/13299379/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'md5_image': 'fee888110d29c7d8021275c36004961f', 'artist': {'id': 61094422, 'name': 'Emilia', 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist'}, 'album': {'id': 730638231, 'title': 'blackout ?', 'cover': 'https://api.deezer.com/album/730638231/image', 'cover_small': 'https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/56x56-000000-80-0-0.jpg', 'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/250x250-000000-80-0-0.jpg', 'cover_big': 'https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/500x500-000000-80-0-0.jpg', 'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/1000x1000-000000-80-0-0.jpg', 'md5_image': 'fee888110d29c7d8021275c36004961f', 'tracklist': 'https://api.deezer.com/album/730638231/tracks', 'type': 'album'}, 'type': 'track'}, {'id': 1825853207, 'readable': True, 'title': 'Quieres', 'title_short': 'Quieres', 'title_version': '', 'link': 'https://www.deezer.com/track/1825853207', 'duration': 213, 'rank': 504369, 'explicit_lyrics': False, 'explicit_content_lyrics': 0, 'explicit_content_cover': 0, 'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/b/6/f/0/b6f2f5af86e9dc60e6c5746cf04024aa.mp3?hdnea=exp=1777458872~acl=/api/1/1/b/6/f/0/b6f2f5af86e9dc60e6c5746cf04024aa.mp3*~data=user_id=0,application_id=42~hmac=a31b3826d8bc224819dc001c0ebd5a0f6afa0233442bf2aa8dea5faffaea4e12', 'contributors': [{'id': 11928391, 'name': 'Aitana', 'link': 'https://www.deezer.com/artist/11928391', 'share': 'https://www.deezer.com/artist/11928391?utm_source=deezer&utm_content=artist-11928391&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/11928391/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/11928391/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 61094422, 'name': 'Emilia', 'link': 'https://www.deezer.com/artist/61094422', 'share': 'https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/61094422/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 81719632, 'name': 'Ptazeta', 'link': 'https://www.deezer.com/artist/81719632', 'share': 'https://www.deezer.com/artist/81719632?utm_source=deezer&utm_content=artist-81719632&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/81719632/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d0bf43f1e03fb10cd4a390d0e02c6f0d/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/81719632/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'md5_image': '405226485b6c6bf695a2d5534be0cd89', 'artist': {'id': 11928391, 'name': 'Aitana', 'tracklist': 'https://api.deezer.com/artist/11928391/top?limit=50', 'type': 'artist'}, 'album': {'id': 336049067, 'title': 'Quieres', 'cover': 'https://api.deezer.com/album/336049067/image', 'cover_small': 'https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/56x56-000000-80-0-0.jpg', 'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/250x250-000000-80-0-0.jpg', 'cover_big': 'https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/500x500-000000-80-0-0.jpg', 'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/405226485b6c6bf695a2d5534be0cd89/1000x1000-000000-80-0-0.jpg', 'md5_image': '405226485b6c6bf695a2d5534be0cd89', 'tracklist': 'https://api.deezer.com/album/336049067/tracks', 'type': 'album'}, 'type': 'track'}, {'id': 3829132661, 'readable': True, 'title': 'JETSKI - Remix', 'title_short': 'JETSKI - Remix', 'title_version': '', 'link': 'https://www.deezer.com/track/3829132661', 'duration': 181, 'rank': 669671, 'explicit_lyrics': True, 'explicit_content_lyrics': 1, 'explicit_content_cover': 2, 'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/d/3/3/0/d33fe67da20e36deea296de834976f2f.mp3?hdnea=exp=1777458872~acl=/api/1/1/d/3/3/0/d33fe67da20e36deea296de834976f2f.mp3*~data=user_id=0,application_id=42~hmac=5ccfea9b8a76e7ddb61cbd0aed2e01ea6cb2290c37d05998048156311ad67e6b', 'contributors': [{'id': 50633822, 'name': 'PEDRO SAMPAIO', 'link': 'https://www.deezer.com/artist/50633822', 'share': 'https://www.deezer.com/artist/50633822?utm_source=deezer&utm_content=artist-50633822&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/50633822/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/706ab941f922fb5820680cdceb284862/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/50633822/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 61094422, 'name': 'Emilia', 'link': 'https://www.deezer.com/artist/61094422', 'share': 'https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/61094422/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 118232102, 'name': 'MC Meno K', 'link': 'https://www.deezer.com/artist/118232102', 'share': 'https://www.deezer.com/artist/118232102?utm_source=deezer&utm_content=artist-118232102&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/118232102/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d9d907601ec12d59082748c8f402d651/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/118232102/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 123505, 'name': 'Melody', 'link': 'https://www.deezer.com/artist/123505', 'share': 'https://www.deezer.com/artist/123505?utm_source=deezer&utm_content=artist-123505&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/123505/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/f0f68980e8ac40edfb75d558a4430e17/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/123505/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'md5_image': '811342cf7292c03bf399b208523a2334', 'artist': {'id': 50633822, 'name': 'PEDRO SAMPAIO', 'tracklist': 'https://api.deezer.com/artist/50633822/top?limit=50', 'type': 'artist'}, 'album': {'id': 913604051, 'title': 'JETSKI - Remix', 'cover': 'https://api.deezer.com/album/913604051/image', 'cover_small': 'https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/56x56-000000-80-0-0.jpg', 'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/250x250-000000-80-0-0.jpg', 'cover_big': 'https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/500x500-000000-80-0-0.jpg', 'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/811342cf7292c03bf399b208523a2334/1000x1000-000000-80-0-0.jpg', 'md5_image': '811342cf7292c03bf399b208523a2334', 'tracklist': 'https://api.deezer.com/album/913604051/tracks', 'type': 'album'}, 'type': 'track'}, {'id': 2498029491, 'readable': True, 'title': 'La_Original.mp3', 'title_short': 'La_Original.mp3', 'title_version': '', 'link': 'https://www.deezer.com/track/2498029491', 'duration': 140, 'rank': 541606, 'explicit_lyrics': False, 'explicit_content_lyrics': 0, 'explicit_content_cover': 2, 'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3?hdnea=exp=1777458872~acl=/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3*~data=user_id=0,application_id=42~hmac=a2e628e90e906ccf90790c25b67d86349521ff346286c7bbb65c57ca2a9d2e81', 'contributors': [{'id': 61094422, 'name': 'Emilia', 'link': 'https://www.deezer.com/artist/61094422', 'share': 'https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/61094422/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 2252591, 'name': 'TINI', 'link': 'https://www.deezer.com/artist/2252591', 'share': 'https://www.deezer.com/artist/2252591?utm_source=deezer&utm_content=artist-2252591&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/2252591/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2252591/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'md5_image': '1eb3b9ecd27cd1be09d01cc8ff513ecb', 'artist': {'id': 61094422, 'name': 'Emilia', 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist'}, 'album': {'id': 499990281, 'title': 'La_Original.mp3', 'cover': 'https://api.deezer.com/album/499990281/image', 'cover_small': 'https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/56x56-000000-80-0-0.jpg', 'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/250x250-000000-80-0-0.jpg', 'cover_big': 'https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/500x500-000000-80-0-0.jpg', 'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/1000x1000-000000-80-0-0.jpg', 'md5_image': '1eb3b9ecd27cd1be09d01cc8ff513ecb', 'tracklist': 'https://api.deezer.com/album/499990281/tracks', 'type': 'album'}, 'type': 'track'}, {'id': 2246628067, 'readable': True, 'title': 'No_se_ve.mp3', 'title_short': 'No_se_ve.mp3', 'title_version': '', 'link': 'https://www.deezer.com/track/2246628067', 'duration': 203, 'rank': 509130, 'explicit_lyrics': True, 'explicit_content_lyrics': 1, 'explicit_content_cover': 2, 'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/d/d/7/0/dd72b964bc2892882f6d0aef8cd23b45.mp3?hdnea=exp=1777458872~acl=/api/1/1/d/d/7/0/dd72b964bc2892882f6d0aef8cd23b45.mp3*~data=user_id=0,application_id=42~hmac=15ff9d040d7eaea4023b7b12caca6bd75780396bd54e49d8f909edc22af900e6', 'contributors': [{'id': 61094422, 'name': 'Emilia', 'link': 'https://www.deezer.com/artist/61094422', 'share': 'https://www.deezer.com/artist/61094422?utm_source=deezer&utm_content=artist-61094422&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/61094422/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 73396, 'name': 'LUDMILLA', 'link': 'https://www.deezer.com/artist/73396', 'share': 'https://www.deezer.com/artist/73396?utm_source=deezer&utm_content=artist-73396&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/73396/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/55ecebdb6fdb2a1a97fff0e9d1ceed70/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/55ecebdb6fdb2a1a97fff0e9d1ceed70/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/55ecebdb6fdb2a1a97fff0e9d1ceed70/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/55ecebdb6fdb2a1a97fff0e9d1ceed70/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/73396/top?limit=50', 'type': 'artist', 'role': 'Main'}, {'id': 5487863, 'name': 'Zecca', 'link': 'https://www.deezer.com/artist/5487863', 'share': 'https://www.deezer.com/artist/5487863?utm_source=deezer&utm_content=artist-5487863&utm_term=0_1777457972&utm_medium=web', 'picture': 'https://api.deezer.com/artist/5487863/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5ac74bb86b7c0e7ace7e85dc4ad744f9/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5ac74bb86b7c0e7ace7e85dc4ad744f9/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5ac74bb86b7c0e7ace7e85dc4ad744f9/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5ac74bb86b7c0e7ace7e85dc4ad744f9/1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5487863/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'md5_image': '5ac74bb86b7c0e7ace7e85dc4ad744f9', 'artist': {'id': 61094422, 'name': 'Emilia', 'tracklist': 'https://api.deezer.com/artist/61094422/top?limit=50', 'type': 'artist'}, 'album': {'id': 432024467, 'title': 'No_se_ve.mp3', 'cover': 'https://api.deezer.com/album/4

In [12]:
df_canciones = pd.DataFrame(canciones)
df_canciones.head()

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo_cancion
0,12246,Taylor Swift,The Fate of Ophelia,The Life of a Showgirl,track
1,12246,Taylor Swift,Opalite,The Life of a Showgirl,track
2,12246,Taylor Swift,Elizabeth Taylor,The Life of a Showgirl,track
3,12246,Taylor Swift,Blank Space,1989 (Deluxe),track
4,12246,Taylor Swift,Out Of The Woods (Taylor's Version),1989 (Taylor's Version),track

In [13]:
df_canciones = pd.DataFrame(canciones)
df_canciones.head(60)

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo_cancion
0,12246,Taylor Swift,The Fate of Ophelia,The Life of a Showgirl,track
1,12246,Taylor Swift,Opalite,The Life of a Showgirl,track
2,12246,Taylor Swift,Elizabeth Taylor,The Life of a Showgirl,track
3,12246,Taylor Swift,Blank Space,1989 (Deluxe),track
4,12246,Taylor Swift,Out Of The Woods (Taylor's Version),1989 (Taylor's Version),track
5,12246,Taylor Swift,Shake It Off,1989 (Deluxe),track
6,12246,Taylor Swift,Eldest Daughter,The Life of a Showgirl,track
7,12246,Taylor Swift,cardigan,folklore,track
8,12246,Taylor Swift,Cruel Summer,Lover,track
9,12246,Taylor Swift,Father Figure,The Life of a Showgirl,track
10,12246,Taylor Swift,Wildest Dreams,1989 (Deluxe),track
11,12246,Taylor Swift,Style,1989 (Deluxe),track
12,12246,Taylor Swift,Actually Romantic,The Life of a Showgirl,track
13,12246,Taylor Swift,Anti-Hero,Midnights,track
14,12246,Taylor Swift,Daylight,Lover,track
15,12246,Taylor Swift,Anti-Hero (Acoustic Version),Anti-Hero (Acoustic Version),track
16,12246,Taylor Swift,exile,folklore (deluxe version),track
17,12246,Taylor Swift,Ruin The Friendship,The Life of a Showgirl,track
18,12246,Taylor Swift,my tears ricochet,folklore (deluxe version),track
19,12246,Taylor Swift,CANCELLED!,The Life of a Showgirl,track
20,12246,Taylor Swift,Wood,The Life of a Showgirl,track
21,12246,Taylor Swift,The Life of a Showgirl,The Life of a Showgirl,track
22,12246,Taylor Swift,Wi$h Li$t,The Life of a Showgirl,track
23,12246,Taylor Swift,All Too Well (10 Minute Version) (Taylor's Ver...,Red (Taylor's Version),track
24,12246,Taylor Swift,I Can Do It With a Broken Heart,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,track
25,12246,Taylor Swift,We Are Never Ever Getting Back Together,Red (Deluxe Edition),track
26,12246,Taylor Swift,Don’t Blame Me,reputation,track
27,12246,Taylor Swift,All Too Well (Taylor's Version),Red (Taylor's Version),track
28,12246,Taylor Swift,Blank Space (Taylor's Version),1989 (Taylor's Version),track
29,12246,Taylor Swift,Red (Taylor's Version),Red (Taylor's Version),track
30,12246,Taylor Swift,You Need To Calm Down,Lover,track
31,12246,Taylor Swift,Fortnight,THE TORTURED POETS DEPARTMENT,track
32,12246,Taylor Swift,august,folklore (deluxe version),track
33,12246,Taylor Swift,I Knew You Were Trouble (Taylor's Version),Red (Taylor's Version),track
34,12246,Taylor Swift,Love Story,Fearless (International Version),track
35,12246,Taylor Swift,I Don’t Wanna Live Forever (Fifty Shades Darker),reputation Stadium Tour Surprise Song Playlist,track
36,12246,Taylor Swift,Look What You Made Me Do,reputation,track
37,12246,Taylor Swift,You Belong With Me (Taylor’s Version),Fearless (Taylor's Version),track
38,12246,Taylor Swift,End Game,reputation,track
39,12246,Taylor Swift,So High School,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,track
40,12246,Taylor Swift,Miss Americana & The Heartbreak Prince,Lover,track
41,12246,Taylor Swift,Bad Blood (Taylor's Version),1989 (Taylor's Version),track
42,12246,Taylor Swift,Delicate,reputation,track
43,12246,Taylor Swift,Opalite (Ely Oaks Remix),Opalite (Ely Oaks Remix),track
44,12246,Taylor Swift,Honey,The Life of a Showgirl,track
45,12246,Taylor Swift,Enchanted (Taylor's Version),Speak Now (Taylor's Version),track
46,12246,Taylor Swift,Love Story (Taylor’s Version),Fearless (Taylor's Version),track
47,12246,Taylor Swift,Karma,Midnights (3am Edition),track
48,12246,Taylor Swift,Bejeweled,Midnights,track
49,12246,Taylor Swift,loml,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,track
50,246791,Drake,One Dance,Views,track
51,246791,Drake,Passionfruit,More Life,track
52,246791,Drake,Hotline Bling,Views,track
53,246791,Drake,NOKIA,$ome $exy $ongs 4 U,track
54,246791,Drake,God's Plan,Scorpion,track
55,246791,Drake,Nice For What,Scorpion,track
56,246791,Drake,Teenage Fever,More Life,track
57,246791,Drake,Fair Trade,Certified Lover Boy,track
58,246791,Drake,DIE TRYING,$ome $exy $ongs 4 U,track
59,246791,Drake,Toosie Slide,Toosie Slide,track

In [14]:
df_canciones["nombre_artista"].value_counts()

nombre_artista
Taylor Swift          50
Drake                 50
Morgan Wallen         50
Kendrick Lamar        50
The Weeknd            50
SZA                   50
Zach Bryan            50
Tyler, The Creator    50
Billie Eilish         50
Ariana Grande         50
Bad Bunny             50
KAROL G               50
Myke Towers           50
Quevedo               50
Aitana                50
ROSALÍA               50
Morad                 50
Melendi               50
Enrique Iglesias      50
Juanes                50
DUKI                  50
Maria Becerra         50
TINI                  50
Nicki Nicole          50
Cazzu                 50
Lali                  50
Paulo Londra          50
Shakira               50
Bizarrap              50
Emilia                50
Name: count, dtype: int64

In [15]:
df_canciones

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo_cancion
0,12246,Taylor Swift,The Fate of Ophelia,The Life of a Showgirl,track
1,12246,Taylor Swift,Opalite,The Life of a Showgirl,track
2,12246,Taylor Swift,Elizabeth Taylor,The Life of a Showgirl,track
3,12246,Taylor Swift,Blank Space,1989 (Deluxe),track
4,12246,Taylor Swift,Out Of The Woods (Taylor's Version),1989 (Taylor's Version),track
...,...,...,...,...,...
1495,61094422,Emilia,Uno los Dos,Uno los Dos,track
1496,61094422,Emilia,Diva (feat. Emilia),Diva (feat. Emilia),track
1497,61094422,Emilia,Guerrero.mp3,Guerrero.mp3,track
1498,61094422,Emilia,Somos Más,Somos Más,track
1499,61094422,Emilia,Maldita Noche En Vivo,Maldita Noche,track

In [16]:
df_canciones.to_excel("canciones.xlsx", index=False)