## Extracción de Datos - API Deezer

#### Librerías

In [22]:
import requests
import time
import pandas as pd
import json

#### Lista de 30 artistas populares (Argentina, España y EEUU)

In [2]:
lista_artistas=[
 
    # 🇺🇸 EEUU (10)
    "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
 
    # 🇪🇸 España (10)
    "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
    "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
 
    # 🇦🇷 Argentina (10)
    "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
    "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
]
 
print(f"Total: {len(lista_artistas)} artistas ✅")

Total: 30 artistas ✅

#### Consulta de artistas en Deezer API - se limita a 1 por existir duplicidad de ID's - RUTA:SEARCH

In [3]:
lista_artistas=[
 
    # 🇺🇸 EEUU (10)
    "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
    "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
 
    # 🇪🇸 España (10)
    "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
    "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
 
    # 🇦🇷 Argentina (10)
    "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
    "Lali", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
]

artista_search=[]

for artista in lista_artistas:
    consulta=requests.get(f"https://api.deezer.com/search/artist?q={artista}&index=0&limit=1")
    consulta.status_code

    if consulta.status_code != 200:
        print(f"No se pudo realizar la consulta del artista: {artista}.\n Error : {consulta.status_code}") 

    datos=consulta.json()
    artista_search.append(datos['data'][0])

print(artista_search)

[{'id': 12246, 'name': 'Taylor Swift', 'link': 'https://www.deezer.com/artist/12246', 'picture': 'https://api.deezer.com/artist/12246/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/1000x1000-000000-80-0-0.jpg', 'nb_album': 124, 'nb_fan': 12524357, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12246/top?limit=50', 'type': 'artist'}, {'id': 246791, 'name': 'Drake', 'link': 'https://www.deezer.com/artist/246791', 'picture': 'https://api.deezer.com/artist/246791/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/1000x1000-000000-80-0-0.jpg', 'nb_album': 76, 'nb_fan': 23932673, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/246791/top?limit=50', 'type': 'artist'}, {'id': 386950521, 'name': 'Morgan Wallen', 'link': 'https://www.deezer.com/artist/386950521', 'picture': 'https://api.deezer.com/artist/386950521/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/1000x1000-000000-80-0-0.jpg', 'nb_album': 1, 'nb_fan': 8, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/386950521/top?limit=50', 'type': 'artist'}, {'id': 525046, 'name': 'Kendrick Lamar', 'link': 'https://www.deezer.com/artist/525046', 'picture': 'https://api.deezer.com/artist/525046/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg', 'nb_album': 40, 'nb_fan': 6080071, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/525046/top?limit=50', 'type': 'artist'}, {'id': 4050205, 'name': 'The Weeknd', 'link': 'https://www.deezer.com/artist/4050205', 'picture': 'https://api.deezer.com/artist/4050205/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg', 'nb_album': 86, 'nb_fan': 14424575, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4050205/top?limit=50', 'type': 'artist'}, {'id': 5531258, 'name': 'SZA', 'link': 'https://www.deezer.com/artist/5531258', 'picture': 'https://api.deezer.com/artist/5531258/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg', 'nb_album': 40, 'nb_fan': 1283376, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5531258/top?limit=50', 'type': 'artist'}, {'id': 71855892, 'name': 'Zach Bryan', 'link': 'https://www.deezer.com/artist/71855892', 'picture': 'https://api.deezer.com/artist/71855892/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/1000x1000-000000-80-0-0.jpg', 'nb_album': 38, 'nb_fan': 112680, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/71855892/top?limit=50', 'type': 'artist'}, {'id': 1194083, 'name': 'Tyler, The Creator', 'link': 'https://www.deezer.com/artist/1194083', 'picture': 'https://api.deezer.com/artist/1194083/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/1000x1000-000000-80-0-0.jpg', 'nb_album': 29, 'nb_fan': 1323769, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/1194083/top?limit=50', 'type': 'artist'}, {'id': 9635624, 'name': 'Billie Eilish', 'link': 'https://www.deezer.com/artist/9635624', 'picture': 'https://api.deezer.com/artist/9635624/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg', 'nb_album': 32, 'nb_fan': 9112255, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/9635624/top?limit=50', 'type': 'artist'}, {'id': 1562681, 'name': 'Ariana Grande', 'link': 'https://www.deezer.com/artist/1562681', 'picture': 'https://api.deezer.com/artist/1562681/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/1000x1000-000000-80-0-0.jpg', 'nb_album': 69, 'nb_fan': 13300406, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/1562681/top?limit=50', 'type': 'artist'}, {'id': 10583405, 'name': 'Bad Bunny', 'link': 'https://www.deezer.com/artist/10583405', 'picture': 'https://api.deezer.com/artist/10583405/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/1000x1000-000000-80-0-0.jpg', 'nb_album': 89, 'nb_fan': 7736342, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/10583405/top?limit=50', 'type': 'artist'}, {'id': 5297021, 'name': 'KAROL G', 'link': 'https://www.deezer.com/artist/5297021', 'picture': 'https://api.deezer.com/artist/5297021/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/1000x1000-000000-80-0-0.jpg', 'nb_album': 74, 'nb_fan': 3357675, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5297021/top?limit=50', 'type': 'artist'}, {'id': 12029862, 'name': 'Myke Towers', 'link': 'https://www.deezer.com/artist/12029862', 'picture': 'https://api.deezer.com/artist/12029862/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/1000x1000-000000-80-0-0.jpg', 'nb_album': 177, 'nb_fan': 1678981, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12029862/top?limit=50', 'type': 'artist'}, {'id': 6705223, 'name': 'Quevedo', 'link': 'https://www.deezer.com/artist/6705223', 'picture': 'https://api.deezer.com/artist/6705223/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/1000x1000-000000-80-0-0.jpg', 'nb_album': 104, 'nb_fan': 286505, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/6705223/top?limit=50', 'type': 'artist'}, {'id': 11928391, 'name': 'Aitana', 'link': 'https://www.deezer.com/artist/11928391', 'picture': 'https://api.deezer.com/artist/11928391/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg', 'nb_album': 58, 'nb_fan': 343355, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/11928391/top?limit=50', 'type': 'artist'}, {'id': 554792, 'name': 'ROSALÍA', 'link': 'https://www.deezer.com/artist/554792', 'picture': 'https://api.deezer.com/artist/554792/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/1000x1000-000000-80-0-0.jpg', 'nb_album': 37, 'nb_fan': 1022335, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/554792/top?limit=50', 'type': 'artist'}, {'id': 111130212, 'name': 'Morad', 'link': 'https://www.deezer.com/artist/111130212', 'picture': 'https://api.deezer.com/artist/111130212/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/1000x1000-000000-80-0-0.jpg', 'nb_album': 133, 'nb_fan': 321980, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/111130212/top?limit=50', 'type': 'artist'}, {'id': 2697, 'name': 'Melendi', 'link': 'https://www.deezer.com/artist/2697', 'picture': 'https://api.deezer.com/artist/2697/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/1000x1000-000000-80-0-0.jpg', 'nb_album': 72, 'nb_fan': 609142, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2697/top?limit=50', 'type': 'artist'}, {'id': 2792, 'name': 'Enrique Iglesias', 'link': 'https://www.deezer.com/artist/2792', 'picture': 'https://api.deezer.com/artist/2792/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/1000x1000-000000-80-0-0.jpg', 'nb_album': 106, 'nb_fan': 5940601, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2792/top?limit=50', 'type': 'artist'}, {'id': 70, 'name': 'Juanes', 'link': 'https://www.deezer.com/artist/70', 'picture': 'https://api.deezer.com/artist/70/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/1000x1000-000000-80-0-0.jpg', 'nb_album': 114, 'nb_fan': 1618006, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/70/top?limit=50', 'type': 'artist'}, {'id': 4902904, 'name': 'DUKI', 'link': 'https://www.deezer.com/artist/4902904', 'picture': 'https://api.deezer.com/artist/4902904/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/1000x1000-000000-80-0-0.jpg', 'nb_album': 155, 'nb_fan': 817502, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/4902904/top?limit=50', 'type': 'artist'}, {'id': 14343187, 'name': 'Maria Becerra', 'link': 'https://www.deezer.com/artist/14343187', 'picture': 'https://api.deezer.com/artist/14343187/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/1000x1000-000000-80-0-0.jpg', 'nb_album': 75, 'nb_fan': 375244, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/14343187/top?limit=50', 'type': 'artist'}, {'id': 2252591, 'name': 'TINI', 'link': 'https://www.deezer.com/artist/2252591', 'picture': 'https://api.deezer.com/artist/2252591/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg', 'nb_album': 79, 'nb_fan': 905169, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/2252591/top?limit=50', 'type': 'artist'}, {'id': 13299379, 'name': 'Nicki Nicole', 'link': 'https://www.deezer.com/artist/13299379', 'picture': 'https://api.deezer.com/artist/13299379/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg', 'nb_album': 64, 'nb_fan': 605576, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/13299379/top?limit=50', 'type': 'artist'}, {'id': 12268072, 'name': 'Cazzu', 'link': 'https://www.deezer.com/artist/12268072', 'picture': 'https://api.deezer.com/artist/12268072/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/1000x1000-000000-80-0-0.jpg', 'nb_album': 56, 'nb_fan': 599001, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/12268072/top?limit=50', 'type': 'artist'}, {'id': 5181388, 'name': 'Lali', 'link': 'https://www.deezer.com/artist/5181388', 'picture': 'https://api.deezer.com/artist/5181388/image', 'picture_small': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/56x56-000000-80-0-0.jpg', 'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/250x250-000000-80-0-0.jpg', 'picture_big': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/500x500-000000-80-0-0.jpg', 'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/bd8e25ceb6992963bb366e84d70518a8/1000x1000-000000-80-0-0.jpg', 'nb_album': 44, 'nb_fan': 48359, 'radio': True, 'tracklist': 'https://api.deezer.com/artist/5181388/top?limit=50', 'type': 'artist'}, {'id': 12637039, 'name': 'Paulo Londra', 'link': 'https://www.deezer.com/artist/12637039', 'picture': 'https://api.deezer.com/artist/12637039/image', 'picture_smal

In [4]:
len(artista_search)

30

In [5]:
import json
print(json.dumps(artista_search, indent=2, ensure_ascii=False))     # para ver estructura

[
  {
    "id": 12246,
    "name": "Taylor Swift",
    "link": "https://www.deezer.com/artist/12246",
    "picture": "https://api.deezer.com/artist/12246/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/e528e270424103b527f8a27ac625563b/1000x1000-000000-80-0-0.jpg",
    "nb_album": 124,
    "nb_fan": 12524357,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/12246/top?limit=50",
    "type": "artist"
  },
  {
    "id": 246791,
    "name": "Drake",
    "link": "https://www.deezer.com/artist/246791",
    "picture": "https://api.deezer.com/artist/246791/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/5d2fa7f140a6bdc2c864c3465a61fc71/1000x1000-000000-80-0-0.jpg",
    "nb_album": 76,
    "nb_fan": 23932673,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/246791/top?limit=50",
    "type": "artist"
  },
  {
    "id": 386950521,
    "name": "Morgan Wallen",
    "link": "https://www.deezer.com/artist/386950521",
    "picture": "https://api.deezer.com/artist/386950521/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/6f8a203c41b9341a87fc0b4d86b9de5c/1000x1000-000000-80-0-0.jpg",
    "nb_album": 1,
    "nb_fan": 8,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/386950521/top?limit=50",
    "type": "artist"
  },
  {
    "id": 525046,
    "name": "Kendrick Lamar",
    "link": "https://www.deezer.com/artist/525046",
    "picture": "https://api.deezer.com/artist/525046/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg",
    "nb_album": 40,
    "nb_fan": 6080071,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/525046/top?limit=50",
    "type": "artist"
  },
  {
    "id": 4050205,
    "name": "The Weeknd",
    "link": "https://www.deezer.com/artist/4050205",
    "picture": "https://api.deezer.com/artist/4050205/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg",
    "nb_album": 86,
    "nb_fan": 14424575,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/4050205/top?limit=50",
    "type": "artist"
  },
  {
    "id": 5531258,
    "name": "SZA",
    "link": "https://www.deezer.com/artist/5531258",
    "picture": "https://api.deezer.com/artist/5531258/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg",
    "nb_album": 40,
    "nb_fan": 1283376,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/5531258/top?limit=50",
    "type": "artist"
  },
  {
    "id": 71855892,
    "name": "Zach Bryan",
    "link": "https://www.deezer.com/artist/71855892",
    "picture": "https://api.deezer.com/artist/71855892/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/552d448a0c2cb72f40c3de3a384949bd/1000x1000-000000-80-0-0.jpg",
    "nb_album": 38,
    "nb_fan": 112680,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/71855892/top?limit=50",
    "type": "artist"
  },
  {
    "id": 1194083,
    "name": "Tyler, The Creator",
    "link": "https://www.deezer.com/artist/1194083",
    "picture": "https://api.deezer.com/artist/1194083/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/5eceecd683beab6dd901a7931294a121/1000x1000-000000-80-0-0.jpg",
    "nb_album": 29,
    "nb_fan": 1323769,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/1194083/top?limit=50",
    "type": "artist"
  },
  {
    "id": 9635624,
    "name": "Billie Eilish",
    "link": "https://www.deezer.com/artist/9635624",
    "picture": "https://api.deezer.com/artist/9635624/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg",
    "nb_album": 32,
    "nb_fan": 9112255,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/9635624/top?limit=50",
    "type": "artist"
  },
  {
    "id": 1562681,
    "name": "Ariana Grande",
    "link": "https://www.deezer.com/artist/1562681",
    "picture": "https://api.deezer.com/artist/1562681/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/5fcde7fde7cde95fc36d4576afcfb49f/1000x1000-000000-80-0-0.jpg",
    "nb_album": 69,
    "nb_fan": 13300406,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/1562681/top?limit=50",
    "type": "artist"
  },
  {
    "id": 10583405,
    "name": "Bad Bunny",
    "link": "https://www.deezer.com/artist/10583405",
    "picture": "https://api.deezer.com/artist/10583405/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/45aaf836629158d714432ae37e552ee7/1000x1000-000000-80-0-0.jpg",
    "nb_album": 89,
    "nb_fan": 7736342,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/10583405/top?limit=50",
    "type": "artist"
  },
  {
    "id": 5297021,
    "name": "KAROL G",
    "link": "https://www.deezer.com/artist/5297021",
    "picture": "https://api.deezer.com/artist/5297021/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/dd8c6b3068d2761955eb6e432046ed91/1000x1000-000000-80-0-0.jpg",
    "nb_album": 74,
    "nb_fan": 3357675,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/5297021/top?limit=50",
    "type": "artist"
  },
  {
    "id": 12029862,
    "name": "Myke Towers",
    "link": "https://www.deezer.com/artist/12029862",
    "picture": "https://api.deezer.com/artist/12029862/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/d3a7418b4e44bf8ee3ae268067a86f09/1000x1000-000000-80-0-0.jpg",
    "nb_album": 177,
    "nb_fan": 1678981,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/12029862/top?limit=50",
    "type": "artist"
  },
  {
    "id": 6705223,
    "name": "Quevedo",
    "link": "https://www.deezer.com/artist/6705223",
    "picture": "https://api.deezer.com/artist/6705223/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/79880cc1b999b15567e332203464c34e/1000x1000-000000-80-0-0.jpg",
    "nb_album": 104,
    "nb_fan": 286505,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/6705223/top?limit=50",
    "type": "artist"
  },
  {
    "id": 11928391,
    "name": "Aitana",
    "link": "https://www.deezer.com/artist/11928391",
    "picture": "https://api.deezer.com/artist/11928391/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/41a75229e7fb63066c6b8be08ff0dbce/1000x1000-000000-80-0-0.jpg",
    "nb_album": 58,
    "nb_fan": 343355,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/11928391/top?limit=50",
    "type": "artist"
  },
  {
    "id": 554792,
    "name": "ROSALÍA",
    "link": "https://www.deezer.com/artist/554792",
    "picture": "https://api.deezer.com/artist/554792/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/96636156440182f1e7db3f77d39e6545/1000x1000-000000-80-0-0.jpg",
    "nb_album": 37,
    "nb_fan": 1022335,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/554792/top?limit=50",
    "type": "artist"
  },
  {
    "id": 111130212,
    "name": "Morad",
    "link": "https://www.deezer.com/artist/111130212",
    "picture": "https://api.deezer.com/artist/111130212/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/4c4e5e8049c0d7ff36e9fb8924dff724/1000x1000-000000-80-0-0.jpg",
    "nb_album": 133,
    "nb_fan": 321980,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/111130212/top?limit=50",
    "type": "artist"
  },
  {
    "id": 2697,
    "name": "Melendi",
    "link": "https://www.deezer.com/artist/2697",
    "picture": "https://api.deezer.com/artist/2697/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/d0690174df6f9017f7e945cfb8c228d8/1000x1000-000000-80-0-0.jpg",
    "nb_album": 72,
    "nb_fan": 609142,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/2697/top?limit=50",
    "type": "artist"
  },
  {
    "id": 2792,
    "name": "Enrique Iglesias",
    "link": "https://www.deezer.com/artist/2792",
    "picture": "https://api.deezer.com/artist/2792/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/7c0f867fb50b6c9302f991521e42e764/1000x1000-000000-80-0-0.jpg",
    "nb_album": 106,
    "nb_fan": 5940601,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/2792/top?limit=50",
    "type": "artist"
  },
  {
    "id": 70,
    "name": "Juanes",
    "link": "https://www.deezer.com/artist/70",
    "picture": "https://api.deezer.com/artist/70/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bdc812bc942510433031868a1088d732/1000x1000-000000-80-0-0.jpg",
    "nb_album": 114,
    "nb_fan": 1618006,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/70/top?limit=50",
    "type": "artist"
  },
  {
    "id": 4902904,
    "name": "DUKI",
    "link": "https://www.deezer.com/artist/4902904",
    "picture": "https://api.deezer.com/artist/4902904/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/795d09a17bc833425e4b88639bb931af/1000x1000-000000-80-0-0.jpg",
    "nb_album": 155,
    "nb_fan": 817502,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/4902904/top?limit=50",
    "type": "artist"
  },
  {
    "id": 14343187,
    "name": "Maria Becerra",
    "link": "https://www.deezer.com/artist/14343187",
    "picture": "https://api.deezer.com/artist/14343187/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/022b53ec2020238407549a708e068e86/1000x1000-000000-80-0-0.jpg",
    "nb_album": 75,
    "nb_fan": 375244,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/14343187/top?limit=50",
    "type": "artist"
  },
  {
    "id": 2252591,
    "name": "TINI",
    "link": "https://www.deezer.com/artist/2252591",
    "picture": "https://api.deezer.com/artist/2252591/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
    "nb_album": 79,
    "nb_fan": 905169,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
    "type": "artist"
  },
  {
    "id": 13299379,
    "name": "Nicki Nicole",
    "link": "https://www.deezer.com/artist/13299379",
    "picture": "https://api.deezer.com/artist/13299379/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/56x56-000000-80-0-0.jpg",
    "picture_medium": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/250x250-000000-80-0-0.jpg",
    "picture_big": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/500x500-000000-80-0-0.jpg",
    "picture_xl": "https://cdn-images.dzcdn.net/images/artist/7b4261dc1d0a02c4437d8cd418bea481/1000x1000-000000-80-0-0.jpg",
    "nb_album": 64,
    "nb_fan": 605576,
    "radio": true,
    "tracklist": "https://api.deezer.com/artist/13299379/top?limit=50",
    "type": "artist"
  },
  {
    "id": 12268072,
    "name": "Cazzu",
    "link": "https://www.deezer.com/artist/12268072",
    "picture": "https://api.deezer.com/artist/12268072/image",
    "picture_small": "https://cdn-images.dzcdn.net/images/artist/d4cb1c4b1f2524bbf40b0fa98c77e055/56x56-000000-80-0-0.jpg",

#### Subsanación de Listado de ID's

In [47]:
lista_id=[]
for d in artista_search:
    lista_id.append(d['id'])
    lista_id.append(d['name'])
print(lista_id)

[12246, 'Taylor Swift', 246791, 'Drake', 386950521, 'Morgan Wallen', 525046, 'Kendrick Lamar', 4050205, 'The Weeknd', 5531258, 'SZA', 71855892, 'Zach Bryan', 1194083, 'Tyler, The Creator', 9635624, 'Billie Eilish', 1562681, 'Ariana Grande', 10583405, 'Bad Bunny', 5297021, 'KAROL G', 12029862, 'Myke Towers', 6705223, 'Quevedo', 11928391, 'Aitana', 554792, 'ROSALÍA', 111130212, 'Morad', 2697, 'Melendi', 2792, 'Enrique Iglesias', 70, 'Juanes', 4902904, 'DUKI', 14343187, 'Maria Becerra', 2252591, 'TINI', 13299379, 'Nicki Nicole', 12268072, 'Cazzu', 5181388, 'Lali', 12637039, 'Paulo Londra', 267400032, 'Shakira', 12487862, 'Bizarrap', 61094422, 'Emilia']

##### Se observan ID incorrectos en la API debido a la generación de nuevos perfiles (la API permite adeicionalmente las acciones de PUSH/DELETE).
##### Se corrigen los ID de Shakira '267400032' se reemplaza por '160' y ID  de Morgan Wallen '386950521' por '7188840'.

In [102]:
artistas_info = []
for artista in artista_search:
    artistas_info.append({"id_artista": artista["id"], "nombre_artista":artista["name"]})
    for artista in artistas_info:     
        if artista["nombre_artista"] == "Morgan Wallen":         
            artista["id_artista"] = 7188840
        if artista["nombre_artista"] == "Shakira":         
            artista["id_artista"] = 160

artistas_info

[{'id_artista': 12246, 'nombre_artista': 'Taylor Swift'},
 {'id_artista': 246791, 'nombre_artista': 'Drake'},
 {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen'},
 {'id_artista': 525046, 'nombre_artista': 'Kendrick Lamar'},
 {'id_artista': 4050205, 'nombre_artista': 'The Weeknd'},
 {'id_artista': 5531258, 'nombre_artista': 'SZA'},
 {'id_artista': 71855892, 'nombre_artista': 'Zach Bryan'},
 {'id_artista': 1194083, 'nombre_artista': 'Tyler, The Creator'},
 {'id_artista': 9635624, 'nombre_artista': 'Billie Eilish'},
 {'id_artista': 1562681, 'nombre_artista': 'Ariana Grande'},
 {'id_artista': 10583405, 'nombre_artista': 'Bad Bunny'},
 {'id_artista': 5297021, 'nombre_artista': 'KAROL G'},
 {'id_artista': 12029862, 'nombre_artista': 'Myke Towers'},
 {'id_artista': 6705223, 'nombre_artista': 'Quevedo'},
 {'id_artista': 11928391, 'nombre_artista': 'Aitana'},
 {'id_artista': 554792, 'nombre_artista': 'ROSALÍA'},
 {'id_artista': 111130212, 'nombre_artista': 'Morad'},
 {'id_artista': 2697, 'nombre_artista': 'Melendi'},
 {'id_artista': 2792, 'nombre_artista': 'Enrique Iglesias'},
 {'id_artista': 70, 'nombre_artista': 'Juanes'},
 {'id_artista': 4902904, 'nombre_artista': 'DUKI'},
 {'id_artista': 14343187, 'nombre_artista': 'Maria Becerra'},
 {'id_artista': 2252591, 'nombre_artista': 'TINI'},
 {'id_artista': 13299379, 'nombre_artista': 'Nicki Nicole'},
 {'id_artista': 12268072, 'nombre_artista': 'Cazzu'},
 {'id_artista': 5181388, 'nombre_artista': 'Lali'},
 {'id_artista': 12637039, 'nombre_artista': 'Paulo Londra'},
 {'id_artista': 160, 'nombre_artista': 'Shakira'},
 {'id_artista': 12487862, 'nombre_artista': 'Bizarrap'},
 {'id_artista': 61094422, 'nombre_artista': 'Emilia'}]

### Consulta de tracks (2 resultados incompletos Taylor S y TINI)

In [23]:
import requests
import time

def consulta_tracks(limit_por_artista, delay):
    lista_artistas = [
        "Taylor Swift", "Drake", "Morgan Wallen", "Kendrick Lamar", "The Weeknd",
        "SZA", "Zach Bryan", "Tyler the Creator", "Billie Eilish", "Ariana Grande",
        "Bad Bunny", "Karol G", "Myke Towers", "Quevedo", "Aitana",
        "Rosalía", "Morad", "Melendi", "Enrique Iglesias", "Juanes",
        "Duki", "María Becerra", "Tini Stoessel", "Nicki Nicole", "Cazzu",
        "Esposito", "Paulo Londra", "Shakira", "Bizarrap", "Emilia",
    ]
    
    #headers para evitar bloqueos
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    tracks_search = {'id': [], 'title': [], 'rank': [], 'artist': []}
    
    for artista in lista_artistas:
        url= f"https://api.deezer.com/search/track?q=artist:\"{artista}\"&index=1&limit={limit_por_artista}"
        #url_1= f"https://api.deezer.com/search/track?q=artist:\"{artista}\"&limit={limit_por_artista}"
        print(f"Consultando tracks para: {artista}")
        
        try:
            respuesta = requests.get(url, headers=headers)
            if respuesta.status_code != 200:
                print(f"Error {respuesta.status_code} para {artista}")
                continue
            
            datos = respuesta.json()
            tracks = datos.get('data', [])
            
            if not tracks:              #en primer consulta arrojó 2 canciones para Taylor S.
                print(f"No se encontraron tracks para {artista}")
                continue
            
            for track in tracks:            #ver de agregar variables
                tracks_search['id'].append(track['id'])
                tracks_search['title'].append(track['title'])
                tracks_search['rank'].append(track.get('rank', 0))
                tracks_search['artist'].append(artista)  # guardamos el nombre buscado
            
            print(f"  → {len(tracks)} tracks obtenidos de {artista}")
            
        except Exception as e:
            print(f"Excepción con {artista}: {e}")
        
        # tiempo de espera para no sobrecargar la API
        time.sleep(delay)
    
    return tracks_search

# llamado y conversión a tabla
resultado = consulta_tracks(limit_por_artista=100, delay=1)
print(f"Total de tracks recolectados: {len(resultado['id'])}")

import pandas as pd
df = pd.DataFrame(resultado)
print(df.head())

Consultando tracks para: Taylor Swift
Excepción con Taylor Swift: HTTPSConnectionPool(host='api.deezer.com', port=443): Max retries exceeded with url: /search/track?q=artist:%22Taylor%20Swift%22&index=1&limit=100 (Caused by NameResolutionError("HTTPSConnection(host='api.deezer.com', port=443): Failed to resolve 'api.deezer.com' ([Errno -2] Name or service not known)"))
Consultando tracks para: Drake
Excepción con Drake: HTTPSConnectionPool(host='api.deezer.com', port=443): Max retries exceeded with url: /search/track?q=artist:%22Drake%22&index=1&limit=100 (Caused by NameResolutionError("HTTPSConnection(host='api.deezer.com', port=443): Failed to resolve 'api.deezer.com' ([Errno -2] Name or service not known)"))
Consultando tracks para: Morgan Wallen
Excepción con Morgan Wallen: HTTPSConnectionPool(host='api.deezer.com', port=443): Max retries exceeded with url: /search/track?q=artist:%22Morgan%20Wallen%22&index=1&limit=100 (Caused by NameResolutionError("HTTPSConnection(host='api.deezer.com', port=443): Failed to resolve 'api.deezer.com' ([Errno -2] Name or service not known)"))
Consultando tracks para: Kendrick Lamar
  → 100 tracks obtenidos de Kendrick Lamar
Consultando tracks para: The Weeknd
  → 100 tracks obtenidos de The Weeknd
Consultando tracks para: SZA
  → 100 tracks obtenidos de SZA
Consultando tracks para: Zach Bryan
  → 100 tracks obtenidos de Zach Bryan
Consultando tracks para: Tyler the Creator
  → 100 tracks obtenidos de Tyler the Creator
Consultando tracks para: Billie Eilish
  → 86 tracks obtenidos de Billie Eilish
Consultando tracks para: Ariana Grande
  → 100 tracks obtenidos de Ariana Grande
Consultando tracks para: Bad Bunny
  → 100 tracks obtenidos de Bad Bunny
Consultando tracks para: Karol G
  → 100 tracks obtenidos de Karol G
Consultando tracks para: Myke Towers
  → 100 tracks obtenidos de Myke Towers
Consultando tracks para: Quevedo
  → 100 tracks obtenidos de Quevedo
Consultando tracks para: Aitana
  → 100 tracks obtenidos de Aitana
Consultando tracks para: Rosalía
  → 100 tracks obtenidos de Rosalía
Consultando tracks para: Morad
  → 100 tracks obtenidos de Morad
Consultando tracks para: Melendi
  → 100 tracks obtenidos de Melendi
Consultando tracks para: Enrique Iglesias
  → 100 tracks obtenidos de Enrique Iglesias
Consultando tracks para: Juanes
  → 100 tracks obtenidos de Juanes
Consultando tracks para: Duki
  → 100 tracks obtenidos de Duki
Consultando tracks para: María Becerra
  → 100 tracks obtenidos de María Becerra
Consultando tracks para: Tini Stoessel
  → 1 tracks obtenidos de Tini Stoessel
Consultando tracks para: Nicki Nicole
  → 100 tracks obtenidos de Nicki Nicole
Consultando tracks para: Cazzu
  → 100 tracks obtenidos de Cazzu
Consultando tracks para: Esposito
  → 100 tracks obtenidos de Esposito
Consultando tracks para: Paulo Londra
  → 81 tracks obtenidos de Paulo Londra
Consultando tracks para: Shakira
  → 100 tracks obtenidos de Shakira
Consultando tracks para: Bizarrap
  → 100 tracks obtenidos de Bizarrap
Consultando tracks para: Emilia
  → 100 tracks obtenidos de Emilia
Total de tracks recolectados: 2568
           id                                            title    rank  \
0   446082632  All The Stars (From "Black Panther: The Album")  927928
1  3106586641                                           luther  824685
2  3106586681                                           tv off  827487
3    67929157                                      Money Trees  823308
4   350171311                                          HUMBLE.  816596

           artist
0  Kendrick Lamar
1  Kendrick Lamar
2  Kendrick Lamar
3  Kendrick Lamar
4  Kendrick Lamar

In [24]:
#print(resultado)
print(json.dumps(resultado, indent=2, ensure_ascii=False)) #para ver estructura (diccionario con listas por cada columna)

{
  "id": [
    446082632,
    3106586641,
    3106586681,
    67929157,
    350171311,
    350171251,
    3106586631,
    2715581062,
    1476644212,
    350171301,
    350171291,
    1766771507,
    3152680431,
    67929154,
    511062642,
    72089437,
    1766771527,
    350171331,
    2775438091,
    1766771497,
    372049961,
    456011702,
    52735971,
    1766771557,
    134533240,
    723393562,
    370426011,
    1766771587,
    97206068,
    3106586701,
    3106586651,
    77511988,
    3106586721,
    67929160,
    97206060,
    723393442,
    3106586671,
    623422582,
    634438752,
    723393612,
    723393582,
    67929167,
    350171271,
    67929162,
    1987477707,
    1766771607,
    723393482,
    67929163,
    67929161,
    350171341,
    1766771627,
    2783963112,
    1048706692,
    136889416,
    120380320,
    1766771677,
    75072823,
    3106586711,
    67929155,
    67929165,
    3106586691,
    723393422,
    131391770,
    3855225991,
    97206008,
    3596323222,
    3106586731,
    97206080,
    350171371,
    65672691,
    1766771537,
    97206076,
    797676502,
    67929159,
    120380312,
    350171281,
    456965102,
    648152372,
    412241052,
    2312477325,
    623422602,
    3106586621,
    1766771547,
    723393572,
    723393542,
    669486712,
    1766771577,
    560951892,
    97206082,
    1766771517,
    67814849,
    86401143,
    74506420,
    1766771637,
    97206064,
    1766771567,
    2292216785,
    120380324,
    120380318,
    13379027,
    138603423,
    781460692,
    10235485,
    3139566641,
    1685337397,
    908604612,
    1713175757,
    2338371075,
    1352360622,
    136889434,
    3210598411,
    106506512,
    3210598501,
    2321977215,
    2047662477,
    136889432,
    136889400,
    106506516,
    477452252,
    3210598391,
    908604622,
    92826786,
    3210598561,
    83844556,
    2747874731,
    2988053201,
    1614228192,
    1457107762,
    644296792,
    3210598441,
    62070468,
    3278625241,
    908604652,
    1225758662,
    79036873,
    1278960402,
    667570632,
    136889406,
    106506510,
    3210598591,
    122703266,
    456011702,
    1614226322,
    3210598381,
    1161752782,
    136889402,
    2164606877,
    383962071,
    908859832,
    2375967015,
    2747874801,
    2386586125,
    1614228242,
    62070464,
    3210598461,
    106506508,
    3210598481,
    1614228212,
    2166259397,
    1410738112,
    3210598511,
    106506526,
    908604582,
    136889414,
    3354177031,
    136886992,
    1278960492,
    2338371095,
    1506150362,
    1614226432,
    675343172,
    908859842,
    2247594637,
    1614226392,
    62070467,
    3210598431,
    1614226302,
    669486662,
    94664198,
    2747874881,
    477452262,
    3557222091,
    136889418,
    106506522,
    1103920482,
    3210598451,
    1543742002,
    136889410,
    1616709952,
    106506514,
    396449622,
    3210598551,
    70106519,
    1787557067,
    1614226412,
    477452272,
    2715581022,
    70106530,
    98060376,
    477452292,
    71360922,
    1652871722,
    446082632,
    12324459,
    2161357,
    940981052,
    86143581,
    2791029492,
    111959512,
    2287577657,
    134124418,
    58904781,
    134124424,
    3246376311,
    122719054,
    3448193751,
    1709027947,
    134124414,
    134124430,
    134124440,
    134124432,
    134124434,
    678135752,
    1183073772,
    2451110135,
    2159990047,
    3263319,
    134124416,
    134124412,
    1481570,
    134124422,
    134124420,
    1481594,
    3273945191,
    3279059491,
    134124438,
    3923177551,
    3203045851,
    134124426,
    11133249,
    134124428,
    480951472,
    378343711,
    134124436,
    1481615,
    716744722,
    1866968887,
    3055274551,
    1769174057,
    122139868,
    1481601,
    2530990371,
    1474495352,
    2270674347,
    1481586,
    111959860,
    677778612,
    411608542,
    413294312,
    699661202,
    1267228502,
    4832887,
    117655880,
    2352264875,
    110955536,
    17891655,
    3275539731,
    2479250131,
    74655406,
    122411294,
    3371998941,
    450146932,
    3565674011,
    25468101,
    1369066732,
    2613158982,
    3243007061,
    3418861481,
    2514509,
    3203045861,
    126095367,
    122958964,
    104096584,
    678135812,
    2115913,
    17891657,
    3464287301,
    58904971,
    3234643201,
    600977272,
    9750559,
    6914397,
    3361918071,
    12246791,
    1938147937,
    2765590011,
    2572464372,
    3471736591,
    58904951,
    1919215,
    2067127687,
    2814830342,
    3765755092,
    1816865957,
    3761742052,
    1714552247,
    1736518437,
    3761742122,
    3761742092,
    3761741942,
    2417266355,
    3761741952,
    3421343421,
    3761742022,
    2417266215,
    1155415792,
    3761741962,
    3512756601,
    2417266375,
    1714552257,
    2118224167,
    3761741972,
    2067127917,
    2461839205,
    3541597291,
    1736518477,
    3440259571,
    2417266195,
    3761742062,
    3421343381,
    2417266175,
    3761741992,
    3761742182,
    3421343411,
    3761742072,
    1152619842,
    1904534597,
    1736518647,
    3495656731,
    3765755152,
    3440259591,
    3761742082,
    3761742032,
    1163301932,
    2461839215,
    2461839245,
    3761741982,
    3464052381,
    2067127777,
    1816865987,
    1721999057,
    3765755172,
    1736518517,
    3200905201,
    3440259581,
    1166835592,
    1166835562,
    1816865977,
    3765755202,
    2461839225,
    3761742012,
    1166835522,
    3761742002,
    2896067901,
    3761742042,
    3421343461,
    3149745231,
    3761742142,
    1736518397,
    1736518407,
    1155415732,
    3421343401,
    3765755142,
    1166835512,
    1736518497,
    1166835492,
    1166835552,
    1155415722,
    1736518367,
    3765755212,
    3765755272,
    3761742112,
    1736518537,
    1155415692,
    2417266255,
    1152619832,
    3761742152,
    2834425672,
    1233891852,
    2461839235,
    1155415682,
    1736518387,
    2417266295,
    1736518557,
    2417266345,
    2067127727,
    1166835532,
    1816865967,
    3765755222,
    1644968512,
    3470152941,
    3064010401,
    446699712,
    681009652,
    3470153011,
    3064010361,
    12292154,
    681009752,
    3064010391,
    681009692,
    12292152,
    3470152981,
    65723687,
    681009722,
    1680292257,
    559711712,
    384157601,
    681009662,
    3064010301,
    3064010321,
    3064010411,
    1792992077,
    681009732,
    384157571,
    1413669942,
    16999969,
    681009642,
    65723678,
    564320582,
    1413669902,
    564320642,
    12292161,
    3470152951,
    3453936791,
    1413669892,
    1780549867,
    3470153001,
    98324152,
    681009742,
    2215437637,
    859494212,
    1413669922,
    65723682,
    3064010311,
    384157681,
    1413670012,
    3532148241,
    384157651,
    1413669932,
    2215437727,
    2215437737,
    102659150,
    98324154,
    3064010291,
    1413670002,
    3064010421,
    3470152931,
    1413669912,
    3532148341,
    384157631,
    384157621,
    2245219087,
    14241668,
    65723693,
    922331112,
    556225692,
    3470152991,
    1391439912,
    964845092,
    681009702,
    578600182,
    3623651642,
    3470152961,
    681009712,
    3064010371,
    2215437777,
    1483699192,
    508003872,
    681009682,
    14241662,
    3064010381,
    3064010351,
    3470153021,
    384157561,
    1413669982,
    2023238107,
    1413669882,
    12292151,
    65723685,
    1413669952,
    2208390237,
    3777479862,
    479629392,
    1614226362,
    2215437767,
    12292158,
    717273782,
    3623651562,
    585408102,
    65723681,
    2366043655,
    2801558062,
    2801558042,
    2929354381,
    655095912,
    803010392,
    486928932,
    655095962,
    1449740592,
    2801558112,
    2801558032,
    655096022,
    877873612,
    2801558022,
    655095942,
    145343466,
    441178832,
    2801558102,
    2801558092,
    2801558082,
    2801558072,
    477338062,
    441178812,
    136337268,
    1216945442,
    655095992,
    1449740572,
    1833875727,
    142752898,
    711031072,
    2277080717,
    136246804,
    1449740502,
    1833875737,
    655095952,
    1449727402,
    1449740562,
    655095932,
    2813431572,
    441178822,
    1449740512,
    1483895182,
    1449727532,
    1140484252,
    1449727422,
    655096002,
    655095972,
    441178802,
    441178872,
    655095982,
    1449727382,
    1449740472,
    612132022,
    590067732,
    655096012,
    1449727432,
    441178882,
    1449727482,
    441178842,
    1449740452,
    655095922,
    1449740532,
    435906472,
    2228313107,
    3975967971,
    140119847,
    469407852,
    355738511,
    655096032,
    141340255,
    140119843,
    1449727462,
    141340253,
    141340251,
    1250420562,
    661235352,
    140119849,
    2289552565,
    141340257,
    655095902,
    3480266781,
    2441291635,
    1067793952,
    1166910502,
    1416790152,
    717944342,
    3294514251,
    2690050002,
    83844534,
    2614318122,
    629899842,
    542389552,
    81609384,
    1126047052,
    953769542,
    124995668,
    1375215222,
    1375215242,
    83844536,
    542389502,
    973317062,
    629899852,
    83844556,
    1375215262,
    83844544,
    2690049962,
    144130194,
    2690049982,
    3294514131,
    724038592,
    2690049922,
    629899762,
    2981279421,
    1126047002,
    3294514261,
    131391768,
    629899822,
    541418452,
    2164606877,
    69959813,
    3294514281,
    1375215292,
    790914772,
    111052058,
    629899782,
    3294514291,
    3294514241,
    657493802,
    1375215332,
    3662731222,
    857206512,
    1249621332,
    83837268,
    3782340962,
    3294514271,
    1375215232,
    3100315991,
    629899862,
    69959806,
    3294514111,
    542373692,
    542389542,
    69959816,
    2892932161,
    629899802,
    3100316021,
    137729301,
    2690049972,
    83844562,
    3294514121,
    1375215352,
    2690050022,
    133984340,
    3294514091,
    73248264,
    1375215272,
    1375215282,
    1287900732,
    3100315961,
    69959809,
    629899772,
    2690050012,
    1023602362,
    629899752,
    3045225161,
    1249621402,
    1375215212,
    1573552612,
    629899832,
    3662731132,
    1126047062,
    629899792,
    83837266,
    1126046952,
    1249621472,
    542389592,
    1126046962,
    69959815,
    1126047082,
    1126047022,
    790914822,
    1126046892,
    542389512,
    353133811,
    2690050032,
    790914762,
    3695893892,
    535391032,
    3171003131,
    3171003001,
    3171003091,
    3171003121,
    1741494317,
    1122450992,
    3171003021,
    3171003031,
    3171002991,
    3086954731,
    1741494417,
    1425937972,
    2496106371,
    3171003141,
    1741494307,
    3171003071,
    608410292,
    702421822,
    1741494477,
    1741494287,
    3171003111,
    3171003011,
    3171003061,
    2496106511,
    3171003081,
    972627922,
    3171003041,
    1155477802,
    704054322,
    889550982,
    686020062,
    3171003051,
    2496106541,
    3171003101,
    2316903805,
    1869675977,
    889550892,
    2289342455,
    1741494407,
    1412071172,
    1390823292,
    1741494447,
    1741494377,
    1498815252,
    1741494467,
    2042243747,
    2758436071,
    2496106431,
    1741494327,
    704078382,
    1045832172,
    2242449097,
    889550882,
    3457344911,
    1741494357,
    482413672,
    2473410281,
    608410332,
    1155477812,
    1741494457,
    2496106361,
    704078562,
    1741494347,
    2471293381,
    451149572,
    1741494487,
    2193354717,
    1741494437,
    1741494337,
    889550862,
    133297136,
    2496106391,
    776076902,
    1741494297,
    668529022,
    1155477892,
    1155477832,
    704059932,
    2496106381,
    482986842,
    1741494427,
    141553591,
    1741494387,
    875511852,
    702421812,
    411091822,
    1155477772,
    1451598462,
    889551002,
    3345061051,
    677305422,
    136305954,
    608410262,
    143986188,
    2496106451,
    482843042,
    1741494367,
    2156158667,
    3981224901,
    2154046487,
    3421452631,
    1721634237,
    3421452651,
    3376766301,
    1649460922,
    2403815945,
    3421452581,
    3421452481,
    796342592,
    714210042,
    2154046437,
    3421452471,
    2154046577,
    2154046457,
    1283546522,
    3353740701,
    3076608311,
    2006806507,
    3421452541,
    2403815955,
    3421452551,
    1283546482,
    2131900117,
    3421452501,
    1049272552,
    1496293332,
    3421452521,
    2381438915,
    3421452531,
    2655316752,
    2154046537,
    1882539797,
    3421452511,
    1583346082,
    2356322575,
    1444099622,
    672202162,
    2154046597,
    3421452601,
    3421452611,
    365643061,
    2403815915,
    3421452591,
    2403815925,
    1110762302,
    2403816065,
    616539122,
    575891702,
    1567098932,
    2403816025,
    3421452561,
    3421452621,
    497151272,
    3421452461,
    1407492942,
    1012504022,
    3421452571,
    553957272,
    2301174945,
    1150505002,
    2154046557,
    657761942,
    477392342,
    3667253872,
    2403816105,
    2005370277,
    2154046477,
    2154046507,
    518459732,
    1283546502,
    648273462,
    2154046467,
    525996902,
    2547799552,
    1233167142,
    1283546492,
    2154046497,
    3031011641,
    672202182,
    2570906182,
    2959868521,
    121124374,
    2403815975,
    623698202,
    671255752,
    135373484,
    751125272,
    2154046517,
    961348062,
    917384132,
    2403815905,
    1712735117,
    1283546622,
    2773864191,
    542488362,
    2043307517,
    414682232,
    672202232,
    3368936011,
    2542594331,
    3824901081,
    2294944375,
    978387002,
    2045122487,
    1095137892,
    2159990627,
    3039942561,
    857827262,
    2758436071,
    3260565211,
    1172384912,
    1331984152,
    937416142,
    1044802062,
    974000002,
    3069012151,
    717285742,
    3697524132,
    2927624581,
    857827162,
    662274202,
    2912364201,
    1049272552,
    2321212095,
    909576642,
    927408142,
    1440185042,
    1162056102,
    1142380132,
    2348872955,
    1078759092,
    2542594411,
    857827232,
    3945244821,
    1567099042,
    3913631501,
    2309824565,
    3147491001,
    1496278042,
    3380325261,
    537872822,
    1399887862,
    2193354727,
    3279575191,
    857827272,
    857827152,
    3952366141,
    3202603181,
    705425882,
    828486762,
    1226448792,
    2674307332,
    857827192,
    857827282,
    566770762,
    857827242,
    696690342,
    717740522,
    1386230782,
    3429928271,
    3039942631,
    1952987777,
    1674916197,
    705581612,
    3202603141,
    1351104272,
    2804986202,
    706139002,
    1677750597,
    2714132532,
    665914662,
    1053377172,
    1262234002,
    773905582,
    1193945962,
    2322228845,
    1166656072,
    857827212,
    2936419841,
    751158212,
    2473410251,
    2927624541,
    2423937665,
    1172384892,
    753835752,
    909336752,
    1351104232,
    1324636742,
    2159990637,
    1349744842,
    2159990497,
    3202603251,
    1044802612,
    859432322,
    773615482,
    678471932,
    3279576111,
    568685952,
    72993990,
    3981853731,
    1426036652,
    3981853771,
    3981853741,
    3981853831,
    3981853751,
    3981853721,
    3981853791,
    3843020331,
    3981853781,
    3981853851,
    3981853801,
    3981853761,
    3981853821,
    3981853811,
    3368936011,
    3104740761,
    3382134521,
    1811481707,
    3447342231,
    3274807471,
    3104740891,
    3104740971,
    3217407501,
    3480440021,
    3104740791,
    1981818727,
    2154046457,
    3217412491,
    2338469455,
    2045122487,
    3104740681,
    3104740731,
    2248629077,
    3104740841,
    3104740881,
    3104740921,
    3217535351,
    3217535381,
    3217411961,
    1599437392,
    3104740951,
    2313435675,
    3217535401,
    3668430692,
    2482830851,
    3104740871,
    3217535391,
    3104740911,
    2233549207,
    3217535291,
    3217535321,
    3296726521,
    3104740811,
    3219256631,
    3217535331,
    1700761967,
    2545940182,
    2195211937,
    3358977371,
    3217535371,
    3104740961,
    2552447642,
    2294428925,
    3217535281,
    3217411241,
    3217535451,
    3217535341,
    3141215631,
    3104740931,
    3104740701,
    3655199202,
    2035201357,
    3219524511,
    1640690782,
    2021305867,
    2544359381,
    3217535691,
    2294688245,
    1522054342,
    3217535411,
    3217535421,
    3682563722,
    3104740901,
    1775141327,
    2462969875,
    2288414387,
    3217532481,
    3028526781,
    3219260371,
    2494111761,
    3104740941,
    3219524531,
    1684980787,
    2010116887,
    3217535271,
    3219258361,
    2331931065,
    3217536871,
    3345503111,
    3104740761,
    3380325231,
    1466081782,
    3380325151,
    1776595277,
    3380325271,
    3380325321,
    3380325181,
    3380325161,
    3380325191,
    3380325171,
    2757069431,
    593589572,
    831250542,
    2204492107,
    3380325201,
    1825853207,
    1566795482,
    531211011,
    3380325211,
    3380325311,
    2304706875,
    661573222,
    2416491895,
    3380325251,
    2867389812,
    1033236192,
    1490258492,
    916172752,
    1697195137,
    1164958852,
    468263862,
    2455267015,
    1517482552,
    3380325291,
    1738658377,
    3380325261,
    2929731081,
    685799152,
    3380325301,
    3380325221,
    1413244422,
    3380325241,
    2444527695,
    689409192,
    1164958832,
    480866212,
    2455267005,
    3638004472,
    1090972972,
    1164958842,
    1164958812,
    955863782,
    2455267095,
    2816257922,
    1164958752,
    1164958762,
    543106902,
    2455267115,
    2455267085,
    2455267065,
    1999216187,
    3486464751,
    678661762,
    1436299642,
    454940862,
    1352141712,
    2455267025,
    1164958802,
    689409272,
    1913400407,
    689409212,
    1164958782,
    468263782,
    3975953391,
    1164958772,
    1529137502,
    1524754792,
    2455267035,
    689409242,
    1629136182,
    450010012,
    2035204907,
    2035204787,
    1340888672,
    422862882,
    3975953421,
    3975953431,
    2035204757,
    587629362,
    689409262,
    2455267045,
    2035204817,
    454940812,
    689409232,
    2035204807,
    2035204777,
    425158842,
    483561412,
    3640140952,
    1845488747,
    3961034571,
    3961034601,
    3640140902,
    3961034591,
    3961034551,
    3640140942,
    3640140892,
    1841999507,
    3640140912,
    3640140982,
    3961034581,
    1685337397,
    3961034611,
    3640140932,
    3640141032,
    3640140922,
    3640140992,
    2200304467,
    3640140972,
    3640140962,
    3886325891,
    3640141022,
    1155477802,
    731498882,
    555188302,
    1685337377,
    1892776297,
    2200304477,
    656027552,
    2120686497,
    555188252,
    3255030181,
    555188232,
    1480970322,
    1685337607,
    1685337837,
    2945954741,
    1685337387,
    2317987945,
    1066959132,
    1685337807,
    1928900437,
    141822209,
    1685337717,
    911234192,
    3005771231,
    1685337817,
    1902534157,
    1216945442,
    555188242,
    1685337407,
    858554762,
    141822223,
    555188292,
    1685337847,
    705789712,
    1685337787,
    1685337457,
    1685337797,
    421773372,
    2537421951,
    2200304487,
    972669712,
    1374548832,
    502733352,
    616963272,
    555188262,
    1902534207,
    1161752782,
    555188332,
    555188272,
    141822203,
    687865142,
    555188282,
    141822221,
    705789722,
    1902534187,
    141822207,
    798480562,
    141822205,
    2067099057,
    1685337527,
    841897042,
    141822211,
    1685337777,
    141822213,
    555188322,
    644568452,
    1902534137,
    555188312,
    1685337827,
    141822217,
    1902534177,
    1902534167,
    1902534197,
    211462,

In [25]:
df=pd.DataFrame(resultado)
df

,id,title,rank,artist
0,446082632,"All The Stars (From ""Black Panther: The Album"")",927928,Kendrick Lamar
1,3106586641,luther,824685,Kendrick Lamar
2,3106586681,tv off,827487,Kendrick Lamar
3,67929157,Money Trees,823308,Kendrick Lamar
4,350171311,HUMBLE.,816596,Kendrick Lamar
...,...,...,...,...
2563,1551939962,Te Doy Mi Vida (Masters en Parranda),240089,Emilia
2564,894202362,HISTERIQUEO,203814,Emilia
2565,831895912,Billion,271307,Emilia
2566,2498034101,A_1000_Km.mp3,198967,Emilia
2567,3506542051,Bruja,233465,Emilia

#### Consulta modelo de tracks (Taylor Swift y Tini Stoessel - 100 canciones)

In [26]:
import re

def llamar():
    #url='https://api.deezer.com/search/track?q=taylor&swift=undefined&index=0&limit=100'    """FUNCION OK PARA TAYLOR"""
    url00="https://api.deezer.com/search/track?q=TINI&index=0&limit=100" #"id": "2252591","name": "TINI",
    headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }


    respuesta = requests.get(url00,headers=headers)
    if respuesta.status_code != 200:
        print(f"Error: {respuesta.status_code}")
    else:
        datos = respuesta.json()
        tracks = datos.get('data',[])
        return tracks

In [27]:
consulta_tini=llamar()
#print(json.dumps(a,indent=2,ensure_ascii=False))

In [28]:
len(consulta_tini)

96

In [29]:
print(json.dumps(consulta_tini,indent=2,ensure_ascii=False))

[
  {
    "id": 3288087861,
    "readable": true,
    "title": "blackout ?",
    "title_short": "blackout ?",
    "title_version": "",
    "isrc": "USSD12500117",
    "link": "https://www.deezer.com/track/3288087861",
    "duration": 180,
    "rank": 577836,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3?hdnea=exp=1777380704~acl=/api/1/1/4/9/3/0/49390d5f9b4a2ab72f844858653c663e.mp3*~data=user_id=0,application_id=42~hmac=cf0d2e3eb9a6099a3f9f3ea3100a7fa49e5d29ff1823cc00344feffafaa7021e",
    "md5_image": "fee888110d29c7d8021275c36004961f",
    "artist": {
      "id": 61094422,
      "name": "Emilia",
      "link": "https://www.deezer.com/artist/61094422",
      "picture": "https://api.deezer.com/artist/61094422/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 730638231,
      "title": "blackout ?",
      "cover": "https://api.deezer.com/album/730638231/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/fee888110d29c7d8021275c36004961f/1000x1000-000000-80-0-0.jpg",
      "md5_image": "fee888110d29c7d8021275c36004961f",
      "tracklist": "https://api.deezer.com/album/730638231/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 1349596782,
    "readable": true,
    "title": "Miénteme",
    "title_short": "Miénteme",
    "title_version": "",
    "isrc": "USHR12141512",
    "link": "https://www.deezer.com/track/1349596782",
    "duration": 165,
    "rank": 640928,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/b/7/0/0/b7043937515638675a3ac002a49f9641.mp3?hdnea=exp=1777380704~acl=/api/1/1/b/7/0/0/b7043937515638675a3ac002a49f9641.mp3*~data=user_id=0,application_id=42~hmac=88e1ab6e34c16b650d5c0ca757888c274f4b893602c1f1e3d747bd47d92ba631",
    "md5_image": "3e6361aae5a06412f6029a371ddb464f",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 224353382,
      "title": "Miénteme",
      "cover": "https://api.deezer.com/album/224353382/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/3e6361aae5a06412f6029a371ddb464f/1000x1000-000000-80-0-0.jpg",
      "md5_image": "3e6361aae5a06412f6029a371ddb464f",
      "tracklist": "https://api.deezer.com/album/224353382/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 1415274362,
    "readable": true,
    "title": "La Niña de la Escuela",
    "title_short": "La Niña de la Escuela",
    "title_version": "",
    "isrc": "ES5702100732",
    "link": "https://www.deezer.com/track/1415274362",
    "duration": 204,
    "rank": 567777,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 0,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/9/4/2/0/942ee634f0f24e6102abaef37bf0634e.mp3?hdnea=exp=1777380704~acl=/api/1/1/9/4/2/0/942ee634f0f24e6102abaef37bf0634e.mp3*~data=user_id=0,application_id=42~hmac=0e164e41c3665d1eda282f5a41cbbd3462d90346d5a46415bf8ae0e60e4c7967",
    "md5_image": "9a727073b88de02008749d70d54d029c",
    "artist": {
      "id": 48765861,
      "name": "Lola Indigo",
      "link": "https://www.deezer.com/artist/48765861",
      "picture": "https://api.deezer.com/artist/48765861/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/f87b9bce8f420d9a2116680be75e7878/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/48765861/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 239883572,
      "title": "La Niña",
      "cover": "https://api.deezer.com/album/239883572/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/9a727073b88de02008749d70d54d029c/1000x1000-000000-80-0-0.jpg",
      "md5_image": "9a727073b88de02008749d70d54d029c",
      "tracklist": "https://api.deezer.com/album/239883572/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 3907274501,
    "readable": true,
    "title": "Dos Amantes",
    "title_short": "Dos Amantes",
    "title_version": "",
    "isrc": "USHR12652960",
    "link": "https://www.deezer.com/track/3907274501",
    "duration": 188,
    "rank": 598977,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/a/e/8/0/ae8f6924dbf0de0fffc639448eab7b41.mp3?hdnea=exp=1777380704~acl=/api/1/1/a/e/8/0/ae8f6924dbf0de0fffc639448eab7b41.mp3*~data=user_id=0,application_id=42~hmac=645846cceaabed679320e6626ecddd193dd58dafecdd4ce54cd3bcf08ad2b8ee",
    "md5_image": "d61b81fa3d9e3b40fabb91cb14ba30cc",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 942083251,
      "title": "Dos Amantes",
      "cover": "https://api.deezer.com/album/942083251/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/d61b81fa3d9e3b40fabb91cb14ba30cc/1000x1000-000000-80-0-0.jpg",
      "md5_image": "d61b81fa3d9e3b40fabb91cb14ba30cc",
      "tracklist": "https://api.deezer.com/album/942083251/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 3403101261,
    "readable": true,
    "title": "Universidad",
    "title_short": "Universidad",
    "title_version": "",
    "isrc": "USHR12550967",
    "link": "https://www.deezer.com/track/3403101261",
    "duration": 158,
    "rank": 593349,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/f/7/9/0/f796d7498e00a1f13d3e595454a106a4.mp3?hdnea=exp=1777380704~acl=/api/1/1/f/7/9/0/f796d7498e00a1f13d3e595454a106a4.mp3*~data=user_id=0,application_id=42~hmac=b5bf24980d4e84588fecb8825bd11098440d7cb4993e12f2a88138da0eeac7bc",
    "md5_image": "2521629f12d9e8e85cef8b65f284bbd4",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 768688871,
      "title": "Universidad",
      "cover": "https://api.deezer.com/album/768688871/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/2521629f12d9e8e85cef8b65f284bbd4/1000x1000-000000-80-0-0.jpg",
      "md5_image": "2521629f12d9e8e85cef8b65f284bbd4",
      "tracklist": "https://api.deezer.com/album/768688871/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 2498029491,
    "readable": true,
    "title": "La_Original.mp3",
    "title_short": "La_Original.mp3",
    "title_version": "",
    "isrc": "USSD12300584",
    "link": "https://www.deezer.com/track/2498029491",
    "duration": 140,
    "rank": 541606,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3?hdnea=exp=1777380704~acl=/api/1/1/9/5/4/0/9543ac2cd39b5d63effa25c9328d8b4e.mp3*~data=user_id=0,application_id=42~hmac=0560e94de5301a9ab57d967963601747dd5cd0569f71e0a4bd2e0f8309851bc8",
    "md5_image": "1eb3b9ecd27cd1be09d01cc8ff513ecb",
    "artist": {
      "id": 61094422,
      "name": "Emilia",
      "link": "https://www.deezer.com/artist/61094422",
      "picture": "https://api.deezer.com/artist/61094422/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/bd2b4dd505269891296688261244d10e/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/61094422/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 499990281,
      "title": "La_Original.mp3",
      "cover": "https://api.deezer.com/album/499990281/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/1eb3b9ecd27cd1be09d01cc8ff513ecb/1000x1000-000000-80-0-0.jpg",
      "md5_image": "1eb3b9ecd27cd1be09d01cc8ff513ecb",
      "tracklist": "https://api.deezer.com/album/499990281/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 2043307557,
    "readable": true,
    "title": "Consejo de Amor (feat. Morat)",
    "title_short": "Consejo de Amor (feat. Morat)",
    "title_version": "",
    "isrc": "USHR11838708",
    "link": "https://www.deezer.com/track/2043307557",
    "duration": 200,
    "rank": 520545,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/7/8/2/0/782f6bca4d028178ad65bbce572d4317.mp3?hdnea=exp=1777380704~acl=/api/1/1/7/8/2/0/782f6bca4d028178ad65bbce572d4317.mp3*~data=user_id=0,application_id=42~hmac=af4d1fe58258ef1928c018465e72703cf09eced4ce54172fdfb147f0c6b74e2a",
    "md5_image": "0baa725364e931a95d79c072743b3b46",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 381949317,
      "title": "Quiero Volver",
      "cover": "https://api.deezer.com/album/381949317/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/0baa725364e931a95d79c072743b3b46/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/0baa725364e931a95d79c072743b3b46/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/0baa725364e931a95d79c072743b3b46/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/0baa725364e931a95d79c072743b3b46/1000x1000-000000-80-0-0.jpg",
      "md5_image": "0baa725364e931a95d79c072743b3b46",
      "tracklist": "https://api.deezer.com/album/381949317/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 1640435962,
    "readable": true,
    "title": "Fantasi",
    "title_short": "Fantasi",
    "title_version": "",
    "isrc": "USHR12243048",
    "link": "https://www.deezer.com/track/1640435962",
    "duration": 159,
    "rank": 550858,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/e/a/0/0/ea084408ba109031203e25bdcbafe861.mp3?hdnea=exp=1777380704~acl=/api/1/1/e/a/0/0/ea084408ba109031203e25bdcbafe861.mp3*~data=user_id=0,application_id=42~hmac=f5f041219a2dc610ff4c87ea2068d6f86726f490ec12d424c2b64010da2d65f0",
    "md5_image": "1e8a123dedb0a22287f606eddcfd4125",
    "artist": {
      "id": 2252591,
      "name": "TINI",
      "link": "https://www.deezer.com/artist/2252591",
      "picture": "https://api.deezer.com/artist/2252591/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/efb8ac71cf0c9358acbce2b8126bfa39/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/2252591/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 291955082,
      "title": "Fantasi",
      "cover": "https://api.deezer.com/album/291955082/image",
      "cover_small": "https://cdn-images.dzcdn.net/images/cover/1e8a123dedb0a22287f606eddcfd4125/56x56-000000-80-0-0.jpg",
      "cover_medium": "https://cdn-images.dzcdn.net/images/cover/1e8a123dedb0a22287f606eddcfd4125/250x250-000000-80-0-0.jpg",
      "cover_big": "https://cdn-images.dzcdn.net/images/cover/1e8a123dedb0a22287f606eddcfd4125/500x500-000000-80-0-0.jpg",
      "cover_xl": "https://cdn-images.dzcdn.net/images/cover/1e8a123dedb0a22287f606eddcfd4125/1000x1000-000000-80-0-0.jpg",
      "md5_image": "1e8a123dedb0a22287f606eddcfd4125",
      "tracklist": "https://api.deezer.com/album/291955082/tracks",
      "type": "album"
    },
    "type": "track"
  },
  {
    "id": 2269250827,
    "readable": true,
    "title": "Me Enteré",
    "title_short": "Me Enteré",
    "title_version": "",
    "isrc": "USWL12300718",
    "link": "https://www.deezer.com/track/2269250827",
    "duration": 182,
    "rank": 562639,
    "explicit_lyrics": false,
    "explicit_content_lyrics": 0,
    "explicit_content_cover": 2,
    "preview": "https://cdnt-preview.dzcdn.net/api/1/1/2/c/1/0/2c10e728ec2c9853ae77e07ef96194aa.mp3?hdnea=exp=1777380704~acl=/api/1/1/2/c/1/0/2c10e728ec2c9853ae77e07ef96194aa.mp3*~data=user_id=0,application_id=42~hmac=1bb5da4a70d686a911c8c11ab6778bd25a67bd980f6eb66a8bf16bf82097614f",
    "md5_image": "86c3cd619ad4c6d105f7376ee3f8763c",
    "artist": {
      "id": 49364062,
      "name": "Tiago PZK",
      "link": "https://www.deezer.com/artist/49364062",
      "picture": "https://api.deezer.com/artist/49364062/image",
      "picture_small": "https://cdn-images.dzcdn.net/images/artist/7db8c378960dfba85e83ae34a61050f5/56x56-000000-80-0-0.jpg",
      "picture_medium": "https://cdn-images.dzcdn.net/images/artist/7db8c378960dfba85e83ae34a61050f5/250x250-000000-80-0-0.jpg",
      "picture_big": "https://cdn-images.dzcdn.net/images/artist/7db8c378960dfba85e83ae34a61050f5/500x500-000000-80-0-0.jpg",
      "picture_xl": "https://cdn-images.dzcdn.net/images/artist/7db8c378960dfba85e83ae34a61050f5/1000x1000-000000-80-0-0.jpg",
      "tracklist": "https://api.deezer.com/artist/49364062/top?limit=50",
      "type": "artist"
    },
    "album": {
      "id": 437633197,
      "title": "Me Enteré",
      "cover": "https://api.deezer.com/album/437633197/image",

##### Función para limpiar tracks

In [30]:
def depurar():  
    lista_tini_depurada=[]
    for track in consulta_tini:
        if "TINI" not in track['artist']['name']:
            continue
        else:
            lista_tini_depurada.append(track)
            
    print(f"Se encontraron {len(lista_tini_depurada)} resultados.")
            
    
    return lista_tini_depurada
TINI=depurar()

Se encontraron 72 resultados.

In [31]:
for r in TINI:
    print(f" - {r['title']}")

#SE OBSERVAN RESULTADOS DUPLICADOS

 - Miénteme
 - Dos Amantes
 - Universidad
 - Consejo de Amor (feat. Morat)
 - Fantasi
 - el cielo
 - Maldita Foto
 - Fresa
 - Un Beso en Madrid
 - Una Noche Más
 - pa
 - El Cielo + Fresa LIVE
 - Te Pido Live
 - Cupido
 - Bar
 - La Loto
 - Carne y Hueso
 - Muñecas
 - tinta 90
 - Te Quiero Más
 - Las Jordans
 - Te Pido
 - Oye
 - La Triple T
 - Missed Calls
 - 36 Vidas
 - Suéltate el Pelo
 - Cupido LIVE
 - 22
 - Siempre Brillarás
 - me voy en vivo
 - Por Qué Te Vas
 - Down
 - ni de ti
 - 7 Veces
 - Princesa
 - Podemos
 - ángel
 - Ser Mejor
 - Acércate
 - Si Tu Te Vas
 - buenos aires
 - What If, Then What? (feat. Amiture)
 - Quiero Volver
 - El Último Beso
 - De Papel
 - En Mi Mundo (From "Violetta" Music from the TV Series)
 - No Reply
 - Libre Soy (Single Version)
 - Te Creo
 - Una Noche Más LIVE
 - Confía En Mí
 - Yo Te Amo A Ti
 - me voy
 - Te Creo LIVE
 - Esto No Puede Terminar
 - buenos aires en vivo
 - Recuerdo
 - Te Olvidaré
 - Ya No Hay Nadie Que Nos Pare
 - Hoy Somos Más (Live)
 - posta
 - Podemos (Live)
 - Diciembre
 - Ella Dice
 - Se Escapa Tu Amor
 - Aquí Estoy
 - Beso En Las Rocas
 - Great Escape
 - Duele (feat. John C)
 - On Beat (Live)
 - miedo

## Consulta de canciones por Id artista (RUTA:TOP)

In [17]:
import requests
import time

def consulta_cancion(lista_artistas):
    info_canciones = []
       
    for artista in lista_artistas:
        id_artista = artista["id_artista"]
        nombre_artista = artista["nombre_artista"]

        consulta_canciones = requests.get(f"https://api.deezer.com/artist/{id_artista}/top?limit=50")

        if consulta_canciones.status_code != 200:
            print(f"No se pudo consultar las canciones del artista: {nombre_artista}")
            continue
        datos_canciones = consulta_canciones.json()

        for cancion in datos_canciones["data"]:
            info_canciones.append({"id_artista": id_artista,"nombre_artista": nombre_artista,"id_cancion": cancion["id"],
                            "titulo_cancion": cancion["title"],"id_album":cancion ["album"]["id"]})#,"titulo_album": cancion["album"]["title"]})#,
                            #"contributors": cancion.get("contributors")})

            
        time.sleep(0.3)
    return info_canciones

In [18]:
artistas_30= [{'id_artista': 12246, 'nombre_artista': 'Taylor Swift'},
 {'id_artista': 246791, 'nombre_artista': 'Drake'},
 {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen'},
 {'id_artista': 525046, 'nombre_artista': 'Kendrick Lamar'},
 {'id_artista': 4050205, 'nombre_artista': 'The Weeknd'},
 {'id_artista': 5531258, 'nombre_artista': 'SZA'},
 {'id_artista': 71855892, 'nombre_artista': 'Zach Bryan'},
 {'id_artista': 1194083, 'nombre_artista': 'Tyler, The Creator'},
 {'id_artista': 9635624, 'nombre_artista': 'Billie Eilish'},
 {'id_artista': 1562681, 'nombre_artista': 'Ariana Grande'},
 {'id_artista': 10583405, 'nombre_artista': 'Bad Bunny'},
 {'id_artista': 5297021, 'nombre_artista': 'KAROL G'},
 {'id_artista': 12029862, 'nombre_artista': 'Myke Towers'},
 {'id_artista': 6705223, 'nombre_artista': 'Quevedo'},
 {'id_artista': 11928391, 'nombre_artista': 'Aitana'},
 {'id_artista': 554792, 'nombre_artista': 'ROSALÍA'},
 {'id_artista': 111130212, 'nombre_artista': 'Morad'},
 {'id_artista': 2697, 'nombre_artista': 'Melendi'},
 {'id_artista': 2792, 'nombre_artista': 'Enrique Iglesias'},
 {'id_artista': 70, 'nombre_artista': 'Juanes'},
 {'id_artista': 4902904, 'nombre_artista': 'DUKI'},
 {'id_artista': 14343187, 'nombre_artista': 'Maria Becerra'},
 {'id_artista': 2252591, 'nombre_artista': 'TINI'},
 {'id_artista': 13299379, 'nombre_artista': 'Nicki Nicole'},
 {'id_artista': 12268072, 'nombre_artista': 'Cazzu'},
 {'id_artista': 5181388, 'nombre_artista': 'Lali'},
 {'id_artista': 12637039, 'nombre_artista': 'Paulo Londra'},
 {'id_artista': 160, 'nombre_artista': 'Shakira'},
 {'id_artista': 12487862, 'nombre_artista': 'Bizarrap'},
 {'id_artista': 61094422, 'nombre_artista': 'Emilia'}]

info_artista_cancion=consulta_cancion(artistas_30)

In [19]:
print(info_artista_cancion)

[{'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685431, 'titulo_cancion': 'The Fate of Ophelia', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685451, 'titulo_cancion': 'Opalite', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077547, 'titulo_cancion': 'Blank Space', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077555, 'titulo_cancion': 'Shake It Off', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293211, 'titulo_cancion': "Out Of The Woods (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967292, 'titulo_cancion': 'Cruel Summer', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685441, 'titulo_cancion': 'Elizabeth Taylor', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685471, 'titulo_cancion': 'Eldest Daughter', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967452, 'titulo_cancion': 'Daylight', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2035609347, 'titulo_cancion': 'Anti-Hero (Acoustic Version)', 'id_album': 380094787}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077549, 'titulo_cancion': 'Style', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1976903157, 'titulo_cancion': 'Anti-Hero', 'id_album': 368474187}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685491, 'titulo_cancion': 'Actually Romantic', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1031382392, 'titulo_cancion': 'exile', 'id_album': 162683442}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1550966602, 'titulo_cancion': "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)", 'id_album': 272247412}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2757496031, 'titulo_cancion': 'I Can Do It With a Broken Heart', 'id_album': 575252501}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 529117841, 'titulo_cancion': 'We Are Never Ever Getting Back Together', 'id_album': 68491961}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1031382712, 'titulo_cancion': 'cardigan', 'id_album': 162683632}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293191, 'titulo_cancion': "Blank Space (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685501, 'titulo_cancion': 'Wi$h Li$t', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967412, 'titulo_cancion': 'You Need To Calm Down', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2753115381, 'titulo_cancion': 'Fortnight', 'id_album': 574109801}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1053765282, 'titulo_cancion': 'august', 'id_album': 167766152}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685461, 'titulo_cancion': 'Father Figure', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 595112162, 'titulo_cancion': 'I Don’t Wanna Live Forever (Fifty Shades Darker)', 'id_album': 80126642}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491472, 'titulo_cancion': 'Don’t Blame Me', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491492, 'titulo_cancion': 'Look What You Made Me Do', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1332677012, 'titulo_cancion': 'You Belong With Me (Taylor’s Version)', 'id_album': 221543452}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685551, 'titulo_cancion': 'CANCELLED!', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491452, 'titulo_cancion': 'End Game', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2917264, 'titulo_cancion': 'Love Story', 'id_album': 283925}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967342, 'titulo_cancion': 'Miss Americana & The Heartbreak Prince', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077561, 'titulo_cancion': 'Wildest Dreams', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685481, 'titulo_cancion': 'Ruin The Friendship', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293251, 'titulo_cancion': "Bad Blood (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491482, 'titulo_cancion': 'Delicate', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3852236971, 'titulo_cancion': 'Opalite (Ely Oaks Remix)', 'id_album': 922021001}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2757496121, 'titulo_cancion': 'So High School', 'id_album': 575252501}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2355587775, 'titulo_cancion': "Enchanted (Taylor's Version)", 'id_album': 461146065}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1332676982, 'titulo_cancion': 'Love Story (Taylor’s Version)', 'id_album': 221543452}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1977132317, 'titulo_cancion': 'Karma', 'id_album': 368506677}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1976903227, 'titulo_cancion': 'Bejeweled', 'id_album': 368474187}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2757496021, 'titulo_cancion': 'loml', 'id_album': 575252501}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293201, 'titulo_cancion': "Style (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3642533572, 'titulo_cancion': 'The Fate of Ophelia (Loud Luxury Remix)', 'id_album': 851845082}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491522, 'titulo_cancion': 'Getaway Car', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967302, 'titulo_cancion': 'Lover', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1550966322, 'titulo_cancion': "Red (Taylor's Version)", 'id_album': 272247412}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1199760462, 'titulo_cancion': 'willow', 'id_album': 198167862}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1550966352, 'titulo_cancion': "All Too Well (Taylor's Version)", 'id_album': 272247412}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603270, 'titulo_cancion': 'One Dance', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609232, 'titulo_cancion': "God's Plan", 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 144572210, 'titulo_cancion': 'Passionfruit', 'id_album': 15685208}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603286, 'titulo_cancion': 'Hotline Bling', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025631, 'titulo_cancion': 'NOKIA', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1794149427, 'titulo_cancion': 'Massive', 'id_album': 328136527}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 144572232, 'titulo_cancion': 'Teenage Fever', 'id_album': 15685208}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347964, 'titulo_cancion': 'Headlines (Explicit Version)', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 500099532, 'titulo_cancion': 'Yes Indeed', 'id_album': 63595452}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144822, 'titulo_cancion': 'Girls Want Girls', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1050306812, 'titulo_cancion': 'Laugh Now Cry Later', 'id_album': 166946302}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609342, 'titulo_cancion': 'Nice For What', 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 947861082, 'titulo_cancion': 'Chicago Freestyle', 'id_album': 145596282}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144902, 'titulo_cancion': 'Yebba’s Heartbreak', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609392, 'titulo_cancion': 'In My Feelings', 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144852, 'titulo_cancion': 'Fair Trade', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603250, 'titulo_cancion': '9', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609402, 'titulo_cancion': 'Don’t Matter To Me', 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1470212372, 'titulo_cancion': 'She Will', 'id_album': 253060792}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 95254404, 'titulo_cancion': 'Know Yourself', 'id_album': 9691186}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347969, 'titulo_cancion': 'Marvins Room', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 2486117581, 'titulo_cancion': 'IDGAF', 'id_album': 496789121}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3444551431, 'titulo_cancion': 'What Did I Miss?', 'id_album': 782753961}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 919708552, 'titulo_cancion': 'Toosie Slide', 'id_album': 139608572}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 642673932, 'titulo_cancion': 'Girls Need Love (Remix)', 'id_album': 89198532}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 107878888, 'titulo_cancion': 'Jumpman', 'id_album': 11250516}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1024107672, 'titulo_cancion': 'POPSTAR (feat. Drake)', 'id_album': 161309222}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1999525127, 'titulo_cancion': 'Hours In Silence', 'id_album': 372625207}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 2486117711, 'titulo_cancion': 'Rich Baby Daddy', 'id_album': 496789121}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144892, 'titulo_cancion': 'Pipe Down', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603254, 'titulo_cancion': 'Feel No Ways', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144802, 'titulo_cancion': 'Champagne Poetry', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025641, 'titulo_cancion': 'DIE TRYING', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347961, 'titulo_cancion': 'Over My Dead Body', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347967, 'titulo_cancion': 'Take Care', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347963, 'titulo_cancion': 'Shot For Me', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 696957242, 'titulo_cancion': 'Money In The Grave', 'id_album': 100449132}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1024107692, 'titulo_cancion': 'GREECE (feat. Drake)', 'id_album': 161309242}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3476500411, 'titulo_cancion': 'Which One', 'id_album': 793705691}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603278, 'titulo_cancion': 'Too Good', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 5060528, 'titulo_cancion': 'Forever (Album Version Explicit)', 'id_album': 464090}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 2486117681, 'titulo_cancion': '8am in Charlotte', 'id_album': 496789121}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025521, 'titulo_cancion': 'SOMETHING ABOUT YOU', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603268, 'titulo_cancion': 'Controlla', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025501, 'titulo_cancion': 'CN TOWER', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 947861122, 'titulo_cancion': 'Time Flies', 'id_album': 145596282}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1733245187, 'titulo_cancion': 'WAIT FOR U (feat. Drake & Tems)', 'id_album': 314182407}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 70697364, 'titulo_cancion': "Hold On, We're Going Home (Album Version)", 'id_album': 6941024}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 947861092, 'titulo_cancion': 'Not You Too', 'id_album': 145596282}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1794149437, 'titulo_cancion': "Flight's Booked", 'id_album': 328136527}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676861, 'titulo_cancion': 'What I Want', 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399880071, 'titulo_cancion': 'Somebody’s Problem', 'id_album': 767572681}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398208101, 'titulo_cancion': 'More Than My Hometown', 'id_album': 767002431}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3595357382, 'titulo_cancion': 'Graveyard Whistling', 'id_album': 835419572}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676321, 'titulo_cancion': "Where'd That Girl Go", 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676251, 'titulo_cancion': 'Falling Apart', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 862201652, 'titulo_cancion': 'Heartless', 'id_album': 128890022}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398208091, 'titulo_cancion': '7 Summers', 'id_album': 767002421}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676291, 'titulo_cancion': '20 Cigarettes', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3278152451, 'titulo_cancion': 'Just In Case', 'id_album': 727297031}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329531, 'titulo_cancion': 'Last Night', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3206261161, 'titulo_cancion': "I'm The Problem", 'id_album': 704279041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3326163551, 'titulo_cancion': "I Ain't Comin' Back", 'id_album': 742935831}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2867668712, 'titulo_cancion': 'Lies Lies Lies', 'id_album': 608032792}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879451, 'titulo_cancion': 'Wasted On You', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676281, 'titulo_cancion': 'Kick Myself', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3161283401, 'titulo_cancion': 'Smile', 'id_album': 689514111}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329761, 'titulo_cancion': 'Thinkin’ Bout Me', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3040572191, 'titulo_cancion': 'Love Somebody', 'id_album': 655091621}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676191, 'titulo_cancion': 'I Got Better', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676941, 'titulo_cancion': 'TN', 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366677031, 'titulo_cancion': "Don't We", 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879591, 'titulo_cancion': 'Still Goin Down', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879611, 'titulo_cancion': 'Dangerous', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329191, 'titulo_cancion': 'Man Made A Bar', 'id_album': 767042901}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879651, 'titulo_cancion': 'This Bar', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2851520632, 'titulo_cancion': 'Whiskey Glasses', 'id_album': 603106342}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2851520612, 'titulo_cancion': 'Happy Hour', 'id_album': 603106342}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3471926691, 'titulo_cancion': 'Miami', 'id_album': 792132651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3278158621, 'titulo_cancion': "I'm A Little Crazy", 'id_album': 727300031}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329841, 'titulo_cancion': 'Cowgirls', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329671, 'titulo_cancion': 'You Proof', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329381, 'titulo_cancion': 'Tennessee Fan', 'id_album': 767042901}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 1593324851, 'titulo_cancion': 'Broadway Girls (feat. Morgan Wallen)', 'id_album': 280948461}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3792429142, 'titulo_cancion': 'McArthur', 'id_album': 903310122}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879681, 'titulo_cancion': 'Me On Whiskey', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2635850312, 'titulo_cancion': 'Spin You Around (1/24)', 'id_album': 539609802}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879551, 'titulo_cancion': 'Only Thing That’s Gone', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329121, 'titulo_cancion': 'Cover Me Up', 'id_album': 767042861}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366677011, 'titulo_cancion': 'Kiss Her In Front Of You', 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879661, 'titulo_cancion': 'Country A$$ Shit', 'id_album': 767572651}, {'id_artista': 7188840, 'n

In [23]:
df=pd.DataFrame(info_artista_cancion)

In [24]:
df.head(5)

,id_artista,nombre_artista,id_cancion,titulo_cancion,id_album
0,12246,Taylor Swift,3579685431,The Fate of Ophelia,829966251
1,12246,Taylor Swift,3579685451,Opalite,829966251
2,12246,Taylor Swift,89077547,Blank Space,9007781
3,12246,Taylor Swift,89077555,Shake It Off,9007781
4,12246,Taylor Swift,2512293211,Out Of The Woods (Taylor's Version),504180521

## Consulta de album por Id Canción (RUTA: ALBUM)

In [ ]:
def consulta_album(info_cancion):
    id_canciones = []
    info_album= []
    for cancion in info_cancion:
        id_cancion = cancion["id_cancion"]
        titulo_cancion = cancion["titulo_cancion"]
        id_album = cancion["id_album"]

        consulta_album = requests.get(f"https://api.deezer.com/album/{id_album}")

        if consulta_album.status_code != 200:
            print(f"No se pudo consultar la canción {id_cancion}: {titulo_cancion}.")
            continue

        datos_album = consulta_album.json()

        info_album.append({'id_cancion':{id_cancion}, 'titulo_cancion':{titulo_cancion}, 'id_album':{id_album},
                          'id_genre':datos_album['id_genre'],
                          'genre': datos_album['genres']['data']['name'], 
                          'año_de_lanzamiento':datos_album['release_date']})
    return info_album

In [46]:
canciones_a_buscar=info_artista_cancion
print(canciones_a_buscar)

[{'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685431, 'titulo_cancion': 'The Fate of Ophelia', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685451, 'titulo_cancion': 'Opalite', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077547, 'titulo_cancion': 'Blank Space', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077555, 'titulo_cancion': 'Shake It Off', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293211, 'titulo_cancion': "Out Of The Woods (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967292, 'titulo_cancion': 'Cruel Summer', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685441, 'titulo_cancion': 'Elizabeth Taylor', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685471, 'titulo_cancion': 'Eldest Daughter', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967452, 'titulo_cancion': 'Daylight', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2035609347, 'titulo_cancion': 'Anti-Hero (Acoustic Version)', 'id_album': 380094787}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077549, 'titulo_cancion': 'Style', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1976903157, 'titulo_cancion': 'Anti-Hero', 'id_album': 368474187}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685491, 'titulo_cancion': 'Actually Romantic', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1031382392, 'titulo_cancion': 'exile', 'id_album': 162683442}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1550966602, 'titulo_cancion': "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)", 'id_album': 272247412}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2757496031, 'titulo_cancion': 'I Can Do It With a Broken Heart', 'id_album': 575252501}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 529117841, 'titulo_cancion': 'We Are Never Ever Getting Back Together', 'id_album': 68491961}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1031382712, 'titulo_cancion': 'cardigan', 'id_album': 162683632}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293191, 'titulo_cancion': "Blank Space (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685501, 'titulo_cancion': 'Wi$h Li$t', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967412, 'titulo_cancion': 'You Need To Calm Down', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2753115381, 'titulo_cancion': 'Fortnight', 'id_album': 574109801}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1053765282, 'titulo_cancion': 'august', 'id_album': 167766152}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685461, 'titulo_cancion': 'Father Figure', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 595112162, 'titulo_cancion': 'I Don’t Wanna Live Forever (Fifty Shades Darker)', 'id_album': 80126642}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491472, 'titulo_cancion': 'Don’t Blame Me', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491492, 'titulo_cancion': 'Look What You Made Me Do', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1332677012, 'titulo_cancion': 'You Belong With Me (Taylor’s Version)', 'id_album': 221543452}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685551, 'titulo_cancion': 'CANCELLED!', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491452, 'titulo_cancion': 'End Game', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2917264, 'titulo_cancion': 'Love Story', 'id_album': 283925}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967342, 'titulo_cancion': 'Miss Americana & The Heartbreak Prince', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 89077561, 'titulo_cancion': 'Wildest Dreams', 'id_album': 9007781}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3579685481, 'titulo_cancion': 'Ruin The Friendship', 'id_album': 829966251}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293251, 'titulo_cancion': "Bad Blood (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491482, 'titulo_cancion': 'Delicate', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3852236971, 'titulo_cancion': 'Opalite (Ely Oaks Remix)', 'id_album': 922021001}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2757496121, 'titulo_cancion': 'So High School', 'id_album': 575252501}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2355587775, 'titulo_cancion': "Enchanted (Taylor's Version)", 'id_album': 461146065}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1332676982, 'titulo_cancion': 'Love Story (Taylor’s Version)', 'id_album': 221543452}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1977132317, 'titulo_cancion': 'Karma', 'id_album': 368506677}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1976903227, 'titulo_cancion': 'Bejeweled', 'id_album': 368474187}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2757496021, 'titulo_cancion': 'loml', 'id_album': 575252501}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 2512293201, 'titulo_cancion': "Style (Taylor's Version)", 'id_album': 504180521}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 3642533572, 'titulo_cancion': 'The Fate of Ophelia (Loud Luxury Remix)', 'id_album': 851845082}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 435491522, 'titulo_cancion': 'Getaway Car', 'id_album': 52612062}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 737967302, 'titulo_cancion': 'Lover', 'id_album': 108447472}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1550966322, 'titulo_cancion': "Red (Taylor's Version)", 'id_album': 272247412}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1199760462, 'titulo_cancion': 'willow', 'id_album': 198167862}, {'id_artista': 12246, 'nombre_artista': 'Taylor Swift', 'id_cancion': 1550966352, 'titulo_cancion': "All Too Well (Taylor's Version)", 'id_album': 272247412}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603270, 'titulo_cancion': 'One Dance', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609232, 'titulo_cancion': "God's Plan", 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 144572210, 'titulo_cancion': 'Passionfruit', 'id_album': 15685208}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603286, 'titulo_cancion': 'Hotline Bling', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025631, 'titulo_cancion': 'NOKIA', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1794149427, 'titulo_cancion': 'Massive', 'id_album': 328136527}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 144572232, 'titulo_cancion': 'Teenage Fever', 'id_album': 15685208}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347964, 'titulo_cancion': 'Headlines (Explicit Version)', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 500099532, 'titulo_cancion': 'Yes Indeed', 'id_album': 63595452}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144822, 'titulo_cancion': 'Girls Want Girls', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1050306812, 'titulo_cancion': 'Laugh Now Cry Later', 'id_album': 166946302}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609342, 'titulo_cancion': 'Nice For What', 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 947861082, 'titulo_cancion': 'Chicago Freestyle', 'id_album': 145596282}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144902, 'titulo_cancion': 'Yebba’s Heartbreak', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609392, 'titulo_cancion': 'In My Feelings', 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144852, 'titulo_cancion': 'Fair Trade', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603250, 'titulo_cancion': '9', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 533609402, 'titulo_cancion': 'Don’t Matter To Me', 'id_album': 69319552}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1470212372, 'titulo_cancion': 'She Will', 'id_album': 253060792}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 95254404, 'titulo_cancion': 'Know Yourself', 'id_album': 9691186}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347969, 'titulo_cancion': 'Marvins Room', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 2486117581, 'titulo_cancion': 'IDGAF', 'id_album': 496789121}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3444551431, 'titulo_cancion': 'What Did I Miss?', 'id_album': 782753961}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 919708552, 'titulo_cancion': 'Toosie Slide', 'id_album': 139608572}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 642673932, 'titulo_cancion': 'Girls Need Love (Remix)', 'id_album': 89198532}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 107878888, 'titulo_cancion': 'Jumpman', 'id_album': 11250516}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1024107672, 'titulo_cancion': 'POPSTAR (feat. Drake)', 'id_album': 161309222}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1999525127, 'titulo_cancion': 'Hours In Silence', 'id_album': 372625207}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 2486117711, 'titulo_cancion': 'Rich Baby Daddy', 'id_album': 496789121}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144892, 'titulo_cancion': 'Pipe Down', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603254, 'titulo_cancion': 'Feel No Ways', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1484144802, 'titulo_cancion': 'Champagne Poetry', 'id_album': 256312232}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025641, 'titulo_cancion': 'DIE TRYING', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347961, 'titulo_cancion': 'Over My Dead Body', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347967, 'titulo_cancion': 'Take Care', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 17347963, 'titulo_cancion': 'Shot For Me', 'id_album': 1622724}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 696957242, 'titulo_cancion': 'Money In The Grave', 'id_album': 100449132}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1024107692, 'titulo_cancion': 'GREECE (feat. Drake)', 'id_album': 161309242}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3476500411, 'titulo_cancion': 'Which One', 'id_album': 793705691}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603278, 'titulo_cancion': 'Too Good', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 5060528, 'titulo_cancion': 'Forever (Album Version Explicit)', 'id_album': 464090}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 2486117681, 'titulo_cancion': '8am in Charlotte', 'id_album': 496789121}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025521, 'titulo_cancion': 'SOMETHING ABOUT YOU', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 124603268, 'titulo_cancion': 'Controlla', 'id_album': 13082992}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 3232025501, 'titulo_cancion': 'CN TOWER', 'id_album': 712442261}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 947861122, 'titulo_cancion': 'Time Flies', 'id_album': 145596282}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1733245187, 'titulo_cancion': 'WAIT FOR U (feat. Drake & Tems)', 'id_album': 314182407}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 70697364, 'titulo_cancion': "Hold On, We're Going Home (Album Version)", 'id_album': 6941024}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 947861092, 'titulo_cancion': 'Not You Too', 'id_album': 145596282}, {'id_artista': 246791, 'nombre_artista': 'Drake', 'id_cancion': 1794149437, 'titulo_cancion': "Flight's Booked", 'id_album': 328136527}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676861, 'titulo_cancion': 'What I Want', 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399880071, 'titulo_cancion': 'Somebody’s Problem', 'id_album': 767572681}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398208101, 'titulo_cancion': 'More Than My Hometown', 'id_album': 767002431}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3595357382, 'titulo_cancion': 'Graveyard Whistling', 'id_album': 835419572}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676321, 'titulo_cancion': "Where'd That Girl Go", 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676251, 'titulo_cancion': 'Falling Apart', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 862201652, 'titulo_cancion': 'Heartless', 'id_album': 128890022}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398208091, 'titulo_cancion': '7 Summers', 'id_album': 767002421}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676291, 'titulo_cancion': '20 Cigarettes', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3278152451, 'titulo_cancion': 'Just In Case', 'id_album': 727297031}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329531, 'titulo_cancion': 'Last Night', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3206261161, 'titulo_cancion': "I'm The Problem", 'id_album': 704279041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3326163551, 'titulo_cancion': "I Ain't Comin' Back", 'id_album': 742935831}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2867668712, 'titulo_cancion': 'Lies Lies Lies', 'id_album': 608032792}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879451, 'titulo_cancion': 'Wasted On You', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676281, 'titulo_cancion': 'Kick Myself', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3161283401, 'titulo_cancion': 'Smile', 'id_album': 689514111}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329761, 'titulo_cancion': 'Thinkin’ Bout Me', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3040572191, 'titulo_cancion': 'Love Somebody', 'id_album': 655091621}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676191, 'titulo_cancion': 'I Got Better', 'id_album': 756668921}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366676941, 'titulo_cancion': 'TN', 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366677031, 'titulo_cancion': "Don't We", 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879591, 'titulo_cancion': 'Still Goin Down', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879611, 'titulo_cancion': 'Dangerous', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329191, 'titulo_cancion': 'Man Made A Bar', 'id_album': 767042901}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879651, 'titulo_cancion': 'This Bar', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2851520632, 'titulo_cancion': 'Whiskey Glasses', 'id_album': 603106342}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2851520612, 'titulo_cancion': 'Happy Hour', 'id_album': 603106342}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3471926691, 'titulo_cancion': 'Miami', 'id_album': 792132651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3278158621, 'titulo_cancion': "I'm A Little Crazy", 'id_album': 727300031}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329841, 'titulo_cancion': 'Cowgirls', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329671, 'titulo_cancion': 'You Proof', 'id_album': 767042911}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329381, 'titulo_cancion': 'Tennessee Fan', 'id_album': 767042901}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 1593324851, 'titulo_cancion': 'Broadway Girls (feat. Morgan Wallen)', 'id_album': 280948461}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3792429142, 'titulo_cancion': 'McArthur', 'id_album': 903310122}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879681, 'titulo_cancion': 'Me On Whiskey', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 2635850312, 'titulo_cancion': 'Spin You Around (1/24)', 'id_album': 539609802}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879551, 'titulo_cancion': 'Only Thing That’s Gone', 'id_album': 767572651}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3398329121, 'titulo_cancion': 'Cover Me Up', 'id_album': 767042861}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3366677011, 'titulo_cancion': 'Kiss Her In Front Of You', 'id_album': 756669041}, {'id_artista': 7188840, 'nombre_artista': 'Morgan Wallen', 'id_cancion': 3399879661, 'titulo_cancion': 'Country A$$ Shit', 'id_album': 767572651}, {'id_artista': 7188840, 'n

In [47]:
resultado=consulta_album(canciones_a_buscar)

KeyError: 'rank'

ID del artista
Nombre del artista
Título de la canción
Título del álbum

Tipo (colaboración, single, etc.)
Año de lanzamiento
Género
Id del género